/* XPM */
static char * circle_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"                        ",
"         ...            ",
"      ...   ...         ",
"     .         .        ",
"    .          XXX      ",
"    .          XoX      ",
"    .          XXX      ",
"   .     XXX     .      ",
"   .     XoX     .      ",
"   .     XXX     .      ",
"    .           .       ",
"    .           .       ",
"    .           .       ",
"     .         .        ",
"      ...   ...         ",
"         ...            ",
"                        ",
"                        ",
" ... ... ...  ... .  ...",
"..    .  . . ..   .  .  ",
".     .  . . .    .  .  ",
".     .  ..  .    .  .. ",
"..    .  . . ..   .  .  ",
" ... ... .  . ... ......"};

/* XPM */
static char * ellipse_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"                        ",
"                        ",
"      ..........        ",
"     .          .       ",
"    .            .      ",
"   .              .     ",
"   .              .     ",
"   .      XXX     .     ",
"   .      XoX     .     ",
"   .      XXX     .     ",
"   .              .     ",
"   .              .     ",
"    .            .      ",
"     .          .  XXX  ",
"      ..........   XoX  ",
"                   XXX  ",
"                        ",
"... .  .  ... .. ... ...",
".   .  .   .  . ..   .  ",
"... .  .   .  . ...  ...",
".   .  .   .  ..   . .  ",
".   .  .   .  .     ..  ",
"... ......... .  ... ...",
"                        "};

static char * curve_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"                        ",
"         ...            ",
"         .X.ooo         ",
"        o...   oo       ",
"      oo         oo     ",
"     o             o    ",
"     o              o   ",
"    o               ... ",
"    o               .X. ",
"   o                ... ",
"  ...                   ",
"  .X.                   ",
"  ...                   ",
"                        ",
"                        ",
"                        ",
" ooo o  o ooo o   o ooo ",
"oo   o  o o o o   o o   ",
"o    o  o o o  o o  ooo ",
"o    o  o oo   o o  o   ",
"oo   o  o o o  o o  o   ",
" ooo oooo o  o  o   ooo "};

/* XPM */
static char * line_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"  ...                   ",
"  .X.                   ",
"  ...                   ",
"     oo                 ",
"       oo               ",
"         oo             ",
"           oo           ",
"             oo         ",
"               oo       ",
"                 ...    ",
"                 .X.    ",
"                 ...    ",
"                        ",
"                        ",
"                        ",
"   o    ooo o  o  oooo  ",
"   o     o  oo o  o     ",
"   o     o  oo o  ooo   ",
"   o     o  o oo  o     ",
"   o     o  o oo  o     ",
"   oooo ooo o  o  oooo  ",
"                        "};


/* XPM */
static char * move_obj_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"       .                ",
" XXX    .  XXX          ",
" XoX ..... XoX          ",
" XXX    .  XXX          ",
"   X   .     .          ",
"    X         .         ",
"     X     .  .         ",
"     X      .  .        ",
"      X  .....  .       ",
"       X    .   .       ",
"        X  .     .      ",
"        XXX      XXX    ",
"        XoX      XoX    ",
"        XXX      XXX    ",
"                        ",
"                        ",
"                        ",
" .   .  ...  .   . .... ",
" .. .. .. .. .   . .    ",
" .. .. .   .  . .  ...  ",
" .. .. .   .  . .  .    ",
" . . . .. ..  ...  .    ",
" . . .  ...    .   .... ",
"                        "};

/* XPM */
static char * copy_obj_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"                        ",
"         .              ",
"  XXX     .  XXX        ",
"  XoX  ..... XoX        ",
"  XXX     .  XXX        ",
"    .    .     .        ",
"    .          .        ",
"     .          .       ",
"     .          .       ",
"     .     .    .       ",
"      .     .    .      ",
"      .  .....   .      ",
"       .    .     .     ",
"      XXX  .     XXX    ",
"      XoX        XoX    ",
"      XXX        XXX    ",
"                        ",
"  ....  ...  .... .   . ",
" ..    .. .. .  .  . .  ",
" .     .   . .  .  . .  ",
" .     .   . ...    .   ",
" ..  . .. .. .      .   ",
"  ....  ...  .      .   ",
"                        "};

/* XPM */
static char * move_point_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"                        ",
"  ...                   ",
"  .X.                   ",
"  ...oo                 ",
"    .  oo               ",
"    .    ooo  ...       ",
"     .      oo.X.       ",
"     .        ...       ",
"     .                  ",
"     .    oooo          ",
"      .     oo          ",
"      .    o o          ",
"     ...  o  o          ",
"     .X. o              ",
"     ...                ",
"                        ",
"oo oo     ooo o  oooooo ",
"o o o     o o oo o  o   ",
"o o o o o o o oo o  o   ",
"o o o o o ooo o oo  o   ",
"o o o o o o   o oo  o   ",
"o o o  o  o   o  o  o   "};



/* XPM */
static char * mini_cross_xpm[] = {
"16 14 4 1",
" 	c None s None",
".	c red",
"X	c gray50",
"o	c black",
"                ",
"           .    ",
"   ..X    ...   ",
"    ..X  .....  ",
"     .......oo  ",
"      .....o    ",
"      ....o     ",
"     ......     ",
"     ..o ...    ",
"    ..o   ...   ",
"    .o     ..X  ",
"   .o       .o  ",
"   o         o  ",
"                "};

/* XPM */
static char * blank_xpm[] = {
"18 17 1 1",
" 	c None",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  "};

/* XPM */
static char * Floppy6_xpm[] = {
"18 18 24 1",
" 	c None",
".	c #861782078617",
"X	c #5965596571C6",
"o	c #618565955965",
"O	c #596559659E79",
"+	c #0000000079E7",
"@	c #0820082071C6",
"#	c #9E799E790000",
"$	c #FFFFFFFF0000",
"%	c #186118614103",
"&	c #965896589E79",
"*	c #9E799E795965",
"=	c #000000006185",
"-	c #9E799E799E79",
";	c #FFFFFFFFFFFF",
":	c #000000000000",
">	c #71C675D69658",
",	c #BEFBBEFBBEFB",
"<	c #B6DAB2CABEFB",
"1	c #1040145171C6",
"2	c #28A228A28617",
"3	c #79E77DF78E38",
"4	c #A699A289A699",
"5	c #38E33CF379E7",
"                  ",
"  .XXoooooooooXO  ",
"  +@#$$$$$$$$$%+O ",
" &++*$$$$$$$$$%+O ",
" &+=-;;;;;;;;;%+O ",
" &==-;::;:;:;;%+O ",
" &++-;;;;;;;;;%+O ",
" &++-;:;:::;:;%+O ",
" &++-;;;;;;;;;%+O ",
" &+=>,,<,,,,,,1+O ",
" &++==========++O ",
" &+++22222222+++O ",
" &++;11>-333.+++O ",
" &++;++>43333+++O ",
" &++5++>4...3=++O ",
"  31+++======+++O ",
"   &&&&&&&&&&&&   ",
"                  "};

/* XPM */
static char * poly_xpm[] = {
"24 24 3 1",
" 	c None",
".	c red",
"X	c black",
"                        ",
"  ...            ...    ",
"  . .            . .    ",
"  ...            ...    ",
"   X X           X  X   ",
"   X  X         X    X  ",
"   X   X...  ...     ...",
"   X    . .  . .     . .",
"   X   X...  ...     ...",
"   X  X        X     X  ",
"  ...X          X   X   ",
"  . .            ...    ",
"  ...            . .    ",
"                 ...    ",
"                        ",
"                        ",
"                        ",
"  XXXX  XX  X   X   X   ",
"  X  X X  X X    X X    ",
"  X  X X  X X    X X    ",
"  XXX  X  X X     X     ",
"  X    X  X X     X     ",
"  X     XX  XXXX  X     ",
"                        "};

/* XPM */
static char * delete_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"                        ",
"   ...         .        ",
"   .X.        .         ",
"   ...o      .          ",
"       oo  ..           ",
"  ..................    ",
"         . oo           ",
"        .    oo         ",
"       .      ...       ",
"     ..       .X.       ",
"    .         ...       ",
"   .                    ",
"  .                     ",
"                        ",
"                        ",
"                        ",
"ooo  ooo o   ooooooooooo",
"o  o o   o   o    o  o  ",
"o  o ooo o   ooo  o  ooo",
"o  o o   o   o    o  o  ",
"o  o o   o   o    o  o  ",
"ooo  ooo ooooooo  o  ooo"};

/* XPM */
static char * star_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"           .            ",
"          ...           ",
"          . .           ",
"          . .           ",
"          . .           ",
"         .. ..     XXX  ",
"  ........   ......XoX  ",
"   ..         XXX .XXX  ",
"    ..    XXX XoX..     ",
"      ..  XoX XXX       ",
"       .. XXX ..        ",
"        .     .         ",
"       .   .   .        ",
"      .. ....  .        ",
"      . ..  .. .        ",
"      ...    ...        ",
"     ..        ..       ",
"     .          .       ",
"  ... .....  .   ...    ",
"  .     .   ...  . .    ",
"  ..    .   . .  . .    ",
"   ..   .   ...  ..     ",
"    .   .  .   . . .    ",
"  ...   .  .   . .  .   "};

/* XPM */
static char * spiral_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"  ...                   ",
"  .X.ooooooooooooooo    ",
"  ...              o    ",
"                   o    ",
"     oooooooooooo  o    ",
"     o          o  o    ",
"     o     ...  o  o    ",
"     o  ooo.X.  o  o    ",
"     o  o  ...  o  o    ",
"     o  o       o  o    ",
"     o  ooooooooo  o    ",
"     o             o    ",
"     o             o    ",
"     ooooooooooooooo    ",
"                        ",
"                        ",
"ooo ooo o ooo    o   o  ",
"o   o o o o o   ooo  o  ",
"oo  o o o o o   o o  o  ",
" oo ooo o oo    ooo  o  ",
"  o o   o o o  o   o o  ",
"ooo o   o o  o o   o ooo",
"                        "};

/* XPM */
static char * bezier_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"   ...              ... ",
"   .X.              .X. ",
"   ...             o... ",
"                  o     ",
"       ooooo      o     ",
"      o     oo   o      ",
"      o       ooo       ",
"     o                  ",
"     o          ...     ",
"    o           .X.     ",
"  ...           ...     ",
"  .X.                   ",
"  ...                   ",
"                        ",
"                        ",
"                        ",
" oooXooo ooo o ooo oo   ",
" o oXo     o o o   o o  ",
" oooXooo  o  o ooo o o  ",
" o oXo    o  o o   oo   ",
" o oXo   o   o o   o o  ",
" oooXooo ooo o ooo o o  ",
"                        "};


/* XPM */
static char * rulers_comp_xpm[] = {
"74 85 192 2",
"  	c None",
". 	c #965875D65144",
"X 	c #9E797DF75965",
"o 	c #861769A64103",
"O 	c #69A6555530C2",
"+ 	c #8E3871C64924",
"@ 	c #BEFB965869A6",
"# 	c #AEBA8A286185",
"$ 	c #79E765954103",
"% 	c #965879E75144",
"& 	c #C71B9E7971C6",
"* 	c #CF3CA28971C6",
"= 	c #A69982075965",
"- 	c #A69986175965",
"; 	c #8E386DB64924",
": 	c #AEBA86175965",
"> 	c #D75CA69979E7",
", 	c #8E3869A64103",
"< 	c #9E7982075965",
"1 	c #861765954103",
"2 	c #9E797DF75144",
"3 	c #79E75D7538E3",
"4 	c #9E7979E75144",
"5 	c #C71B9A6971C6",
"6 	c #71C6596538E3",
"7 	c #965871C64924",
"8 	c #79E761854103",
"9 	c #492434D32081",
"0 	c #38E328A21861",
"q 	c #208118610820",
"w 	c #28A220811040",
"e 	c #5965492428A2",
"r 	c #79E7618538E3",
"t 	c #28A21C711040",
"y 	c #28A218610820",
"u 	c #30C224921040",
"i 	c #410334D32081",
"p 	c #492438E32081",
"a 	c #5144410328A2",
"s 	c #5965451428A2",
"d 	c #B6DA8E386185",
"f 	c #38E32CB21861",
"g 	c #082008200000",
"h 	c #B6DA924869A6",
"j 	c #6185492428A2",
"k 	c #69A64D3430C2",
"l 	c #FFFFEBADCF3C",
"z 	c #49243CF32081",
"x 	c #410330C21861",
"c 	c #000000000000",
"v 	c #BEFB9A6969A6",
"b 	c #86176DB64924",
"n 	c #FFFFE79DC71B",
"m 	c #F7DED75C9E79",
"M 	c #FFFFE38DBEFB",
"N 	c #104008200000",
"B 	c #FFFFC71B6185",
"V 	c #FFFFAAAA0820",
"C 	c #FFFFA6990000",
"Z 	c #FFFFBAEA4103",
"A 	c #F7DEE38DBEFB",
"S 	c #28A224921040",
"D 	c #6185514430C2",
"F 	c #FFFFB2CA28A2",
"G 	c #FFFFA2890000",
"H 	c #FFFFAEBA1861",
"J 	c #61854D3430C2",
"K 	c #F7DED34C9658",
"L 	c #FFFFCB2B71C6",
"P 	c #71C6555530C2",
"I 	c #FFFFC30B5144",
"U 	c #FFFFBEFB4924",
"Y 	c #30C228A21861",
"T 	c #FFFFD75C9658",
"R 	c #186114510820",
"E 	c #F7DECF3C8617",
"W 	c #BEFB924869A6",
"Q 	c #CF3CA69971C6",
"! 	c #F7DEA2890000",
"~ 	c #79E76DB630C2",
"^ 	c #9E7979E72081",
"/ 	c #CF3C79E71040",
"( 	c #C71B7DF74103",
") 	c #30C220811040",
"_ 	c #51443CF32081",
"` 	c #69A6514430C2",
"' 	c #41032CB21861",
"] 	c #F7DE9E790000",
"[ 	c #BEFB82074103",
"{ 	c #CF3C8E381040",
"} 	c #EFBE92480820",
"| 	c #C71B924879E7",
" .	c #20811C711040",
"..	c #000004100000",
"X.	c #30C251444924",
"o.	c #E79D92480820",
"O.	c #A699514428A2",
"+.	c #FFFFFBEED75C",
"@.	c #FFFFFFFFE79D",
"#.	c #71C65D7538E3",
"$.	c #10400C300000",
"%.	c #E79D9A690820",
"&.	c #C71B82074103",
"*.	c #FFFFF7DEDF7D",
"=.	c #DF7DD75CD75C",
"-.	c #E79DE38DCF3C",
";.	c #FFFF9E790000",
":.	c #EFBE96580820",
">.	c #BEFB75D638E3",
",.	c #F7DEF7DEE79D",
"<.	c #F7DEEFBECF3C",
"1.	c #C71BC71BC71B",
"2.	c #D75CD34CC71B",
"3.	c #F7DEF3CECF3C",
"4.	c #DF7D8A280820",
"5.	c #A699555528A2",
"6.	c #DF7DDB6CC71B",
"7.	c #BEFBBEFBBEFB",
"8.	c #C71BC30BBEFB",
"9.	c #AEBA8E386185",
"0.	c #CF3C8A284924",
"q.	c #9E79A699A699",
"w.	c #71C686178617",
"e.	c #B6DAB6DAB6DA",
"r.	c #E79DE79DC71B",
"t.	c #8E3875D65144",
"y.	c #EFBEEBADCF3C",
"u.	c #A699AAAAAEBA",
"i.	c #CF3CCB2BC71B",
"p.	c #514438E32081",
"a.	c #492465956185",
"s.	c #8E3896589658",
"d.	c #BEFBBAEABEFB",
"f.	c #861786178617",
"g.	c #69A669A669A6",
"h.	c #69A66DB669A6",
"j.	c #D75C92480820",
"k.	c #30C234D330C2",
"l.	c #BEFB75D61861",
"z.	c #BEFB71C638E3",
"x.	c #208114510820",
"c.	c #E79D8A280820",
"v.	c #AEBAAAAAAEBA",
"b.	c #861782078617",
"n.	c #596559655965",
"m.	c #49244D344924",
"M.	c #C71B79E730C2",
"N.	c #AEBAB2CAAEBA",
"B.	c #AEBAAEBAAEBA",
"V.	c #A699A699A699",
"C.	c #C71BA28971C6",
"Z.	c #082004100000",
"A.	c #CF3C861730C2",
"S.	c #8E389A699E79",
"D.	c #9E79A289A699",
"F.	c #EFBEE79DC71B",
"G.	c #9E799A699E79",
"H.	c #FFFFF7DECF3C",
"J.	c #79E78A288E38",
"K.	c #208120812081",
"L.	c #618565956185",
"P.	c #F7DE9A690820",
"I.	c #41035D755965",
"U.	c #104014511040",
"Y.	c #D75C7DF71040",
"T.	c #B6DA69A630C2",
"R.	c #38E338E338E3",
"E.	c #965875D628A2",
"W.	c #EFBE9E7928A2",
"Q.	c #B6DA86171861",
"!.	c #CF3C8E384924",
"~.	c #C71B965879E7",
"^.	c #618575D671C6",
"/.	c #79E779E779E7",
"(.	c #71C675D671C6",
").	c #AEBA5D7528A2",
"_.	c #B6DA92486185",
"`.	c #8E388E388E38",
"'.	c #BEFB6DB628A2",
"].	c #DF7D86171040",
"[.	c #CF3C92481040",
"{.	c #861771C628A2",
"}.	c #514451445144",
"|.	c #BEFB861769A6",
" X	c #8E3871C628A2",
".X	c #C71B7DF730C2",
"XX	c #71C671C671C6",
"oX	c #B6DABAEABEFB",
"OX	c #104010401040",
"+X	c #69A6596538E3",
"@X	c #9E799E799E79",
"#X	c #79E77DF779E7",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"          . X                                                                                                                                       ",
"        o O O X                                                                                                                                     ",
"      + + @ # $                                                                                                                                     ",
"      $ % & * # $ =                                                                                                                                 ",
"      - ; : * > : , X                                                                                                                               ",
"        < o = & * : 1 2                                                                                                                             ",
"          = + # & & X 3 4                                                                                                                           ",
"            = . # 5 @ 3 6     # ; 3 ,                                                                                                               ",
"                7 % 4 7 6 8 6 9 0 q w 9 e ;                                                                                                         ",
"                = $ $ r 3 t y u 9 i p a u s 6 =                                                                                                     ",
"                  d # O f g i +     d h 3 j k 3                                   l l                                                               ",
"                      z g x = c -       v b q s                                 n m m M                                                             ",
"                    = t N p c c c X         3 t O                             M B V C Z A                                                           ",
"                    2 S p % c ; ; c O D     - x a                           n B F G C H B M                                                         ",
"                    7 w J   h c o $ c a     s q 9                         n K V C C C G C L M                                                       ",
"                      0 s     # c O P c .   j p f ,                     A I H C C C G C G H U M                                                     ",
"                      x Y =     J c c c c 6 6 c J P .                   L F G C G C C C G G H L T                                                   ",
"                      z R $       r = c o o c r # - + 2 -           n E G G C G C C G G C C C C C F                                                 ",
"                      ; 0 0 =       = c 4 W h x = Q h # 2 + X @   M I F C C d C G ! ~ ^ C C G G / (                                                 ",
"                        7 ) _ .     r c . d & _ ; & * * @ 2 ` `   K F G C 4 ' J C ] [ c { ] G } ( |                                                 ",
"                          ,  .q w  .c ; o D J _ a . : W * 5 @ < $ 6 4 C 4 x ..R $ C C c X.{ o.O.          +.@.                                      ",
"                            7 8 0 q 0 #.4 . 3 1 . + ; . # v & * : 7 o r p $.q #.C G G %.c ( &.          *.=.-.@.                                    ",
"                                h % J O - & @ 8 1 & h . #.#.- & * * h ; O f f G C C C ;.:.>.|         ,.<.1.2.3.                                    ",
"                                      7 % v Q d 4 v * W . o 1 o 2 5 * 5 h 7 O 8 - C G 4.5.          +.6.7.7.7.8.<.@.                                ",
"                                        . # * @ ; + v & 9.. . 8 j . @ 5 * & @ : 1 7 2 0.          ,.6.q.w.e.7.7.2.r.@.                              ",
"                                        2 4 & Q W j 2 h o #.. < _ 0 ; t.@ & Q * = 1 r + .       *.y.7.c c u.e.7.7.i.*.                              ",
"                                          o X * & 3 o = 6 o o p.g $.6 ; ; 7 9.* * @ : o $ 3 # @ =.1.7.e.c a.w.7.7.7.8.1.i.1.                        ",
"                                          2 6 W * # $ + ; o . ` R s c c % ; ; # & * & d # ; k ` = s.d.7.e.c s.7.7.7.7.f.g.h.                        ",
"                                          # ` 2 & & , 1 o a ` + e 8 G j.c h < ; 7 : v * * v - . r r . 7.7.7.7.7.7.7.d.k.c c                         ",
"                                            4 o # & = 3 a q q e ; 3 t.G c l.z.    7 , . W Q * & - 3 6 4 7.7.7.7.7.7.7.k.c c                         ",
"                                            E r , * 5 4 p x.a r 6 D 3 ;.c.0.|     - 6 D 1 # h * * * d % 2 ; 7.7.7.v.b.n.m.m.                        ",
"                                        n E G ; J d Q @ r s = C . 6 d } O.          +.# o D O # * Q * v h 4 r . : b...                              ",
"                                      n I F C G . ` & & 2 r C G C C / M.          *.=.i.d.. 4 ` # d 5 * * 5 4 r 6 n.                                ",
"                                      K H G G C #.9 @ Q 5 . o C ;.} ( |         *.y.N.B.7.7.V.= + b 2 d v * & C.: ` a ;                             ",
"                                  A L C C C W O Z.$.b 5 Q X 6 C c.O.          +.6.e.c c 7.7.7.7.7.# + b . d & * & P f p o                           ",
"                                n I F G G G 6 R c ' ` # * h + 4 A.          *.=.i.7.S.D.7.7.7.7.7.7.7.% + o o # - 6 O j O .                         ",
"                              n K H C C C G #.t x % . X v & d 2 #         ,.F.e.e.7.7.7.7.7.7.7.7.7.7.B.G.< ; o r p s 1 + . .                       ",
"                            A B V G C C G C G ; = C # ; 4 5 & # -       H.=.e.c J.7.7.7.7.7.7.7.7.7.7.n.K.    = s q Y #.9.h % %                     ",
"                          n B F C G G C G C C G G C C 4 1 - * d . -   ,.6.i.e.w.c J.e.7.7.7.7.7.7.B.L.h.        - P O ` 7 h @ , +                   ",
"                        M m C C C C C C C G G C C G G P.o . & & # o : y.e.d.7.7.J.I.B.7.7.7.7.7.e.G.U.                6 3 ; % p.o 2                 ",
"                        H H G G C C C C C C G G C G Y.T.  1 = * h 6 X N.c S.7.7.e.B.d.7.7.7.7.d.m.R.                  5 d E.J i ' t ;               ",
"                        W.4.G C C C :.Q.P.G C C ;.c.!.~.  #.t.* * 2 r N.^.V.7.7.7.7.7.7.7.7.v./.L.(.                        # d - 3 r               ",
"                        | ).P.G G C c X.{ G G G :.5.      4 1 _.* * 3 + 7.7.7.7.7.7.7.7.7.d.`...                                                    ",
"                            '.].C C %.[.~ {.C / >.          ; ; @ & 8 , 7.7.7.7.7.7.7.7.d.}.}.                                                      ",
"                            |.A.} G G C  Xc } &.|         ,.. + h * @ + 7 7.7.7.7.7.7.v.`.m.h.                                                      ",
"                                5.:.C G C c.O.          *.-.7.. . @ > W $ 1 7.7.7.d.7./...                                                          ",
"                                  M.Y.G / &.          +.=.q.c = o - * & + 6 7.7.7.e.}.L.                                                            ",
"                                  |..X:.>.~.        ,.y.8.s.a.B.; X & * d b , 7.B.G.R.XX                                                            ",
"                                      5.          +.6.8.7.d.e.7.7.; # * * X _ @ L.U.                                                                ",
"                                                *.=.c w.e.7.7.7.7.= = C.Q @ ` 4 h.                                                                  ",
"                                              ,.<.7.w.c u.oX7.7.7.# . # * & = 6 :                                                                   ",
"                                              =.8.7.e.c a.w.7.7.7.7.2 o # & h ` .                                                                   ",
"                                                i.XXG.e.w.s.7.7.7.7.7.6 7 * 5 4 ,                                                                   ",
"                                                  OXg.e.d.7.7.7.7.7.d.. , d W 7 O J                                                                 ",
"                                                    h.k.B.7.7.7.7.d.}.m.b +X+ s q w 7                                                               ",
"                                                      }./.@X7.7.B.b.n.h.. a $ $ e t 1                                                               ",
"                                                        K.}.d.d.f...      1 _ 9 #.r #.+                                                             ",
"                                                          #Xk.k.n.          #.u o h ; $ W                                                           ",
"                                                            c c m.            8 1 d 9.1 %                                                           ",
"                                                            c c m.              + + # 3 r d                                                         ",
"                                                                                  . 6 _ _ .                                                         ",
"                                                                                    < $ J 1                                                         ",
"                                                                                        4 $ #                                                       ",
"                                                                                        h ; d                                                       ",
"                                                                                          h                                                         ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    ",
"                                                                                                                                                    "};

