/* XPM */
static char * circle_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"                        ",
"         ...            ",
"      ...   ...         ",
"     .         .        ",
"    .          XXX      ",
"    .          XoX      ",
"    .          XXX      ",
"   .     XXX     .      ",
"   .     XoX     .      ",
"   .     XXX     .      ",
"    .           .       ",
"    .           .       ",
"    .           .       ",
"     .         .        ",
"      ...   ...         ",
"         ...            ",
"                        ",
"                        ",
" ... ... ...  ... .  ...",
"..    .  . . ..   .  .  ",
".     .  . . .    .  .  ",
".     .  ..  .    .  .. ",
"..    .  . . ..   .  .  ",
" ... ... .  . ... ......"};

/* XPM */
static char * ellipse_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"                        ",
"                        ",
"      ..........        ",
"     .          .       ",
"    .            .      ",
"   .              .     ",
"   .              .     ",
"   .      XXX     .     ",
"   .      XoX     .     ",
"   .      XXX     .     ",
"   .              .     ",
"   .              .     ",
"    .            .      ",
"     .          .  XXX  ",
"      ..........   XoX  ",
"                   XXX  ",
"                        ",
"... .  .  ... .. ... ...",
".   .  .   .  . ..   .  ",
"... .  .   .  . ...  ...",
".   .  .   .  ..   . .  ",
".   .  .   .  .     ..  ",
"... ......... .  ... ...",
"                        "};

static char * curve_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"                        ",
"         ...            ",
"         .X.ooo         ",
"        o...   oo       ",
"      oo         oo     ",
"     o             o    ",
"     o              o   ",
"    o               ... ",
"    o               .X. ",
"   o                ... ",
"  ...                   ",
"  .X.                   ",
"  ...                   ",
"                        ",
"                        ",
"                        ",
" ooo o  o ooo o   o ooo ",
"oo   o  o o o o   o o   ",
"o    o  o o o  o o  ooo ",
"o    o  o oo   o o  o   ",
"oo   o  o o o  o o  o   ",
" ooo oooo o  o  o   ooo "};

/* XPM */
static char * line_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"  ...                   ",
"  .X.                   ",
"  ...                   ",
"     oo                 ",
"       oo               ",
"         oo             ",
"           oo           ",
"             oo         ",
"               oo       ",
"                 ...    ",
"                 .X.    ",
"                 ...    ",
"                        ",
"                        ",
"                        ",
"   o    ooo o  o  oooo  ",
"   o     o  oo o  o     ",
"   o     o  oo o  ooo   ",
"   o     o  o oo  o     ",
"   o     o  o oo  o     ",
"   oooo ooo o  o  oooo  ",
"                        "};


/* XPM */
static char * move_obj_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"       .                ",
" XXX    .  XXX          ",
" XoX ..... XoX          ",
" XXX    .  XXX          ",
"   X   .     .          ",
"    X         .         ",
"     X     .  .         ",
"     X      .  .        ",
"      X  .....  .       ",
"       X    .   .       ",
"        X  .     .      ",
"        XXX      XXX    ",
"        XoX      XoX    ",
"        XXX      XXX    ",
"                        ",
"                        ",
"                        ",
" .   .  ...  .   . .... ",
" .. .. .. .. .   . .    ",
" .. .. .   .  . .  ...  ",
" .. .. .   .  . .  .    ",
" . . . .. ..  ...  .    ",
" . . .  ...    .   .... ",
"                        "};

/* XPM */
static char * copy_obj_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c black",
"X	c red",
"o	c white",
"                        ",
"         .              ",
"  XXX     .  XXX        ",
"  XoX  ..... XoX        ",
"  XXX     .  XXX        ",
"    .    .     .        ",
"    .          .        ",
"     .          .       ",
"     .          .       ",
"     .     .    .       ",
"      .     .    .      ",
"      .  .....   .      ",
"       .    .     .     ",
"      XXX  .     XXX    ",
"      XoX        XoX    ",
"      XXX        XXX    ",
"                        ",
"  ....  ...  .... .   . ",
" ..    .. .. .  .  . .  ",
" .     .   . .  .  . .  ",
" .     .   . ...    .   ",
" ..  . .. .. .      .   ",
"  ....  ...  .      .   ",
"                        "};

/* XPM */
static char * move_point_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"                        ",
"  ...                   ",
"  .X.                   ",
"  ...oo                 ",
"    .  oo               ",
"    .    ooo  ...       ",
"     .      oo.X.       ",
"     .        ...       ",
"     .                  ",
"     .    oooo          ",
"      .     oo          ",
"      .    o o          ",
"     ...  o  o          ",
"     .X. o              ",
"     ...                ",
"                        ",
"oo oo     ooo o  oooooo ",
"o o o     o o oo o  o   ",
"o o o o o o o oo o  o   ",
"o o o o o ooo o oo  o   ",
"o o o o o o   o oo  o   ",
"o o o  o  o   o  o  o   "};



/* XPM */
static char * mini_cross_xpm[] = {
"16 14 4 1",
" 	c None s None",
".	c red",
"X	c gray50",
"o	c black",
"                ",
"           .    ",
"   ..X    ...   ",
"    ..X  .....  ",
"     .......oo  ",
"      .....o    ",
"      ....o     ",
"     ......     ",
"     ..o ...    ",
"    ..o   ...   ",
"    .o     ..X  ",
"   .o       .o  ",
"   o         o  ",
"                "};

/* XPM */
static char * blank_xpm[] = {
"18 17 1 1",
" 	c None",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  ",
"                  "};

/* XPM */
static char * Floppy6_xpm[] = {
"18 18 24 1",
" 	c None",
".	c #861782078617",
"X	c #5965596571C6",
"o	c #618565955965",
"O	c #596559659E79",
"+	c #0000000079E7",
"@	c #0820082071C6",
"#	c #9E799E790000",
"$	c #FFFFFFFF0000",
"%	c #186118614103",
"&	c #965896589E79",
"*	c #9E799E795965",
"=	c #000000006185",
"-	c #9E799E799E79",
";	c #FFFFFFFFFFFF",
":	c #000000000000",
">	c #71C675D69658",
",	c #BEFBBEFBBEFB",
"<	c #B6DAB2CABEFB",
"1	c #1040145171C6",
"2	c #28A228A28617",
"3	c #79E77DF78E38",
"4	c #A699A289A699",
"5	c #38E33CF379E7",
"                  ",
"  .XXoooooooooXO  ",
"  +@#$$$$$$$$$%+O ",
" &++*$$$$$$$$$%+O ",
" &+=-;;;;;;;;;%+O ",
" &==-;::;:;:;;%+O ",
" &++-;;;;;;;;;%+O ",
" &++-;:;:::;:;%+O ",
" &++-;;;;;;;;;%+O ",
" &+=>,,<,,,,,,1+O ",
" &++==========++O ",
" &+++22222222+++O ",
" &++;11>-333.+++O ",
" &++;++>43333+++O ",
" &++5++>4...3=++O ",
"  31+++======+++O ",
"   &&&&&&&&&&&&   ",
"                  "};

/* XPM */
static char * poly_xpm[] = {
"24 24 3 1",
" 	c None",
".	c red",
"X	c black",
"                        ",
"  ...            ...    ",
"  . .            . .    ",
"  ...            ...    ",
"   X X           X  X   ",
"   X  X         X    X  ",
"   X   X...  ...     ...",
"   X    . .  . .     . .",
"   X   X...  ...     ...",
"   X  X        X     X  ",
"  ...X          X   X   ",
"  . .            ...    ",
"  ...            . .    ",
"                 ...    ",
"                        ",
"                        ",
"                        ",
"  XXXX  XX  X   X   X   ",
"  X  X X  X X    X X    ",
"  X  X X  X X    X X    ",
"  XXX  X  X X     X     ",
"  X    X  X X     X     ",
"  X     XX  XXXX  X     ",
"                        "};

/* XPM */
static char * delete_xpm[] = {
"24 24 4 1",
" 	s None	c None",
".	c red",
"X	c white",
"o	c black",
"                        ",
"                        ",
"                        ",
"   ...         .        ",
"   .X.        .         ",
"   ...o      .          ",
"       oo  ..           ",
"  ..................    ",
"         . oo           ",
"        .    oo         ",
"       .      ...       ",
"     ..       .X.       ",
"    .         ...       ",
"   .                    ",
"  .                     ",
"                        ",
"                        ",
"                        ",
"ooo  ooo o   ooooooooooo",
"o  o o   o   o    o  o  ",
"o  o ooo o   ooo  o  ooo",
"o  o o   o   o    o  o  ",
"o  o o   o   o    o  o  ",
"ooo  ooo ooooooo  o  ooo"};
