/* LIBGIMP - The GIMP Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * gimpdrawableedit_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__GIMP_H_INSIDE__) && !defined (GIMP_COMPILATION)
#error "Only <libgimp/gimp.h> can be included directly."
#endif

#ifndef __GIMP_DRAWABLE_EDIT_PDB_H__
#define __GIMP_DRAWABLE_EDIT_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */




#ifndef GIMP_DEPRECATED_REPLACE_NEW_API

gboolean gimp_drawable_edit_clear            (GimpDrawable     *drawable);
gboolean gimp_drawable_edit_fill             (GimpDrawable     *drawable,
                                              GimpFillType      fill_type);
gboolean gimp_drawable_edit_bucket_fill      (GimpDrawable     *drawable,
                                              GimpFillType      fill_type,
                                              gdouble           x,
                                              gdouble           y);
gboolean gimp_drawable_edit_gradient_fill    (GimpDrawable     *drawable,
                                              GimpGradientType  gradient_type,
                                              gdouble           offset,
                                              gboolean          supersample,
                                              gint              supersample_max_depth,
                                              gdouble           supersample_threshold,
                                              gboolean          dither,
                                              gdouble           x1,
                                              gdouble           y1,
                                              gdouble           x2,
                                              gdouble           y2);
gboolean gimp_drawable_edit_stroke_selection (GimpDrawable     *drawable);
gboolean gimp_drawable_edit_stroke_item      (GimpDrawable     *drawable,
                                              GimpItem         *item);

#else /* GIMP_DEPRECATED_REPLACE_NEW_API */

#define gimp_drawable_edit_clear _gimp_drawable_edit_clear
#define gimp_drawable_edit_fill _gimp_drawable_edit_fill
#define gimp_drawable_edit_bucket_fill _gimp_drawable_edit_bucket_fill
#define gimp_drawable_edit_gradient_fill _gimp_drawable_edit_gradient_fill
#define gimp_drawable_edit_stroke_selection _gimp_drawable_edit_stroke_selection
#define gimp_drawable_edit_stroke_item _gimp_drawable_edit_stroke_item


#endif /* GIMP_DEPRECATED_REPLACE_NEW_API */

/* Below API are deprecated and should not be used by new plug-ins.
 * They are not marked internal as a trick to keep the old API alive for now.
 */

gboolean _gimp_drawable_edit_clear            (gint32           drawable_ID);
gboolean _gimp_drawable_edit_fill             (gint32           drawable_ID,
                                               GimpFillType     fill_type);
gboolean _gimp_drawable_edit_bucket_fill      (gint32           drawable_ID,
                                               GimpFillType     fill_type,
                                               gdouble          x,
                                               gdouble          y);
gboolean _gimp_drawable_edit_gradient_fill    (gint32           drawable_ID,
                                               GimpGradientType gradient_type,
                                               gdouble          offset,
                                               gboolean         supersample,
                                               gint             supersample_max_depth,
                                               gdouble          supersample_threshold,
                                               gboolean         dither,
                                               gdouble          x1,
                                               gdouble          y1,
                                               gdouble          x2,
                                               gdouble          y2);
gboolean _gimp_drawable_edit_stroke_selection (gint32           drawable_ID);
gboolean _gimp_drawable_edit_stroke_item      (gint32           drawable_ID,
                                               gint32           item_ID);


G_END_DECLS

#endif /* __GIMP_DRAWABLE_EDIT_PDB_H__ */
