/* LIBGIMP - The GIMP Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * gimpunit_pdb.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__GIMP_H_INSIDE__) && !defined (GIMP_COMPILATION)
#error "Only <libgimp/gimp.h> can be included directly."
#endif

#ifndef __GIMP_UNIT_PDB_H__
#define __GIMP_UNIT_PDB_H__

G_BEGIN_DECLS

/* For information look into the C source or the html documentation */


GimpUnit*                gimp_unit_new                (const gchar  *name,
                                                       gdouble       factor,
                                                       gint          digits,
                                                       const gchar  *symbol,
                                                       const gchar  *abbreviation);
G_GNUC_INTERNAL gchar*   _gimp_unit_get_data          (gint          unit_id,
                                                       gdouble      *factor,
                                                       gint         *digits,
                                                       gchar       **symbol,
                                                       gchar       **abbreviation);
G_GNUC_INTERNAL gboolean _gimp_unit_get_deletion_flag (GimpUnit     *unit);
G_GNUC_INTERNAL gboolean _gimp_unit_set_deletion_flag (GimpUnit     *unit,
                                                       gboolean      deletion_flag);


G_END_DECLS

#endif /* __GIMP_UNIT_PDB_H__ */
