m4_include([m4macros/detectcflags.m4])
m4_include([m4macros/pythondev.m4])
m4_include([m4macros/gimpprint.m4])
m4_include([m4macros/alsa.m4])
m4_include([m4macros/gtk-doc.m4])
m4_include([m4macros/binreloc.m4])
