libgimpwidgets_introspectable_headers =	\
	../libgimpwidgets/gimpbrowser.h			\
	../libgimpwidgets/gimpbusybox.h			\
	../libgimpwidgets/gimpbutton.h			\
	../libgimpwidgets/gimpcairo-utils.h			\
	../libgimpwidgets/gimpcellrenderercolor.h		\
	../libgimpwidgets/gimpcellrenderertoggle.h		\
	../libgimpwidgets/gimpchainbutton.h			\
	../libgimpwidgets/gimpcolorarea.h			\
	../libgimpwidgets/gimpcolorbutton.h			\
	../libgimpwidgets/gimpcolordisplay.h			\
	../libgimpwidgets/gimpcolordisplaystack.h		\
	../libgimpwidgets/gimpcolorhexentry.h		\
	../libgimpwidgets/gimpcolornotebook.h		\
	../libgimpwidgets/gimpcolorprofilechooserdialog.h	\
	../libgimpwidgets/gimpcolorprofilecombobox.h		\
	../libgimpwidgets/gimpcolorprofilestore.h   		\
	../libgimpwidgets/gimpcolorprofileview.h    		\
##	../libgimpwidgets/gimpcolorscale.h
##	../libgimpwidgets/gimpcolorscales.h
##	../libgimpwidgets/gimpcolorselect.h
	../libgimpwidgets/gimpcolorselection.h      		\
	../libgimpwidgets/gimpcolorselector.h       		\
	../libgimpwidgets/gimpdialog.h	       		\
	../libgimpwidgets/gimpenumcombobox.h	       		\
	../libgimpwidgets/gimpenumlabel.h	       		\
	../libgimpwidgets/gimpenumstore.h	       		\
	../libgimpwidgets/gimpenumwidgets.h	       		\
	../libgimpwidgets/gimpfileentry.h	       		\
	../libgimpwidgets/gimpframe.h	       		\
	../libgimpwidgets/gimphelpui.h	       		\
	../libgimpwidgets/gimphintbox.h	       		\
	../libgimpwidgets/gimpicons.h	       		\
	../libgimpwidgets/gimpintcombobox.h	       		\
	../libgimpwidgets/gimpintstore.h	       		\
	../libgimpwidgets/gimpmemsizeentry.h	       		\
	../libgimpwidgets/gimpnumberpairentry.h     		\
	../libgimpwidgets/gimpoffsetarea.h	       		\
	../libgimpwidgets/gimppageselector.h	       		\
	../libgimpwidgets/gimppatheditor.h	       		\
	../libgimpwidgets/gimppickbutton.h	       		\
	../libgimpwidgets/gimppreview.h	       		\
	../libgimpwidgets/gimppreviewarea.h	       		\
	../libgimpwidgets/gimppropwidgets.h	       		\
	../libgimpwidgets/gimpquerybox.h	       		\
	../libgimpwidgets/gimpruler.h	       		\
	../libgimpwidgets/gimpscaleentry.h	       		\
	../libgimpwidgets/gimpscrolledpreview.h     		\
	../libgimpwidgets/gimpsizeentry.h	       		\
	../libgimpwidgets/gimpspinbutton.h	       		\
	../libgimpwidgets/gimpstringcombobox.h      		\
	../libgimpwidgets/gimpunitcombobox.h	       		\
	../libgimpwidgets/gimpunitstore.h	       		\
	../libgimpwidgets/gimpwidgets-error.h       		\
	../libgimpwidgets/gimpwidgets.h	       		\
	../libgimpwidgets/gimpwidgetsenums.h	       		\
	../libgimpwidgets/gimpwidgetstypes.h	       		\
	../libgimpwidgets/gimpwidgetsutils.h	       		\
	../libgimpwidgets/gimpzoommodel.h

libgimpwidgets_introspectable =	\
	../libgimpwidgets/gimpbrowser.c			\
	../libgimpwidgets/gimpbusybox.c			\
	../libgimpwidgets/gimpbutton.c			\
	../libgimpwidgets/gimpcairo-utils.c			\
	../libgimpwidgets/gimpcellrenderercolor.c		\
	../libgimpwidgets/gimpcellrenderertoggle.c		\
	../libgimpwidgets/gimpchainbutton.c			\
	../libgimpwidgets/gimpcolorarea.c			\
	../libgimpwidgets/gimpcolorbutton.c			\
	../libgimpwidgets/gimpcolordisplay.c			\
	../libgimpwidgets/gimpcolordisplaystack.c		\
	../libgimpwidgets/gimpcolorhexentry.c		\
	../libgimpwidgets/gimpcolornotebook.c		\
	../libgimpwidgets/gimpcolorprofilechooserdialog.c	\
	../libgimpwidgets/gimpcolorprofilecombobox.c		\
	../libgimpwidgets/gimpcolorprofilestore.c		\
	../libgimpwidgets/gimpcolorprofileview.c		\
##	../libgimpwidgets/gimpcolorscale.c
##	../libgimpwidgets/gimpcolorscales.c
##	../libgimpwidgets/gimpcolorselect.c
	../libgimpwidgets/gimpcolorselection.c		\
	../libgimpwidgets/gimpcolorselector.c		\
	../libgimpwidgets/gimpdialog.c			\
	../libgimpwidgets/gimpenumcombobox.c			\
	../libgimpwidgets/gimpenumlabel.c			\
	../libgimpwidgets/gimpenumstore.c			\
	../libgimpwidgets/gimpenumwidgets.c			\
	../libgimpwidgets/gimpfileentry.c			\
	../libgimpwidgets/gimpframe.c			\
	../libgimpwidgets/gimphelpui.c			\
	../libgimpwidgets/gimphintbox.c			\
	../libgimpwidgets/gimpicons.c			\
	../libgimpwidgets/gimpintcombobox.c			\
	../libgimpwidgets/gimpintstore.c			\
	../libgimpwidgets/gimpmemsizeentry.c			\
	../libgimpwidgets/gimpnumberpairentry.c		\
	../libgimpwidgets/gimpoffsetarea.c			\
	../libgimpwidgets/gimppageselector.c			\
	../libgimpwidgets/gimppatheditor.c			\
	../libgimpwidgets/gimppickbutton.c			\
	../libgimpwidgets/gimppreview.c			\
	../libgimpwidgets/gimppreviewarea.c			\
	../libgimpwidgets/gimppropwidgets.c			\
	../libgimpwidgets/gimpquerybox.c			\
	../libgimpwidgets/gimpruler.c			\
	../libgimpwidgets/gimpscaleentry.c			\
	../libgimpwidgets/gimpscrolledpreview.c		\
	../libgimpwidgets/gimpsizeentry.c			\
	../libgimpwidgets/gimpspinbutton.c			\
	../libgimpwidgets/gimpstringcombobox.c		\
	../libgimpwidgets/gimpunitcombobox.c			\
	../libgimpwidgets/gimpunitstore.c			\
	../libgimpwidgets/gimpwidgets-error.c		\
	../libgimpwidgets/gimpwidgets.c			\
	../libgimpwidgets/gimpwidgetsutils.c			\
	../libgimpwidgets/gimpzoommodel.c			\
	$(libgimpwidgets_introspectable_headers)
