libligmawidgets_introspectable_headers =	\
	../libligmawidgets/ligmabrowser.h			\
	../libligmawidgets/ligmabusybox.h			\
	../libligmawidgets/ligmabutton.h			\
	../libligmawidgets/ligmacairo-utils.h			\
	../libligmawidgets/ligmacellrenderercolor.h		\
	../libligmawidgets/ligmacellrenderertoggle.h		\
	../libligmawidgets/ligmachainbutton.h			\
	../libligmawidgets/ligmacolorarea.h			\
	../libligmawidgets/ligmacolorbutton.h			\
	../libligmawidgets/ligmacolordisplay.h			\
	../libligmawidgets/ligmacolordisplaystack.h		\
	../libligmawidgets/ligmacolorhexentry.h		\
	../libligmawidgets/ligmacolornotebook.h		\
	../libligmawidgets/ligmacolorprofilechooserdialog.h	\
	../libligmawidgets/ligmacolorprofilecombobox.h		\
	../libligmawidgets/ligmacolorprofilestore.h   		\
	../libligmawidgets/ligmacolorprofileview.h    		\
##	../libligmawidgets/ligmacolorscale.h
	../libligmawidgets/ligmacolorscaleentry.h	       		\
##	../libligmawidgets/ligmacolorscales.h
##	../libligmawidgets/ligmacolorselect.h
	../libligmawidgets/ligmacolorselection.h      		\
	../libligmawidgets/ligmacolorselector.h       		\
	../libligmawidgets/ligmadialog.h	       		\
	../libligmawidgets/ligmaenumcombobox.h	       		\
	../libligmawidgets/ligmaenumlabel.h	       		\
	../libligmawidgets/ligmaenumstore.h	       		\
	../libligmawidgets/ligmaenumwidgets.h	       		\
	../libligmawidgets/ligmafileentry.h	       		\
	../libligmawidgets/ligmaframe.h	       		\
	../libligmawidgets/ligmahelpui.h	       		\
	../libligmawidgets/ligmahintbox.h	       		\
	../libligmawidgets/ligmaicons.h	       		\
	../libligmawidgets/ligmaintcombobox.h	       		\
	../libligmawidgets/ligmaintradioframe.h	       		\
	../libligmawidgets/ligmaintstore.h	       		\
	../libligmawidgets/ligmalabelcolor.h			\
	../libligmawidgets/ligmalabeled.h				\
	../libligmawidgets/ligmalabelentry.h			\
	../libligmawidgets/ligmalabelintwidget.h			\
	../libligmawidgets/ligmalabelspin.h			\
	../libligmawidgets/ligmamemsizeentry.h	       		\
	../libligmawidgets/ligmanumberpairentry.h     		\
	../libligmawidgets/ligmaoffsetarea.h	       		\
	../libligmawidgets/ligmapageselector.h	       		\
	../libligmawidgets/ligmapatheditor.h	       		\
	../libligmawidgets/ligmapickbutton.h	       		\
	../libligmawidgets/ligmapreview.h	       		\
	../libligmawidgets/ligmapreviewarea.h	       		\
	../libligmawidgets/ligmapropwidgets.h	       		\
	../libligmawidgets/ligmaquerybox.h	       		\
	../libligmawidgets/ligmaruler.h	       		\
	../libligmawidgets/ligmascaleentry.h	       		\
	../libligmawidgets/ligmascrolledpreview.h     		\
	../libligmawidgets/ligmasizeentry.h	       		\
	../libligmawidgets/ligmaspinbutton.h	       		\
	../libligmawidgets/ligmaspinscale.h			\
	../libligmawidgets/ligmastringcombobox.h      		\
	../libligmawidgets/ligmaunitcombobox.h	       		\
	../libligmawidgets/ligmaunitstore.h	       		\
	../libligmawidgets/ligmawidgets-error.h       		\
	../libligmawidgets/ligmawidgets.h	       		\
	../libligmawidgets/ligmawidgetsenums.h	       		\
	../libligmawidgets/ligmawidgetstypes.h	       		\
	../libligmawidgets/ligmawidgetsutils.h	       		\
	../libligmawidgets/ligmazoommodel.h

libligmawidgets_introspectable =	\
	../libligmawidgets/ligmabrowser.c			\
	../libligmawidgets/ligmabusybox.c			\
	../libligmawidgets/ligmabutton.c			\
	../libligmawidgets/ligmacairo-utils.c			\
	../libligmawidgets/ligmacellrenderercolor.c		\
	../libligmawidgets/ligmacellrenderertoggle.c		\
	../libligmawidgets/ligmachainbutton.c			\
	../libligmawidgets/ligmacolorarea.c			\
	../libligmawidgets/ligmacolorbutton.c			\
	../libligmawidgets/ligmacolordisplay.c			\
	../libligmawidgets/ligmacolordisplaystack.c		\
	../libligmawidgets/ligmacolorhexentry.c		\
	../libligmawidgets/ligmacolornotebook.c		\
	../libligmawidgets/ligmacolorprofilechooserdialog.c	\
	../libligmawidgets/ligmacolorprofilecombobox.c		\
	../libligmawidgets/ligmacolorprofilestore.c		\
	../libligmawidgets/ligmacolorprofileview.c		\
##	../libligmawidgets/ligmacolorscale.c
	../libligmawidgets/ligmacolorscaleentry.c	       		\
##	../libligmawidgets/ligmacolorscales.c
##	../libligmawidgets/ligmacolorselect.c
	../libligmawidgets/ligmacolorselection.c		\
	../libligmawidgets/ligmacolorselector.c		\
	../libligmawidgets/ligmadialog.c			\
	../libligmawidgets/ligmaenumcombobox.c			\
	../libligmawidgets/ligmaenumlabel.c			\
	../libligmawidgets/ligmaenumstore.c			\
	../libligmawidgets/ligmaenumwidgets.c			\
	../libligmawidgets/ligmafileentry.c			\
	../libligmawidgets/ligmaframe.c			\
	../libligmawidgets/ligmahelpui.c			\
	../libligmawidgets/ligmahintbox.c			\
	../libligmawidgets/ligmaicons.c			\
	../libligmawidgets/ligmaintcombobox.c			\
	../libligmawidgets/ligmaintradioframe.c	       		\
	../libligmawidgets/ligmaintstore.c			\
	../libligmawidgets/ligmalabelcolor.c			\
	../libligmawidgets/ligmalabeled.c				\
	../libligmawidgets/ligmalabelentry.c			\
	../libligmawidgets/ligmalabelintwidget.c			\
	../libligmawidgets/ligmalabelspin.c			\
	../libligmawidgets/ligmamemsizeentry.c			\
	../libligmawidgets/ligmanumberpairentry.c		\
	../libligmawidgets/ligmaoffsetarea.c			\
	../libligmawidgets/ligmapageselector.c			\
	../libligmawidgets/ligmapatheditor.c			\
	../libligmawidgets/ligmapickbutton.c			\
	../libligmawidgets/ligmapreview.c			\
	../libligmawidgets/ligmapreviewarea.c			\
	../libligmawidgets/ligmapropwidgets.c			\
	../libligmawidgets/ligmaquerybox.c			\
	../libligmawidgets/ligmaruler.c			\
	../libligmawidgets/ligmascaleentry.c			\
	../libligmawidgets/ligmascrolledpreview.c		\
	../libligmawidgets/ligmasizeentry.c			\
	../libligmawidgets/ligmaspinbutton.c			\
	../libligmawidgets/ligmaspinscale.c			\
	../libligmawidgets/ligmastringcombobox.c		\
	../libligmawidgets/ligmaunitcombobox.c			\
	../libligmawidgets/ligmaunitstore.c			\
	../libligmawidgets/ligmawidgets-error.c		\
	../libligmawidgets/ligmawidgets.c			\
	../libligmawidgets/ligmawidgetsutils.c			\
	../libligmawidgets/ligmazoommodel.c			\
	$(libligmawidgets_introspectable_headers)
