/* The GIMP -- an image manipulation program
 * Copyright (C) 1995 Spencer Kimball and Peter Mattis
 *
 * gimphelp-ids.h
 * Copyright (C) 2003 Michael Natterer <mitch@gimp.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef __GIMP_HELP_IDS_H__
#define __GIMP_HELP_IDS_H__


#define GIMP_HELP_FILE_NEW                  "file/dialogs/file_new.html"
#define GIMP_HELP_FILE_NEW_CONFIRM          "file/dialogs/file_new.html#confirm_dialog"
#define GIMP_HELP_FILE_OPEN                 "file/dialogs/file_open.html"
#define GIMP_HELP_FILE_SAVE                 "file/dialogs/file_save.html"
#define GIMP_HELP_FILE_SAVE_AS              "file/dialogs/file_save.html"
#define GIMP_HELP_FILE_SAVE_A_COPY          "file/dialogs/file_save.html"
#define GIMP_HELP_FILE_SAVE_AS_TEMPLATE     "file/dialogs/file_save.html"
#define GIMP_HELP_FILE_SAVE_OVERWRITE       "file/dialogs/file_exists.html"
#define GIMP_HELP_FILE_REVERT               "file/revert.html"
#define GIMP_HELP_FILE_CLOSE                "file/close.html"
#define GIMP_HELP_FILE_QUIT                 "file/quit.html"

#define GIMP_HELP_EDIT_UNDO                 "edit/undo.html"
#define GIMP_HELP_EDIT_REDO                 "edit/redo.html"
#define GIMP_HELP_EDIT_CUT                  "edit/cut.html"
#define GIMP_HELP_EDIT_COPY                 "edit/copy.html"
#define GIMP_HELP_EDIT_PASTE                "edit/paste.html"
#define GIMP_HELP_EDIT_PASTE_INTO           "edit/paste_into.html"
#define GIMP_HELP_EDIT_PASTE_AS_NEW         "edit/paste_as_new.html"
#define GIMP_HELP_EDIT_CLEAR                "edit/clear.html"
#define GIMP_HELP_EDIT_FILL_FG              "edit/fill.html"
#define GIMP_HELP_EDIT_FILL_BG              "edit/fill.html"
#define GIMP_HELP_EDIT_FILL_PATTERN         "edit/fill.html"
#define GIMP_HELP_EDIT_STROKE_SELECTION     "edit/stroke.html"
#define GIMP_HELP_EDIT_STROKE_PATH          "edit/stroke.html"

#define GIMP_HELP_SELECT_DIALOG             "dialogs/selection_editor.html"
#define GIMP_HELP_SELECT_ALL                "select/all.html"
#define GIMP_HELP_SELECT_NONE               "select/none.html"
#define GIMP_HELP_SELECT_INVERT             "select/invert.html"
#define GIMP_HELP_SELECT_FLOAT              "select/float.html"
#define GIMP_HELP_SELECT_FEATHER            "select/dialogs/feather_selection.html"
#define GIMP_HELP_SELECT_SHARPEN            "select/sharpen.html"
#define GIMP_HELP_SELECT_SHRINK             "select/dialogs/shrink_selection.html"
#define GIMP_HELP_SELECT_GROW               "select/dialogs/grow_selection.html"
#define GIMP_HELP_SELECT_BORDER             "select/dialogs/border_selection.html"
#define GIMP_HELP_SELECT_QUICKMASK          "select/quickmask.html"
#define GIMP_HELP_SELECT_SAVE_TO_CHANNEL    "select/save_to_channel.html"

#define GIMP_HELP_VIEW_NEW                  "view/new.html"
#define GIMP_HELP_VIEW_DOT_FOR_DOT          "view/dot_for_dot.html"
#define GIMP_HELP_VIEW_ZOOM                 "view/zoom.html"
#define GIMP_HELP_VIEW_ZOOM_TO_FIT          "view/zoom.html"
#define GIMP_HELP_VIEW_SHOW_SELECTION       "view/toggle_selection.html"
#define GIMP_HELP_VIEW_SHOW_LAYER_BOUNDARY  "view/toggle_selection.html"
#define GIMP_HELP_VIEW_SHOW_GUIDES          "view/toggle_guides.html"
#define GIMP_HELP_VIEW_SNAP_TO_GUIDES       "view/gnap_to_guides.html"
#define GIMP_HELP_VIEW_SHOW_GRID            "view/toggle_grid.html"
#define GIMP_HELP_VIEW_SNAP_TO_GRID         "view/snap_to_grid.html"
#define GIMP_HELP_VIEW_SHOW_MENUBAR         "view/toggle_menubar.html"
#define GIMP_HELP_VIEW_SHOW_RULERS          "view/toggle_rulers.html"
#define GIMP_HELP_VIEW_SHOW_SCROLLBARS      "view/toggle_scrollbars.html"
#define GIMP_HELP_VIEW_SHOW_STATUSBAR       "view/toggle_statusbar.html"
#define GIMP_HELP_VIEW_SHRINK_WRAP          "view/shrink_wrap.html"
#define GIMP_HELP_VIEW_FULLSCREEN           "view/fullscreen.html"

#define GIMP_HELP_IMAGE_DIALOG              "dialogs/image_dialog.html"
#define GIMP_HELP_IMAGE_CONVERT_RGB         "image/mode/convert_to_rgb.html"
#define GIMP_HELP_IMAGE_CONVERT_GRAYSCALE   "image/mode/convert_to_grayscale.html"
#define GIMP_HELP_IMAGE_CONVERT_INDEXED     "image/mode/convert_to_indexed.html"
#define GIMP_HELP_IMAGE_FLIP_HORIZONTAL     "image/dialogs/flip_image.html"
#define GIMP_HELP_IMAGE_FLIP_VERTICAL       "image/dialogs/flip_image.html"
#define GIMP_HELP_IMAGE_ROTATE_90           "image/dialogs/rotate_image.html"
#define GIMP_HELP_IMAGE_ROTATE_180          "image/dialogs/rotate_image.html"
#define GIMP_HELP_IMAGE_ROTATE_270          "image/dialogs/rotate_image.html"
#define GIMP_HELP_IMAGE_RESIZE              "image/dialogs/set_canvas_size.html"
#define GIMP_HELP_IMAGE_SCALE               "image/dialogs/scale_image.html"
#define GIMP_HELP_IMAGE_CROP                "image/dialogs/crop_image.html"
#define GIMP_HELP_IMAGE_DUPLICATE           "image/duplicate.html"
#define GIMP_HELP_IMAGE_MERGE_LAYERS        "layers/dialogs/merge_visible_layers.html"
#define GIMP_HELP_IMAGE_FLATTEN             "layers/flatten_image.html"
#define GIMP_HELP_IMAGE_GRID                "image/dialogs/configure_grid.html"

#define GIMP_HELP_LAYER_DIALOG              "layers/dialogs/layers_dialog.html"
#define GIMP_HELP_LAYER_NEW                 "layers/dialogs/new_layer.html"
#define GIMP_HELP_LAYER_DUPLICATE           "layers/duplicate_layer.html"
#define GIMP_HELP_LAYER_ANCHOR              "layers/anchor_layer.html"
#define GIMP_HELP_LAYER_MERGE_DOWN          "layers/merge_down.html"
#define GIMP_HELP_LAYER_DELETE              "layers/delete_layer.html"
#define GIMP_HELP_LAYER_PREVIOUS            "layers/stack/stack.html#previous_layer"
#define GIMP_HELP_LAYER_NEXT                "layers/stack/stack.html#next_layer"
#define GIMP_HELP_LAYER_TOP                 "layers/stack/stack.html#previous_layer"
#define GIMP_HELP_LAYER_BOTTOM              "layers/stack/stack.html#next_layer"
#define GIMP_HELP_LAYER_RAISE               "layers/stack/stack.html#raise_layer"
#define GIMP_HELP_LAYER_LOWER               "layers/stack/stack.html#lower_layer"
#define GIMP_HELP_LAYER_RAISE_TO_TOP        "layers/stack/stack.html#layer_to_top"
#define GIMP_HELP_LAYER_LOWER_TO_BOTTOM     "layers/stack/stack.html#layer_to_bottom"
#define GIMP_HELP_LAYER_DESATURATE          "layers/colors/desaturate.html"
#define GIMP_HELP_LAYER_INVERT              "layers/colors/invert.html"
#define GIMP_HELP_LAYER_EQUALIZE            "layers/colors/auto/equalize.html"
#define GIMP_HELP_LAYER_MASK_ADD            "layers/dialogs/add_layer_mask.html"
#define GIMP_HELP_LAYER_MASK_APPLY          "layers/apply_mask.html"
#define GIMP_HELP_LAYER_MASK_DELETE         "layers/delete_mask.html"
#define GIMP_HELP_LAYER_MASK_SEL_REPLACE    "layers/mask_to_selection.html"
#define GIMP_HELP_LAYER_MASK_SEL_ADD        "layers/mask_to_selection.html#add"
#define GIMP_HELP_LAYER_MASK_SEL_SUB        "layers/mask_to_selection.html#subtract"
#define GIMP_HELP_LAYER_MASK_SEL_INTERSECT  "layers/mask_to_selection.html#intersect"
#define GIMP_HELP_LAYER_ALPHA_ADD           "layers/add_alpha_channel.html"
#define GIMP_HELP_LAYER_ALPHA_SEL_REPLACE   "layers/alpha_to_selection.html"
#define GIMP_HELP_LAYER_ALPHA_SEL_ADD       "layers/alpha_to_selection.html#add"
#define GIMP_HELP_LAYER_ALPHA_SEL_SUB       "layers/alpha_to_selection.html#subtract"
#define GIMP_HELP_LAYER_ALPHA_SEL_INTERSECT "layers/alpha_to_selection.html#intersect"
#define GIMP_HELP_LAYER_FLIP_HORIZONTAL     "layers/flip_layer.html"
#define GIMP_HELP_LAYER_FLIP_VERTICAL       "layers/flip_layer.html"
#define GIMP_HELP_LAYER_ROTATE_90           "layers/rotate_layer.html"
#define GIMP_HELP_LAYER_ROTATE_180          "layers/rotate_layer.html"
#define GIMP_HELP_LAYER_ROTATE_270          "layers/rotate_layer.html"
#define GIMP_HELP_LAYER_OFFSET              "layers/dialogs/offset.html"
#define GIMP_HELP_LAYER_RESIZE              "layers/dialogs/layer_boundary_size.html"
#define GIMP_HELP_LAYER_RESIZE_TO_IMAGE     "layers/layer_to_image_size.html"
#define GIMP_HELP_LAYER_SCALE               "layers/dialogs/scale_layer.html"
#define GIMP_HELP_LAYER_CROP                "layers/dialogs/crop_layer.html"
#define GIMP_HELP_LAYER_EDIT                "layers/dialogs/edit_layer_attributes.html"

#define GIMP_HELP_CHANNEL_DIALOG            "channels/dialogs/channels_dialog.html"
#define GIMP_HELP_CHANNEL_NEW               "channels/dialogs/new_channel.html"
#define GIMP_HELP_CHANNEL_RAISE             "channels/raise_channel.html"
#define GIMP_HELP_CHANNEL_LOWER             "channels/lower_channel.html"
#define GIMP_HELP_CHANNEL_DUPLICATE         "channels/duplicate_channel.html"
#define GIMP_HELP_CHANNEL_DELETE            "channels/delete_channel.html"
#define GIMP_HELP_CHANNEL_SEL_REPLACE       "channels/channel_to_selection.html"
#define GIMP_HELP_CHANNEL_SEL_ADD           "channels/channel_to_selection.html#add"
#define GIMP_HELP_CHANNEL_SEL_SUB           "channels/channel_to_selection.html#subtract"
#define GIMP_HELP_CHANNEL_SEL_INTERSECT     "channels/channel_to_selection.html#intersect"
#define GIMP_HELP_CHANNEL_EDIT              "channels/dialogs/edit_channel_attributes.html"

#define GIMP_HELP_PATH_DIALOG               "paths/dislogs/paths_dialog.html"
#define GIMP_HELP_PATH_NEW                  "paths/new_path.html"
#define GIMP_HELP_PATH_RAISE                "paths/raise_path.html"
#define GIMP_HELP_PATH_LOWER                "paths/lower_path.html"
#define GIMP_HELP_PATH_DUPLICATE            "paths/duplicate_path.html"
#define GIMP_HELP_PATH_DELETE               "paths/delete_path.html"
#define GIMP_HELP_PATH_SEL_REPLACE          "paths/path_to_selection.html"
#define GIMP_HELP_PATH_SEL_ADD              "paths/path_to_selection.html#add"
#define GIMP_HELP_PATH_SEL_SUB              "paths/path_to_selection.html#subtract"
#define GIMP_HELP_PATH_SEL_INTERSECT        "paths/path_to_selection.html#intersect"
#define GIMP_HELP_PATH_STROKE               "paths/stroke_path.html"
#define GIMP_HELP_PATH_COPY                 "paths/copy_path.html"
#define GIMP_HELP_PATH_PASTE                "paths/paste_path.html"
#define GIMP_HELP_PATH_IMPORT               "paths/dialogs/import_path.html"
#define GIMP_HELP_PATH_EXPORT               "paths/dialogs/export_path.html"
#define GIMP_HELP_PATH_EDIT                 "paths/dialogs/edit_path_attributes.html"

#define GIMP_HELP_TOOL_BY_COLOR_SELECT      "tools/by_color_select.html"
#define GIMP_HELP_TOOL_COLOR_BALANCE        "tools/color_balance.html"
#define GIMP_HELP_TOOL_HUE_SATURATION       "tools/hue_saturation.html"
#define GIMP_HELP_TOOL_COLORIZE             "tools/colorize.html"
#define GIMP_HELP_TOOL_BRIGHTNESS_CONTRAST  "tools/brightness-contrast.html"
#define GIMP_HELP_TOOL_THRESHOLD            "tools/threshold.html"
#define GIMP_HELP_TOOL_LEVELS               "tools/levels.html"
#define GIMP_HELP_TOOL_CURVES               "tools/curves.html"
#define GIMP_HELP_TOOL_POSTERIZE            "tools/posterize.html"
#define GIMP_HELP_TOOL_HISTOGRAM            "tools/histogram.html"
#define GIMP_HELP_TOOL_ROTATE               "tools/rotate.html"
#define GIMP_HELP_TOOL_VECTORS              "tools/vectors.html"

#define GIMP_HELP_FILTER_REPEAT             "filters/repeat_last.html"
#define GIMP_HELP_FILTER_RESHOW             "filters/reshow_last.html"

#define GIMP_HELP_TOOLBOX                   "toolbox/toolbox.html"
#define GIMP_HELP_TOOLBOX_DEFAULT_COLORS    "toolbox/toolbox.html#default_colors"
#define GIMP_HELP_TOOLBOX_SWAP_COLORS       "toolbox/toolbox.html#swap_colors"

#define GIMP_HELP_BRUSH_DIALOG              "dialogs/brush_selection.html"
#define GIMP_HELP_BRUSH_NEW                 "dialogs/brush_selection.html"
#define GIMP_HELP_BRUSH_DUPLICATE           "dialogs/brush_selection.html"
#define GIMP_HELP_BRUSH_EDIT                "dialogs/brush_selection.html"
#define GIMP_HELP_BRUSH_DELETE              "dialogs/brush_selection.html"
#define GIMP_HELP_BRUSH_REFRESH             "dialogs/brush_selection.html"

#define GIMP_HELP_PATTERN_DIALOG            "dialogs/pattern_selection.html"
#define GIMP_HELP_PATTERN_NEW               "dialogs/pattern_selection.html"
#define GIMP_HELP_PATTERN_DUPLICATE         "dialogs/pattern_selection.html"
#define GIMP_HELP_PATTERN_EDIT              "dialogs/pattern_selection.html"
#define GIMP_HELP_PATTERN_DELETE            "dialogs/pattern_selection.html"
#define GIMP_HELP_PATTERN_REFRESH           "dialogs/pattern_selection.html"

#define GIMP_HELP_GRADIENT_DIALOG           "dialogs/gradient_selection.html"
#define GIMP_HELP_GRADIENT_NEW              "dialogs/gradient_selection.html"
#define GIMP_HELP_GRADIENT_DUPLICATE        "dialogs/gradient_selection.html"
#define GIMP_HELP_GRADIENT_EDIT             "dialogs/gradient_selection.html"
#define GIMP_HELP_GRADIENT_DELETE           "dialogs/gradient_selection.html"
#define GIMP_HELP_GRADIENT_REFRESH          "dialogs/gradient_selection.html"
#define GIMP_HELP_GRADIENT_SAVE_AS_POV      "dialogs/gradient_selection.html"

#define GIMP_HELP_PALETTE_DIALOG            "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_NEW               "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_DUPLICATE         "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_EDIT              "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_DELETE            "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_REFRESH           "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_IMPORT            "dialogs/palette_selection.html"
#define GIMP_HELP_PALETTE_MERGE             "dialogs/palette_selection.html"

#define GIMP_HELP_FONT_DIALOG               "dialogs/font_selection.html"

#define GIMP_HELP_BUFFER_DIALOG             "dialogs/named_buffers.html"
#define GIMP_HELP_BUFFER_CUT                "dialogs/cut_named.html"
#define GIMP_HELP_BUFFER_COPY               "dialogs/copy_named.html"
#define GIMP_HELP_BUFFER_PASTE              "dialogs/paste_named.html"
#define GIMP_HELP_BUFFER_PASTE_INTO         "dialogs/paste_named.html"
#define GIMP_HELP_BUFFER_PASTE_AS_NEW       "dialogs/paste_named.html"
#define GIMP_HELP_BUFFER_DELETE             "dialogs/delete_buffer.html"

#define GIMP_HELP_TEMPLATE_DIALOG           "dialogs/templates.html"
#define GIMP_HELP_TEMPLATE_NEW              "dialogs/templates.html"
#define GIMP_HELP_TEMPLATE_DUPLICATE        "dialogs/templates.html"
#define GIMP_HELP_TEMPLATE_EDIT             "dialogs/templates.html"
#define GIMP_HELP_TEMPLATE_IMAGE_NEW        "dialogs/templates.html"
#define GIMP_HELP_TEMPLATE_DELETE           "dialogs/templates.html"

#define GIMP_HELP_PREFERENCES_DIALOG        "file/dialogs/preferences/preferences.html"

#define GIMP_HELP_COLOR_DIALOG              "dialogs/color.html"
#define GIMP_HELP_TOOL_OPTIONS_DIALOG       "dialogs/tool_options.html"
#define GIMP_HELP_DEVICE_STATUS_DIALOG      "dialogs/device_status.html"
#define GIMP_HELP_DOCUMENT_DIALOG           "file/dialogs/document_index.html"
#define GIMP_HELP_MODULE_DIALOG             "dialogs/module_manager.html"
#define GIMP_HELP_INFO_DIALOG               "view/dialogs/info_window.html"
#define GIMP_HELP_NAVIGATION_DIALOG         "view/dialogs/navigation_window.html"
#define GIMP_HELP_DISPLAY_FILTER_DIALOG     "dialogs/display_filters/display_filters.html"
#define GIMP_HELP_UNDO_DIALOG               "dialogs/undo_history.html"
#define GIMP_HELP_INDEXED_PALETTE_DIALOG    "dialogs/indexed_palette.html"
#define GIMP_HELP_ERROR_DIALOG              "dialogs/error_console.html"
#define GIMP_HELP_TIPS_DIALOG               "help/dialogs/tip_of_the_day.html"
#define GIMP_HELP_ABOUT_DIALOG              "help/dialogs/about.html"

#define GIMP_HELP_HELP                      "help/dialogs/help.html"
#define GIMP_HELP_HELP_CONTEXT              "help/context_help.html"


#endif /* __GIMP_HELP_IDS_H__ */
