/* LIGMA - The GNU Image Manipulation Program
 * Copyright (C) 1995 Spencer Kimball and Peter Mattis
 *
 * ligmahelp-ids.h
 * Copyright (C) 2003 Michael Natterer <mitch@ligma.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef __LIGMA_HELP_IDS_H__
#define __LIGMA_HELP_IDS_H__


#define LIGMA_HELP_MAIN                            "ligma-main"

#define LIGMA_HELP_FILE_NEW                        "ligma-file-new"
#define LIGMA_HELP_FILE_OPEN                       "ligma-file-open"
#define LIGMA_HELP_FILE_OPEN_AS_LAYER              "ligma-file-open-as-layer"
#define LIGMA_HELP_FILE_OPEN_LOCATION              "ligma-file-open-location"
#define LIGMA_HELP_FILE_OPEN_BY_EXTENSION          "ligma-file-open-by-extension"
#define LIGMA_HELP_FILE_OPEN_RECENT                "ligma-file-open-recent"
#define LIGMA_HELP_FILE_SAVE                       "ligma-file-save"
#define LIGMA_HELP_FILE_SAVE_AS                    "ligma-file-save-as"
#define LIGMA_HELP_FILE_SAVE_A_COPY                "ligma-file-save-a-copy"
#define LIGMA_HELP_FILE_SAVE_BY_EXTENSION          "ligma-file-save-by-extension"
#define LIGMA_HELP_FILE_EXPORT                     "ligma-file-export"
#define LIGMA_HELP_FILE_EXPORT_AS                  "ligma-file-export-as"
#define LIGMA_HELP_FILE_OVERWRITE                  "ligma-file-overwrite"
#define LIGMA_HELP_FILE_REVERT                     "ligma-file-revert"
#define LIGMA_HELP_FILE_CLOSE                      "ligma-file-close"
#define LIGMA_HELP_FILE_CLOSE_ALL                  "ligma-file-close-all"
#define LIGMA_HELP_FILE_COPY_LOCATION              "ligma-file-copy-location"
#define LIGMA_HELP_FILE_SHOW_IN_FILE_MANAGER       "ligma-file-show-in-file-manager"
#define LIGMA_HELP_FILE_CREATE_TEMPLATE            "ligma-file-create-template"
#define LIGMA_HELP_FILE_QUIT                       "ligma-file-quit"

#define LIGMA_HELP_EDIT_UNDO                       "ligma-edit-undo"
#define LIGMA_HELP_EDIT_REDO                       "ligma-edit-redo"
#define LIGMA_HELP_EDIT_STRONG_UNDO                "ligma-edit-strong-undo"
#define LIGMA_HELP_EDIT_STRONG_REDO                "ligma-edit-strong-redo"
#define LIGMA_HELP_EDIT_UNDO_CLEAR                 "ligma-edit-undo-clear"
#define LIGMA_HELP_EDIT_CUT                        "ligma-edit-cut"
#define LIGMA_HELP_EDIT_COPY                       "ligma-edit-copy"
#define LIGMA_HELP_EDIT_COPY_VISIBLE               "ligma-edit-copy-visible"
#define LIGMA_HELP_EDIT_PASTE                      "ligma-edit-paste"
#define LIGMA_HELP_EDIT_PASTE_IN_PLACE             "ligma-edit-paste-in-place"
#define LIGMA_HELP_EDIT_PASTE_INTO                 "ligma-edit-paste-into"
#define LIGMA_HELP_EDIT_PASTE_INTO_IN_PLACE        "ligma-edit-paste-into-in-place"
#define LIGMA_HELP_EDIT_PASTE_AS_NEW_LAYER         "ligma-edit-paste-as-new-layer"
#define LIGMA_HELP_EDIT_PASTE_AS_NEW_LAYER_IN_PLACE "ligma-edit-paste-as-new-layer-in-place"
#define LIGMA_HELP_EDIT_PASTE_AS_NEW_IMAGE         "ligma-edit-paste-as-new-image"
#define LIGMA_HELP_EDIT_CLEAR                      "ligma-edit-clear"
#define LIGMA_HELP_EDIT_FILL_FG                    "ligma-edit-fill-fg"
#define LIGMA_HELP_EDIT_FILL_BG                    "ligma-edit-fill-bg"
#define LIGMA_HELP_EDIT_FILL_PATTERN               "ligma-edit-fill-pattern"

#define LIGMA_HELP_SELECTION_DIALOG                "ligma-selection-dialog"
#define LIGMA_HELP_SELECTION_ALL                   "ligma-selection-all"
#define LIGMA_HELP_SELECTION_NONE                  "ligma-selection-none"
#define LIGMA_HELP_SELECTION_INVERT                "ligma-selection-invert"
#define LIGMA_HELP_SELECTION_FLOAT                 "ligma-selection-float"
#define LIGMA_HELP_SELECTION_FEATHER               "ligma-selection-feather"
#define LIGMA_HELP_SELECTION_SHARPEN               "ligma-selection-sharpen"
#define LIGMA_HELP_SELECTION_SHRINK                "ligma-selection-shrink"
#define LIGMA_HELP_SELECTION_GROW                  "ligma-selection-grow"
#define LIGMA_HELP_SELECTION_BORDER                "ligma-selection-border"
#define LIGMA_HELP_SELECTION_FLOOD                 "ligma-selection-flood"
#define LIGMA_HELP_SELECTION_FILL                  "ligma-selection-fill"
#define LIGMA_HELP_SELECTION_STROKE                "ligma-selection-stroke"
#define LIGMA_HELP_SELECTION_TO_CHANNEL            "ligma-selection-to-channel"
#define LIGMA_HELP_SELECTION_TO_PATH               "ligma-selection-to-path"

#define LIGMA_HELP_VIEW_NEW                        "ligma-view-new"
#define LIGMA_HELP_VIEW_SHOW_ALL                   "ligma-view-show-all"
#define LIGMA_HELP_VIEW_DOT_FOR_DOT                "ligma-view-dot-for-dot"
#define LIGMA_HELP_VIEW_RESET                      "ligma-view-reset"
#define LIGMA_HELP_VIEW_SCROLL_CENTER              "ligma-view-scroll-center"
#define LIGMA_HELP_VIEW_ZOOM_REVERT                "ligma-view-zoom-revert"
#define LIGMA_HELP_VIEW_ZOOM_OUT                   "ligma-view-zoom-out"
#define LIGMA_HELP_VIEW_ZOOM_IN                    "ligma-view-zoom-in"
#define LIGMA_HELP_VIEW_ZOOM_100                   "ligma-view-zoom-100"
#define LIGMA_HELP_VIEW_ZOOM_FIT_IN                "ligma-view-zoom-fit-in"
#define LIGMA_HELP_VIEW_ZOOM_FILL                  "ligma-view-zoom-fill"
#define LIGMA_HELP_VIEW_ZOOM_SELECTION             "ligma-view-zoom-selection"
#define LIGMA_HELP_VIEW_ZOOM_OTHER                 "ligma-view-zoom-other"
#define LIGMA_HELP_VIEW_FLIP                       "ligma-view-flip"
#define LIGMA_HELP_VIEW_FLIP_RESET                 "ligma-view-flip-reset"
#define LIGMA_HELP_VIEW_ROTATE_RESET               "ligma-view-rotate-reset"
#define LIGMA_HELP_VIEW_ROTATE_15                  "ligma-view-rotate-15"
#define LIGMA_HELP_VIEW_ROTATE_90                  "ligma-view-rotate-90"
#define LIGMA_HELP_VIEW_ROTATE_180                 "ligma-view-rotate-180"
#define LIGMA_HELP_VIEW_ROTATE_270                 "ligma-view-rotate-270"
#define LIGMA_HELP_VIEW_ROTATE_345                 "ligma-view-rotate-345"
#define LIGMA_HELP_VIEW_ROTATE_OTHER               "ligma-view-rotate-other"
#define LIGMA_HELP_VIEW_COLOR_MANAGEMENT           "ligma-view-color-management"
#define LIGMA_HELP_VIEW_SHOW_SELECTION             "ligma-view-show-selection"
#define LIGMA_HELP_VIEW_SHOW_LAYER_BOUNDARY        "ligma-view-show-layer-boundary"
#define LIGMA_HELP_VIEW_SHOW_CANVAS_BOUNDARY       "ligma-view-show-canvas-boundary"
#define LIGMA_HELP_VIEW_SHOW_GUIDES                "ligma-view-show-guides"
#define LIGMA_HELP_VIEW_SHOW_GRID                  "ligma-view-show-grid"
#define LIGMA_HELP_VIEW_SHOW_SAMPLE_POINTS         "ligma-view-show-sample-points"
#define LIGMA_HELP_VIEW_SNAP_TO_GUIDES             "ligma-view-snap-to-guides"
#define LIGMA_HELP_VIEW_SNAP_TO_GRID               "ligma-view-snap-to-grid"
#define LIGMA_HELP_VIEW_SNAP_TO_CANVAS             "ligma-view-snap-to-canvas"
#define LIGMA_HELP_VIEW_SNAP_TO_VECTORS            "ligma-view-snap-to-vectors"
#define LIGMA_HELP_VIEW_SHOW_MENUBAR               "ligma-view-show-menubar"
#define LIGMA_HELP_VIEW_SHOW_RULERS                "ligma-view-show-rulers"
#define LIGMA_HELP_VIEW_SHOW_SCROLLBARS            "ligma-view-show-scrollbars"
#define LIGMA_HELP_VIEW_SHOW_STATUSBAR             "ligma-view-show-statusbar"
#define LIGMA_HELP_VIEW_PADDING_COLOR              "ligma-view-padding-color"
#define LIGMA_HELP_VIEW_SHRINK_WRAP                "ligma-view-shrink-wrap"
#define LIGMA_HELP_VIEW_FULLSCREEN                 "ligma-view-fullscreen"
#define LIGMA_HELP_VIEW_CHANGE_SCREEN              "ligma-view-change-screen"

#define LIGMA_HELP_IMAGE_WINDOW                    "ligma-image-window"
#define LIGMA_HELP_IMAGE_WINDOW_ORIGIN             "ligma-image-window-origin"
#define LIGMA_HELP_IMAGE_WINDOW_ZOOM_FOLLOW_BUTTON "ligma-image-window-zoom-follow-button"
#define LIGMA_HELP_IMAGE_WINDOW_QUICK_MASK_BUTTON  "ligma-image-window-quick-mask-button"
#define LIGMA_HELP_IMAGE_WINDOW_NAV_BUTTON         "ligma-image-window-nav-button"
#define LIGMA_HELP_IMAGE_WINDOW_RULER              "ligma-image-window-ruler"
#define LIGMA_HELP_IMAGE_WINDOW_STATUS_BAR         "ligma-image-window-status-bar"


#define LIGMA_HELP_IMAGE_DIALOG                    "ligma-image-dialog"
#define LIGMA_HELP_IMAGE_DUPLICATE                 "ligma-image-duplicate"
#define LIGMA_HELP_IMAGE_CONVERT_RGB               "ligma-image-convert-rgb"
#define LIGMA_HELP_IMAGE_CONVERT_GRAYSCALE         "ligma-image-convert-grayscale"
#define LIGMA_HELP_IMAGE_CONVERT_INDEXED           "ligma-image-convert-indexed"
#define LIGMA_HELP_IMAGE_CONVERT_U8                "ligma-image-convert-u8"
#define LIGMA_HELP_IMAGE_CONVERT_U16               "ligma-image-convert-u16"
#define LIGMA_HELP_IMAGE_CONVERT_U32               "ligma-image-convert-u32"
#define LIGMA_HELP_IMAGE_CONVERT_HALF              "ligma-image-convert-half"
#define LIGMA_HELP_IMAGE_CONVERT_FLOAT             "ligma-image-convert-float"
#define LIGMA_HELP_IMAGE_CONVERT_DOUBLE            "ligma-image-convert-double"
#define LIGMA_HELP_IMAGE_CONVERT_GAMMA             "ligma-image-convert-gamma"
#define LIGMA_HELP_IMAGE_CONVERT_PRECISION         "ligma-image-convert-precision"
#define LIGMA_HELP_IMAGE_FLIP_HORIZONTAL           "ligma-image-flip-horizontal"
#define LIGMA_HELP_IMAGE_FLIP_VERTICAL             "ligma-image-flip-vertical"
#define LIGMA_HELP_IMAGE_ROTATE_90                 "ligma-image-rotate-90"
#define LIGMA_HELP_IMAGE_ROTATE_180                "ligma-image-rotate-180"
#define LIGMA_HELP_IMAGE_ROTATE_270                "ligma-image-rotate-270"
#define LIGMA_HELP_IMAGE_RESIZE                    "ligma-image-resize"
#define LIGMA_HELP_IMAGE_RESIZE_TO_LAYERS          "ligma-image-resize-to-layers"
#define LIGMA_HELP_IMAGE_RESIZE_TO_SELECTION       "ligma-image-resize-to-selection"
#define LIGMA_HELP_IMAGE_PRINT_SIZE                "ligma-image-print-size"
#define LIGMA_HELP_IMAGE_SCALE                     "ligma-image-scale"
#define LIGMA_HELP_IMAGE_SCALE_WARNING             "ligma-image-scale-warning"
#define LIGMA_HELP_IMAGE_CROP                      "ligma-image-crop"
#define LIGMA_HELP_IMAGE_MERGE_LAYERS              "ligma-image-merge-layers"
#define LIGMA_HELP_IMAGE_FLATTEN                   "ligma-image-flatten"
#define LIGMA_HELP_IMAGE_COLOR_PROFILE_ASSIGN      "ligma-image-color-profile-assign"
#define LIGMA_HELP_IMAGE_COLOR_PROFILE_CONVERT     "ligma-image-color-profile-convert"
#define LIGMA_HELP_IMAGE_COLOR_PROFILE_DISCARD     "ligma-image-color-profile-discard"
#define LIGMA_HELP_IMAGE_COLOR_PROFILE_USE_SRGB    "ligma-image-color-profile-use-srgb"
#define LIGMA_HELP_IMAGE_COLOR_PROFILE_SAVE        "ligma-image-color-profile-save"
#define LIGMA_HELP_IMAGE_COLOR_PROFILE_IMPORT      "ligma-image-color-profile-import"
#define LIGMA_HELP_IMAGE_GRID                      "ligma-image-grid"
#define LIGMA_HELP_IMAGE_PROPERTIES                "ligma-image-properties"

#define LIGMA_HELP_LAYER_DIALOG                    "ligma-layer-dialog"
#define LIGMA_HELP_LAYER_DIALOG_PAINT_MODE_MENU    "ligma-layer-dialog-paint-mode-menu"
#define LIGMA_HELP_LAYER_DIALOG_OPACITY_SCALE      "ligma-layer-dialog-opacity-scale"

#define LIGMA_HELP_LAYER_NEW                       "ligma-layer-new"
#define LIGMA_HELP_LAYER_NEW_FROM_VISIBLE          "ligma-layer-new-from-visible"
#define LIGMA_HELP_LAYER_DUPLICATE                 "ligma-layer-duplicate"
#define LIGMA_HELP_LAYER_ANCHOR                    "ligma-layer-anchor"
#define LIGMA_HELP_LAYER_MERGE_DOWN                "ligma-layer-merge-down"
#define LIGMA_HELP_LAYER_MERGE_GROUP               "ligma-layer-merge-group"
#define LIGMA_HELP_LAYER_DELETE                    "ligma-layer-delete"
#define LIGMA_HELP_LAYER_TEXT_DISCARD              "ligma-layer-text-discard"
#define LIGMA_HELP_LAYER_TEXT_TO_PATH              "ligma-layer-text-to-path"
#define LIGMA_HELP_LAYER_TEXT_ALONG_PATH           "ligma-layer-text-along-path"
#define LIGMA_HELP_LAYER_PREVIOUS                  "ligma-layer-previous"
#define LIGMA_HELP_LAYER_NEXT                      "ligma-layer-next"
#define LIGMA_HELP_LAYER_TOP                       "ligma-layer-top"
#define LIGMA_HELP_LAYER_BOTTOM                    "ligma-layer-bottom"
#define LIGMA_HELP_LAYER_RAISE                     "ligma-layer-raise"
#define LIGMA_HELP_LAYER_RAISE_TO_TOP              "ligma-layer-raise-to-top"
#define LIGMA_HELP_LAYER_LOWER                     "ligma-layer-lower"
#define LIGMA_HELP_LAYER_LOWER_TO_BOTTOM           "ligma-layer-lower-to-bottom"
#define LIGMA_HELP_LAYER_WHITE_BALANCE             "ligma-layer-white-balance"
#define LIGMA_HELP_LAYER_EQUALIZE                  "ligma-layer-equalize"
#define LIGMA_HELP_LAYER_VISIBLE                   "ligma-layer-visible"
#define LIGMA_HELP_LAYER_LINKED                    "ligma-layer-linked"
#define LIGMA_HELP_LAYER_COLOR_TAG                 "ligma-layer-color-tag"
#define LIGMA_HELP_LAYER_OPACITY                   "ligma-layer-opacity"
#define LIGMA_HELP_LAYER_MODE                      "ligma-layer-mode"
#define LIGMA_HELP_LAYER_LOCK_ALPHA                "ligma-layer-lock-alpha"
#define LIGMA_HELP_LAYER_LOCK_PIXELS               "ligma-layer-lock-pixels"
#define LIGMA_HELP_LAYER_LOCK_POSITION             "ligma-layer-lock-position"
#define LIGMA_HELP_LAYER_LOCK_VISIBILITY           "ligma-layer-lock-visibility"
#define LIGMA_HELP_LAYER_MASK_ADD                  "ligma-layer-mask-add"
#define LIGMA_HELP_LAYER_MASK_APPLY                "ligma-layer-mask-apply"
#define LIGMA_HELP_LAYER_MASK_DELETE               "ligma-layer-mask-delete"
#define LIGMA_HELP_LAYER_MASK_EDIT                 "ligma-layer-mask-edit"
#define LIGMA_HELP_LAYER_MASK_SHOW                 "ligma-layer-mask-show"
#define LIGMA_HELP_LAYER_MASK_DISABLE              "ligma-layer-mask-disable"
#define LIGMA_HELP_LAYER_MASK_SELECTION_REPLACE    "ligma-layer-mask-selection-replace"
#define LIGMA_HELP_LAYER_MASK_SELECTION_ADD        "ligma-layer-mask-selection-add"
#define LIGMA_HELP_LAYER_MASK_SELECTION_SUBTRACT   "ligma-layer-mask-selection-subtract"
#define LIGMA_HELP_LAYER_MASK_SELECTION_INTERSECT  "ligma-layer-mask-selection-intersect"
#define LIGMA_HELP_LAYER_ALPHA_ADD                 "ligma-layer-alpha-add"
#define LIGMA_HELP_LAYER_ALPHA_REMOVE              "ligma-layer-alpha-remove"
#define LIGMA_HELP_LAYER_ALPHA_SELECTION_REPLACE   "ligma-layer-alpha-selection-replace"
#define LIGMA_HELP_LAYER_ALPHA_SELECTION_ADD       "ligma-layer-alpha-selection-add"
#define LIGMA_HELP_LAYER_ALPHA_SELECTION_SUBTRACT  "ligma-layer-alpha-selection-subtract"
#define LIGMA_HELP_LAYER_ALPHA_SELECTION_INTERSECT "ligma-layer-alpha-selection-intersect"
#define LIGMA_HELP_LAYER_FLIP_HORIZONTAL           "ligma-layer-flip-horizontal"
#define LIGMA_HELP_LAYER_FLIP_VERTICAL             "ligma-layer-flip-vertical"
#define LIGMA_HELP_LAYER_ROTATE_90                 "ligma-layer-rotate-90"
#define LIGMA_HELP_LAYER_ROTATE_180                "ligma-layer-rotate-180"
#define LIGMA_HELP_LAYER_ROTATE_270                "ligma-layer-rotate-270"
#define LIGMA_HELP_LAYER_RESIZE                    "ligma-layer-resize"
#define LIGMA_HELP_LAYER_RESIZE_TO_IMAGE           "ligma-layer-resize-to-image"
#define LIGMA_HELP_LAYER_SCALE                     "ligma-layer-scale"
#define LIGMA_HELP_LAYER_CROP                      "ligma-layer-crop"
#define LIGMA_HELP_LAYER_EDIT                      "ligma-layer-edit"

#define LIGMA_HELP_CHANNEL_DIALOG                  "ligma-channel-dialog"
#define LIGMA_HELP_CHANNEL_NEW                     "ligma-channel-new"
#define LIGMA_HELP_CHANNEL_RAISE                   "ligma-channel-raise"
#define LIGMA_HELP_CHANNEL_RAISE_TO_TOP            "ligma-channel-raise-to-top"
#define LIGMA_HELP_CHANNEL_LOWER                   "ligma-channel-lower"
#define LIGMA_HELP_CHANNEL_LOWER_TO_BOTTOM         "ligma-channel-lower-to-bottom"
#define LIGMA_HELP_CHANNEL_DUPLICATE               "ligma-channel-duplicate"
#define LIGMA_HELP_CHANNEL_DELETE                  "ligma-channel-delete"
#define LIGMA_HELP_CHANNEL_PREVIOUS                "ligma-channel-previous"
#define LIGMA_HELP_CHANNEL_NEXT                    "ligma-channel-next"
#define LIGMA_HELP_CHANNEL_TOP                     "ligma-channel-top"
#define LIGMA_HELP_CHANNEL_BOTTOM                  "ligma-channel-bottom"
#define LIGMA_HELP_CHANNEL_VISIBLE                 "ligma-channel-visible"
#define LIGMA_HELP_CHANNEL_LINKED                  "ligma-channel-linked"
#define LIGMA_HELP_CHANNEL_COLOR_TAG               "ligma-channel-color-tag"
#define LIGMA_HELP_CHANNEL_LOCK_PIXELS             "ligma-channel-lock-pixels"
#define LIGMA_HELP_CHANNEL_LOCK_POSITION           "ligma-channel-lock-position"
#define LIGMA_HELP_CHANNEL_LOCK_VISIBILITY         "ligma-channel-lock-visibility"
#define LIGMA_HELP_CHANNEL_SELECTION_REPLACE       "ligma-channel-selection-replace"
#define LIGMA_HELP_CHANNEL_SELECTION_ADD           "ligma-channel-selection-add"
#define LIGMA_HELP_CHANNEL_SELECTION_SUBTRACT      "ligma-channel-selection-subtract"
#define LIGMA_HELP_CHANNEL_SELECTION_INTERSECT     "ligma-channel-selection-intersect"
#define LIGMA_HELP_CHANNEL_EDIT                    "ligma-channel-edit"

#define LIGMA_HELP_QUICK_MASK                      "ligma-quick-mask"
#define LIGMA_HELP_QUICK_MASK_TOGGLE               "ligma-quick-mask-toggle"
#define LIGMA_HELP_QUICK_MASK_INVERT               "ligma-quick-mask-invert"
#define LIGMA_HELP_QUICK_MASK_EDIT                 "ligma-quick-mask-edit"

#define LIGMA_HELP_PATH_DIALOG                     "ligma-path-dialog"
#define LIGMA_HELP_PATH_NEW                        "ligma-path-new"
#define LIGMA_HELP_PATH_PREVIOUS                   "ligma-path-previous"
#define LIGMA_HELP_PATH_NEXT                       "ligma-path-next"
#define LIGMA_HELP_PATH_TOP                        "ligma-path-top"
#define LIGMA_HELP_PATH_BOTTOM                     "ligma-path-bottom"
#define LIGMA_HELP_PATH_RAISE                      "ligma-path-raise"
#define LIGMA_HELP_PATH_RAISE_TO_TOP               "ligma-path-raise-to-top"
#define LIGMA_HELP_PATH_LOWER                      "ligma-path-lower"
#define LIGMA_HELP_PATH_LOWER_TO_BOTTOM            "ligma-path-lower-to-bottom"
#define LIGMA_HELP_PATH_DUPLICATE                  "ligma-path-duplicate"
#define LIGMA_HELP_PATH_DELETE                     "ligma-path-delete"
#define LIGMA_HELP_PATH_MERGE_VISIBLE              "ligma-path-merge-visible"
#define LIGMA_HELP_PATH_VISIBLE                    "ligma-path-visible"
#define LIGMA_HELP_PATH_LINKED                     "ligma-path-linked"
#define LIGMA_HELP_PATH_COLOR_TAG                  "ligma-path-color-tag"
#define LIGMA_HELP_PATH_LOCK_STROKES               "ligma-path-lock-strokes"
#define LIGMA_HELP_PATH_LOCK_POSITION              "ligma-path-lock-position"
#define LIGMA_HELP_PATH_SELECTION_REPLACE          "ligma-path-selection-replace"
#define LIGMA_HELP_PATH_SELECTION_ADD              "ligma-path-selection-add"
#define LIGMA_HELP_PATH_SELECTION_SUBTRACT         "ligma-path-selection-subtract"
#define LIGMA_HELP_PATH_SELECTION_INTERSECT        "ligma-path-selection-intersect"
#define LIGMA_HELP_PATH_FILL                       "ligma-path-fill"
#define LIGMA_HELP_PATH_STROKE                     "ligma-path-stroke"
#define LIGMA_HELP_PATH_COPY                       "ligma-path-copy"
#define LIGMA_HELP_PATH_PASTE                      "ligma-path-paste"
#define LIGMA_HELP_PATH_IMPORT                     "ligma-path-import"
#define LIGMA_HELP_PATH_EXPORT                     "ligma-path-export"
#define LIGMA_HELP_PATH_EDIT                       "ligma-path-edit"

#define LIGMA_HELP_TOOL_AIRBRUSH                   "ligma-tool-airbrush"
#define LIGMA_HELP_TOOL_ALIGN                      "ligma-tool-align"
#define LIGMA_HELP_TOOL_BRIGHTNESS_CONTRAST        "ligma-tool-brightness-contrast"
#define LIGMA_HELP_TOOL_BUCKET_FILL                "ligma-tool-bucket-fill"
#define LIGMA_HELP_TOOL_BY_COLOR_SELECT            "ligma-tool-by-color-select"
#define LIGMA_HELP_TOOL_CAGE                       "ligma-tool-cage"
#define LIGMA_HELP_TOOL_CLONE                      "ligma-tool-clone"
#define LIGMA_HELP_TOOL_COLORIZE                   "ligma-tool-colorize"
#define LIGMA_HELP_TOOL_COLOR_BALANCE              "ligma-tool-color-balance"
#define LIGMA_HELP_TOOL_COLOR_PICKER               "ligma-tool-color-picker"
#define LIGMA_HELP_TOOL_CONVOLVE                   "ligma-tool-convolve"
#define LIGMA_HELP_TOOL_CROP                       "ligma-tool-crop"
#define LIGMA_HELP_TOOL_CURVES                     "ligma-tool-curves"
#define LIGMA_HELP_TOOL_DODGE_BURN                 "ligma-tool-dodge-burn"
#define LIGMA_HELP_TOOL_ELLIPSE_SELECT             "ligma-tool-ellipse-select"
#define LIGMA_HELP_TOOL_ERASER                     "ligma-tool-eraser"
#define LIGMA_HELP_TOOL_FLIP                       "ligma-tool-flip"
#define LIGMA_HELP_TOOL_FREE_SELECT                "ligma-tool-free-select"
#define LIGMA_HELP_TOOL_FOREGROUND_SELECT          "ligma-tool-foreground-select"
#define LIGMA_HELP_TOOL_FUZZY_SELECT               "ligma-tool-fuzzy-select"
#define LIGMA_HELP_TOOL_GEGL                       "ligma-tool-gegl"
#define LIGMA_HELP_TOOL_GRADIENT                   "ligma-tool-gradient"
#define LIGMA_HELP_TOOL_HANDLE_TRANSFORM           "ligma-tool-handle-transform"
#define LIGMA_HELP_TOOL_HEAL                       "ligma-tool-heal"
#define LIGMA_HELP_TOOL_HUE_SATURATION             "ligma-tool-hue-saturation"
#define LIGMA_HELP_TOOL_INK                        "ligma-tool-ink"
#define LIGMA_HELP_TOOL_ISCISSORS                  "ligma-tool-iscissors"
#define LIGMA_HELP_TOOL_LEVELS                     "ligma-tool-levels"
#define LIGMA_HELP_TOOL_MEASURE                    "ligma-tool-measure"
#define LIGMA_HELP_TOOL_MOVE                       "ligma-tool-move"
#define LIGMA_HELP_TOOL_MYPAINT_BRUSH              "ligma-tool-mypaint-brush"
#define LIGMA_HELP_TOOL_N_POINT_DEFORMATION        "ligma-tool-n-point-deformation"
#define LIGMA_HELP_TOOL_OFFSET                     "ligma-tool-offset"
#define LIGMA_HELP_TOOL_PATH                       "ligma-tool-path"
#define LIGMA_HELP_TOOL_PAINTBRUSH                 "ligma-tool-paintbrush"
#define LIGMA_HELP_TOOL_PENCIL                     "ligma-tool-pencil"
#define LIGMA_HELP_TOOL_PERSPECTIVE                "ligma-tool-perspective"
#define LIGMA_HELP_TOOL_PERSPECTIVE_CLONE          "ligma-tool-perspective-clone"
#define LIGMA_HELP_TOOL_RECT_SELECT                "ligma-tool-rect-select"
#define LIGMA_HELP_TOOL_ROTATE                     "ligma-tool-rotate"
#define LIGMA_HELP_TOOL_SCALE                      "ligma-tool-scale"
#define LIGMA_HELP_TOOL_SEAMLESS_CLONE             "ligma-tool-seamless-clone"
#define LIGMA_HELP_TOOL_SHEAR                      "ligma-tool-shear"
#define LIGMA_HELP_TOOL_SMUDGE                     "ligma-tool-smudge"
#define LIGMA_HELP_TOOL_TEXT                       "ligma-tool-text"
#define LIGMA_HELP_TOOL_THRESHOLD                  "ligma-tool-threshold"
#define LIGMA_HELP_TOOL_TRANSFORM_3D               "ligma-tool-transform-3d"
#define LIGMA_HELP_TOOL_UNIFIED_TRANSFORM          "ligma-tool-unified-transform"
#define LIGMA_HELP_TOOL_VECTORS                    "ligma-tool-vectors"
#define LIGMA_HELP_TOOL_WARP                       "ligma-tool-warp"
#define LIGMA_HELP_TOOL_ZOOM                       "ligma-tool-zoom"

#define LIGMA_HELP_FILTER_REPEAT                   "ligma-filter-repeat"
#define LIGMA_HELP_FILTER_RESHOW                   "ligma-filter-reshow"
#define LIGMA_HELP_FILTER_RESET_ALL                "ligma-filter-reset-all"

#define LIGMA_HELP_FILTER_ALIEN_MAP                "ligma-filter-alien-map"
#define LIGMA_HELP_FILTER_ANTIALIAS                "ligma-filter-antialias"
#define LIGMA_HELP_FILTER_APPLY_CANVAS             "ligma-filter-apply-canvas"
#define LIGMA_HELP_FILTER_APPLY_LENS               "ligma-filter-apply-lens"
#define LIGMA_HELP_FILTER_BAYER_MATRIX             "ligma-filter-bayer-matrix"
#define LIGMA_HELP_FILTER_BLOOM                    "ligma-filter-bloom"
#define LIGMA_HELP_FILTER_BUMP_MAP                 "ligma-filter-bump-map"
#define LIGMA_HELP_FILTER_C2G                      "ligma-filter-c2g"
#define LIGMA_HELP_FILTER_CARTOON                  "ligma-filter-cartoon"
#define LIGMA_HELP_FILTER_CHANNEL_MIXER            "ligma-filter-channel-mixer"
#define LIGMA_HELP_FILTER_CHECKERBOARD             "ligma-filter-checkerboard"
#define LIGMA_HELP_FILTER_COLOR_ENHANCE            "ligma-filter-color-enhance"
#define LIGMA_HELP_FILTER_COLOR_EXCHANGE           "ligma-filter-color-exchange"
#define LIGMA_HELP_FILTER_COLOR_ROTATE             "ligma-filter-color-rotate"
#define LIGMA_HELP_FILTER_COLOR_TEMPERATURE        "ligma-filter-color-temperature"
#define LIGMA_HELP_FILTER_COLOR_TO_ALPHA           "ligma-filter-color-to-alpha"
#define LIGMA_HELP_FILTER_COMPONENT_EXTRACT        "ligma-filter-component-extract"
#define LIGMA_HELP_FILTER_CONVOLUTION_MATRIX       "ligma-filter-convolution-matrix"
#define LIGMA_HELP_FILTER_CUBISM                   "ligma-filter-cubism"
#define LIGMA_HELP_FILTER_DEINTERLACE              "ligma-filter-deinterlace"
#define LIGMA_HELP_FILTER_DESATURATE               "ligma-filter-desaturate"
#define LIGMA_HELP_FILTER_DIFFERENCE_OF_GAUSSIANS  "ligma-filter-difference-of-gaussians"
#define LIGMA_HELP_FILTER_DIFFRACTION_PATTERNS     "ligma-filter-diffraction-patterns"
#define LIGMA_HELP_FILTER_DILATE                   "ligma-filter-dilate"
#define LIGMA_HELP_FILTER_DISPLACE                 "ligma-filter-displace"
#define LIGMA_HELP_FILTER_DISTANCE_MAP             "ligma-filter-distance-map"
#define LIGMA_HELP_FILTER_DITHER                   "ligma-filter-dither"
#define LIGMA_HELP_FILTER_DROPSHADOW               "ligma-filter-dropshadow"
#define LIGMA_HELP_FILTER_EDGE                     "ligma-filter-edge"
#define LIGMA_HELP_FILTER_EDGE_LAPLACE             "ligma-filter-edge-laplace"
#define LIGMA_HELP_FILTER_EDGE_NEON                "ligma-filter-edge-neon"
#define LIGMA_HELP_FILTER_EDGE_SOBEL               "ligma-filter-edge-sobel"
#define LIGMA_HELP_FILTER_EMBOSS                   "ligma-filter-emboss"
#define LIGMA_HELP_FILTER_ENGRAVE                  "ligma-filter-engrave"
#define LIGMA_HELP_FILTER_ERODE                    "ligma-filter-erode"
#define LIGMA_HELP_FILTER_EXPOSURE                 "ligma-filter-exposure"
#define LIGMA_HELP_FILTER_FATTAL_2002              "ligma-filter-fattal-2002"
#define LIGMA_HELP_FILTER_FOCUS_BLUR               "ligma-filter-focus-blur"
#define LIGMA_HELP_FILTER_FRACTAL_TRACE            "ligma-filter-fractal-trace"
#define LIGMA_HELP_FILTER_GAUSSIAN_BLUR            "ligma-filter-gaussian-blur"
#define LIGMA_HELP_FILTER_GAUSSIAN_BLUR_SELECTIVE  "ligma-filter-gaussian-blur-selective"
#define LIGMA_HELP_FILTER_GEGL_GRAPH               "ligma-filter-gegl"
#define LIGMA_HELP_FILTER_GRID                     "ligma-filter-grid"
#define LIGMA_HELP_FILTER_HIGH_PASS                "ligma-filter-high-pass"
#define LIGMA_HELP_FILTER_HUE_CHROMA               "ligma-filter-hue-chroma"
#define LIGMA_HELP_FILTER_ILLUSION                 "ligma-filter-illusion"
#define LIGMA_HELP_FILTER_INVERT_LINEAR            "ligma-filter-invert-linear"
#define LIGMA_HELP_FILTER_INVERT_PERCEPTUAL        "ligma-filter-invert-perceptual"
#define LIGMA_HELP_FILTER_INVERT_VALUE             "ligma-filter-invert-value"
#define LIGMA_HELP_FILTER_IMAGE_GRADIENT           "ligma-filter-image-gradient"
#define LIGMA_HELP_FILTER_KALEIDOSCOPE             "ligma-filter-kaleidoscope"
#define LIGMA_HELP_FILTER_LENS_BLUR                "ligma-filter-lens-blur"
#define LIGMA_HELP_FILTER_LENS_DISTORTION          "ligma-filter-lens-distortion"
#define LIGMA_HELP_FILTER_LENS_FLARE               "ligma-filter-lens-flare"
#define LIGMA_HELP_FILTER_LINEAR_SINUSOID          "ligma-filter-linear-sinusoid"
#define LIGMA_HELP_FILTER_LITTLE_PLANET            "ligma-filter-little-planet"
#define LIGMA_HELP_FILTER_LONG_SHADOW              "ligma-filter-long-shadow"
#define LIGMA_HELP_FILTER_MANTIUK_2006             "ligma-filter-manituk-2006"
#define LIGMA_HELP_FILTER_MAZE                     "ligma-filter-maze"
#define LIGMA_HELP_FILTER_MEAN_CURVATURE_BLUR      "ligma-filter-mean-curvature-blur"
#define LIGMA_HELP_FILTER_MEDIAN_BLUR              "ligma-filter-median-blur"
#define LIGMA_HELP_FILTER_MONO_MIXER               "ligma-filter-mono-mixer"
#define LIGMA_HELP_FILTER_MOSAIC                   "ligma-filter-mosaic"
#define LIGMA_HELP_FILTER_MOTION_BLUR_CIRCULAR     "ligma-filter-motion-blur-circular"
#define LIGMA_HELP_FILTER_MOTION_BLUR_LINEAR       "ligma-filter-motion-blur-linear"
#define LIGMA_HELP_FILTER_MOTION_BLUR_ZOOM         "ligma-filter-motion-blur-zoom"
#define LIGMA_HELP_FILTER_NEWSPRINT                "ligma-filter-newsprint"
#define LIGMA_HELP_FILTER_NOISE_CELL               "ligma-filter-noise-cell"
#define LIGMA_HELP_FILTER_NOISE_CIE_LCH            "ligma-filter-noise-cie-lch"
#define LIGMA_HELP_FILTER_NOISE_HSV                "ligma-filter-noise-hsv"
#define LIGMA_HELP_FILTER_NOISE_HURL               "ligma-filter-noise-hurl"
#define LIGMA_HELP_FILTER_NOISE_PERLIN             "ligma-filter-noise-perlin"
#define LIGMA_HELP_FILTER_NOISE_PICK               "ligma-filter-noise-pick"
#define LIGMA_HELP_FILTER_NOISE_RGB                "ligma-filter-noise-rgb"
#define LIGMA_HELP_FILTER_NOISE_REDUCTION          "ligma-filter-noise-reduction"
#define LIGMA_HELP_FILTER_NOISE_SIMPLEX            "ligma-filter-noise-simplex"
#define LIGMA_HELP_FILTER_NOISE_SLUR               "ligma-filter-noise-slur"
#define LIGMA_HELP_FILTER_NOISE_SOLID              "ligma-filter-noise-solid"
#define LIGMA_HELP_FILTER_NOISE_SPREAD             "ligma-filter-noise-spread"
#define LIGMA_HELP_FILTER_NORMAL_MAP               "ligma-filter-normal-map"
#define LIGMA_HELP_FILTER_OILIFY                   "ligma-filter-oilify"
#define LIGMA_HELP_FILTER_PANORAMA_PROJECTION      "ligma-filter-panorama-projection"
#define LIGMA_HELP_FILTER_PHOTOCOPY                "ligma-filter-photocopy"
#define LIGMA_HELP_FILTER_PIXELIZE                 "ligma-filter-pixelize"
#define LIGMA_HELP_FILTER_PLASMA                   "ligma-filter-plasma"
#define LIGMA_HELP_FILTER_POLAR_COORDINATES        "ligma-filter-polar-coordinates"
#define LIGMA_HELP_FILTER_POSTERIZE                "ligma-filter-posterize"
#define LIGMA_HELP_FILTER_RECURSIVE_TRANSFORM      "ligma-filter-recursive-transform"
#define LIGMA_HELP_FILTER_RED_EYE_REMOVAL          "ligma-filter-red-eye-removal"
#define LIGMA_HELP_FILTER_REINHARD_2005            "ligma-filter-reinhard-2005"
#define LIGMA_HELP_FILTER_RGB_CLIP                 "ligma-filter-rgb-clip"
#define LIGMA_HELP_FILTER_RIPPLE                   "ligma-filter-ripple"
#define LIGMA_HELP_FILTER_SATURATION               "ligma-filter-saturation"
#define LIGMA_HELP_FILTER_SEMI_FLATTEN             "ligma-filter-semi-flatten"
#define LIGMA_HELP_FILTER_SEPIA                    "ligma-filter-sepia"
#define LIGMA_HELP_FILTER_SHADOWS_HIGHLIGHTS       "ligma-filter-shadows-highlights"
#define LIGMA_HELP_FILTER_SHIFT                    "ligma-filter-shift"
#define LIGMA_HELP_FILTER_SINUS                    "ligma-filter-sinus"
#define LIGMA_HELP_FILTER_SLIC                     "ligma-filter-slic"
#define LIGMA_HELP_FILTER_SNN_MEAN                 "ligma-filter-snn-mean"
#define LIGMA_HELP_FILTER_SOFTGLOW                 "ligma-filter-softglow"
#define LIGMA_HELP_FILTER_SPHERIZE                 "ligma-filter-spherize"
#define LIGMA_HELP_FILTER_SPIRAL                   "ligma-filter-spiral"
#define LIGMA_HELP_FILTER_STRETCH_CONTRAST         "ligma-filter-stretch-contrast"
#define LIGMA_HELP_FILTER_STRETCH_CONTRAST_HSV     "ligma-filter-stretch-contrast-hsv"
#define LIGMA_HELP_FILTER_STRESS                   "ligma-filter-stress"
#define LIGMA_HELP_FILTER_SUPERNOVA                "ligma-filter-supernova"
#define LIGMA_HELP_FILTER_THRESHOLD_ALPHA          "ligma-filter-threshold-alpha"
#define LIGMA_HELP_FILTER_TILE_GLASS               "ligma-filter-tile-glass"
#define LIGMA_HELP_FILTER_TILE_PAPER               "ligma-filter-tile-paper"
#define LIGMA_HELP_FILTER_TILE_SEAMLESS            "ligma-filter-tile-seamless"
#define LIGMA_HELP_FILTER_UNSHARP_MASK             "ligma-filter-unsharp-mask"
#define LIGMA_HELP_FILTER_VALUE_PROPAGATE          "ligma-filter-value-propagate"
#define LIGMA_HELP_FILTER_VARIABLE_BLUR            "ligma-filter-variable-blur"
#define LIGMA_HELP_FILTER_VIDEO_DEGRADATION        "ligma-filter-video-degradation"
#define LIGMA_HELP_FILTER_VIGNETTE                 "ligma-filter-vignette"
#define LIGMA_HELP_FILTER_WATERPIXELS              "ligma-filter-waterpixels"
#define LIGMA_HELP_FILTER_WAVES                    "ligma-filter-waves"
#define LIGMA_HELP_FILTER_WHIRL_PINCH              "ligma-filter-whirl-pinch"
#define LIGMA_HELP_FILTER_WIND                     "ligma-filter-wind"

#define LIGMA_HELP_TOOLBOX                         "ligma-toolbox"
#define LIGMA_HELP_TOOLBOX_COLOR_AREA              "ligma-toolbox-color-area"
#define LIGMA_HELP_TOOLBOX_IMAGE_AREA              "ligma-toolbox-image-area"
#define LIGMA_HELP_TOOLBOX_INDICATOR_AREA          "ligma-toolbox-indicator-area"
#define LIGMA_HELP_TOOLBOX_DEFAULT_COLORS          "ligma-toolbox-default-colors"
#define LIGMA_HELP_TOOLBOX_SWAP_COLORS             "ligma-toolbox-swap-colors"

#define LIGMA_HELP_BRUSH_DIALOG                    "ligma-brush-dialog"
#define LIGMA_HELP_BRUSH_EDIT                      "ligma-brush-edit"
#define LIGMA_HELP_BRUSH_OPEN_AS_IMAGE             "ligma-brush-open-as-image"
#define LIGMA_HELP_BRUSH_NEW                       "ligma-brush-new"
#define LIGMA_HELP_BRUSH_DUPLICATE                 "ligma-brush-duplicate"
#define LIGMA_HELP_BRUSH_COPY_LOCATION             "ligma-brush-copy-location"
#define LIGMA_HELP_BRUSH_SHOW_IN_FILE_MANAGER      "ligma-brush-show-in-file-manager"
#define LIGMA_HELP_BRUSH_DELETE                    "ligma-brush-delete"
#define LIGMA_HELP_BRUSH_REFRESH                   "ligma-brush-refresh"

#define LIGMA_HELP_BRUSH_EDITOR_DIALOG             "ligma-brush-editor-dialog"
#define LIGMA_HELP_BRUSH_EDITOR_EDIT_ACTIVE        "ligma-brush-editor-edit-active"

#define LIGMA_HELP_DYNAMICS_EDITOR_DIALOG          "ligma-dynamics-editor-dialog"

#define LIGMA_HELP_TOOL_PRESET_EDITOR_DIALOG       "ligma-tool-preset-editor-dialog"
#define LIGMA_HELP_TOOL_PRESET_EDITOR_EDIT_ACTIVE  "ligma-tool-preset-editor-edit-active"

#define LIGMA_HELP_DYNAMICS_DIALOG                 "ligma-dynamics-dialog"
#define LIGMA_HELP_DYNAMICS_EDIT                   "ligma-dynamics-edit"
#define LIGMA_HELP_DYNAMICS_NEW                    "ligma-dynamics-new"
#define LIGMA_HELP_DYNAMICS_DUPLICATE              "ligma-dynamics-duplicate"
#define LIGMA_HELP_DYNAMICS_COPY_LOCATION          "ligma-dynamics-copy-location"
#define LIGMA_HELP_DYNAMICS_SHOW_IN_FILE_MANAGER   "ligma-dynamics-show-in-file-manager"
#define LIGMA_HELP_DYNAMICS_DELETE                 "ligma-dynamics-delete"
#define LIGMA_HELP_DYNAMICS_REFRESH                "ligma-dynamics-refresh"

#define LIGMA_HELP_MYPAINT_BRUSH_DIALOG            "ligma-mypaint-brush-dialog"
#define LIGMA_HELP_MYPAINT_BRUSH_EDIT              "ligma-mypaint-brush-edit"
#define LIGMA_HELP_MYPAINT_BRUSH_NEW               "ligma-mypaint-brush-new"
#define LIGMA_HELP_MYPAINT_BRUSH_DUPLICATE         "ligma-mypaint-brush-duplicate"
#define LIGMA_HELP_MYPAINT_BRUSH_COPY_LOCATION     "ligma-mypaint-brush-copy-location"
#define LIGMA_HELP_MYPAINT_BRUSH_SHOW_IN_FILE_MANAGER "ligma-mypaint-brush-show-in-file-manager"
#define LIGMA_HELP_MYPAINT_BRUSH_DELETE            "ligma-mypaint-brush-delete"
#define LIGMA_HELP_MYPAINT_BRUSH_REFRESH           "ligma-mypaint-brush-refresh"

#define LIGMA_HELP_PATTERN_DIALOG                  "ligma-pattern-dialog"
#define LIGMA_HELP_PATTERN_EDIT                    "ligma-pattern-edit"
#define LIGMA_HELP_PATTERN_OPEN_AS_IMAGE           "ligma-pattern-open-as-image"
#define LIGMA_HELP_PATTERN_NEW                     "ligma-pattern-new"
#define LIGMA_HELP_PATTERN_DUPLICATE               "ligma-pattern-duplicate"
#define LIGMA_HELP_PATTERN_COPY_LOCATION           "ligma-pattern-copy-location"
#define LIGMA_HELP_PATTERN_SHOW_IN_FILE_MANAGER    "ligma-pattern-show-in-file-manager"
#define LIGMA_HELP_PATTERN_DELETE                  "ligma-pattern-delete"
#define LIGMA_HELP_PATTERN_REFRESH                 "ligma-pattern-refresh"

#define LIGMA_HELP_GRADIENT_DIALOG                 "ligma-gradient-dialog"
#define LIGMA_HELP_GRADIENT_EDIT                   "ligma-gradient-edit"
#define LIGMA_HELP_GRADIENT_NEW                    "ligma-gradient-new"
#define LIGMA_HELP_GRADIENT_DUPLICATE              "ligma-gradient-duplicate"
#define LIGMA_HELP_GRADIENT_COPY_LOCATION          "ligma-gradient-copy-location"
#define LIGMA_HELP_GRADIENT_SHOW_IN_FILE_MANAGER   "ligma-gradient-show-in-file-manager"
#define LIGMA_HELP_GRADIENT_DELETE                 "ligma-gradient-delete"
#define LIGMA_HELP_GRADIENT_REFRESH                "ligma-gradient-refresh"
#define LIGMA_HELP_GRADIENT_SAVE_AS_POV            "ligma-gradient-save-as-pov"

#define LIGMA_HELP_GRADIENT_EDITOR_DIALOG          "ligma-gradient-editor-dialog"
#define LIGMA_HELP_GRADIENT_EDITOR_LEFT_COLOR      "ligma-gradient-editor-left-color"
#define LIGMA_HELP_GRADIENT_EDITOR_LEFT_LOAD       "ligma-gradient-editor-left-load"
#define LIGMA_HELP_GRADIENT_EDITOR_LEFT_SAVE       "ligma-gradient-editor-left-save"
#define LIGMA_HELP_GRADIENT_EDITOR_RIGHT_COLOR     "ligma-gradient-editor-right-color"
#define LIGMA_HELP_GRADIENT_EDITOR_RIGHT_LOAD      "ligma-gradient-editor-right-load"
#define LIGMA_HELP_GRADIENT_EDITOR_RIGHT_SAVE      "ligma-gradient-editor-right-save"
#define LIGMA_HELP_GRADIENT_EDITOR_BLENDING        "ligma-gradient-editor-blending"
#define LIGMA_HELP_GRADIENT_EDITOR_COLORING        "ligma-gradient-editor-coloring"
#define LIGMA_HELP_GRADIENT_EDITOR_FLIP            "ligma-gradient-editor-flip"
#define LIGMA_HELP_GRADIENT_EDITOR_REPLICATE       "ligma-gradient-editor-replicate"
#define LIGMA_HELP_GRADIENT_EDITOR_SPLIT_MIDPOINT  "ligma-gradient-editor-split-midpoint"
#define LIGMA_HELP_GRADIENT_EDITOR_SPLIT_UNIFORM   "ligma-gradient-editor-split-uniform"
#define LIGMA_HELP_GRADIENT_EDITOR_DELETE          "ligma-gradient-editor-delete"
#define LIGMA_HELP_GRADIENT_EDITOR_RECENTER        "ligma-gradient-editor-recenter"
#define LIGMA_HELP_GRADIENT_EDITOR_REDISTRIBUTE    "ligma-gradient-editor-redistribute"
#define LIGMA_HELP_GRADIENT_EDITOR_BLEND_COLOR     "ligma-gradient-editor-blend-color"
#define LIGMA_HELP_GRADIENT_EDITOR_BLEND_OPACITY   "ligma-gradient-editor-blend-opacity"
#define LIGMA_HELP_GRADIENT_EDITOR_ZOOM_OUT        "ligma-gradient-editor-zoom-out"
#define LIGMA_HELP_GRADIENT_EDITOR_ZOOM_IN         "ligma-gradient-editor-zoom-in"
#define LIGMA_HELP_GRADIENT_EDITOR_ZOOM_ALL        "ligma-gradient-editor-zoom-all"
#define LIGMA_HELP_GRADIENT_EDITOR_EDIT_ACTIVE     "ligma-gradient-editor-edit-active"

#define LIGMA_HELP_PALETTE_DIALOG                  "ligma-palette-dialog"
#define LIGMA_HELP_PALETTE_EDIT                    "ligma-palette-edit"
#define LIGMA_HELP_PALETTE_NEW                     "ligma-palette-new"
#define LIGMA_HELP_PALETTE_DUPLICATE               "ligma-palette-duplicate"
#define LIGMA_HELP_PALETTE_COPY_LOCATION           "ligma-palette-copy-location"
#define LIGMA_HELP_PALETTE_SHOW_IN_FILE_MANAGER    "ligma-palette-show-in-file-manager"
#define LIGMA_HELP_PALETTE_DELETE                  "ligma-palette-delete"
#define LIGMA_HELP_PALETTE_REFRESH                 "ligma-palette-refresh"
#define LIGMA_HELP_PALETTE_IMPORT                  "ligma-palette-import"
#define LIGMA_HELP_PALETTE_MERGE                   "ligma-palette-merge"

#define LIGMA_HELP_PALETTE_EDITOR_DIALOG           "ligma-palette-editor-dialog"
#define LIGMA_HELP_PALETTE_EDITOR_NEW              "ligma-palette-editor-new"
#define LIGMA_HELP_PALETTE_EDITOR_EDIT             "ligma-palette-editor-edit"
#define LIGMA_HELP_PALETTE_EDITOR_DELETE           "ligma-palette-editor-delete"
#define LIGMA_HELP_PALETTE_EDITOR_ZOOM_OUT         "ligma-palette-editor-zoom-out"
#define LIGMA_HELP_PALETTE_EDITOR_ZOOM_IN          "ligma-palette-editor-zoom-in"
#define LIGMA_HELP_PALETTE_EDITOR_ZOOM_ALL         "ligma-palette-editor-zoom-all"
#define LIGMA_HELP_PALETTE_EDITOR_EDIT_ACTIVE      "ligma-palette-editor-edit-active"

#define LIGMA_HELP_FONT_DIALOG                     "ligma-font-dialog"
#define LIGMA_HELP_FONT_REFRESH                    "ligma-font-refresh"

#define LIGMA_HELP_BUFFER_DIALOG                   "ligma-buffer-dialog"
#define LIGMA_HELP_BUFFER_CUT                      "ligma-buffer-cut"
#define LIGMA_HELP_BUFFER_COPY                     "ligma-buffer-copy"
#define LIGMA_HELP_BUFFER_PASTE                    "ligma-buffer-paste"
#define LIGMA_HELP_BUFFER_PASTE_IN_PLACE           "ligma-buffer-paste-in-place"
#define LIGMA_HELP_BUFFER_PASTE_INTO               "ligma-buffer-paste-into"
#define LIGMA_HELP_BUFFER_PASTE_INTO_IN_PLACE      "ligma-buffer-paste-into-in-place"
#define LIGMA_HELP_BUFFER_PASTE_AS_NEW_LAYER       "ligma-buffer-paste-as-new-layer"
#define LIGMA_HELP_BUFFER_PASTE_AS_NEW_LAYER_IN_PLACE "ligma-buffer-paste-as-new-layer-in-place"
#define LIGMA_HELP_BUFFER_PASTE_AS_NEW_IMAGE       "ligma-buffer-paste-as-new-image"
#define LIGMA_HELP_BUFFER_DELETE                   "ligma-buffer-delete"

#define LIGMA_HELP_TOOL_PRESET_DIALOG              "ligma-tool-preset-dialog"
#define LIGMA_HELP_TOOL_PRESET_EDIT                "ligma-tool-preset-edit"
#define LIGMA_HELP_TOOL_PRESET_NEW                 "ligma-tool-preset-new"
#define LIGMA_HELP_TOOL_PRESET_DUPLICATE           "ligma-tool-preset-duplicate"
#define LIGMA_HELP_TOOL_PRESET_COPY_LOCATION       "ligma-tool-preset-copy-location"
#define LIGMA_HELP_TOOL_PRESET_SHOW_IN_FILE_MANAGER "ligma-tool-preset-show-in-file-manager"
#define LIGMA_HELP_TOOL_PRESET_SAVE                "ligma-tool-preset-save"
#define LIGMA_HELP_TOOL_PRESET_RESTORE             "ligma-tool-preset-restore"
#define LIGMA_HELP_TOOL_PRESET_DELETE              "ligma-tool-preset-delete"
#define LIGMA_HELP_TOOL_PRESET_REFRESH             "ligma-tool-preset-refresh"

#define LIGMA_HELP_DOCUMENT_CLEAR                  "ligma-document-clear"
#define LIGMA_HELP_DOCUMENT_COPY_LOCATION          "ligma-document-copy-location"
#define LIGMA_HELP_DOCUMENT_SHOW_IN_FILE_MANAGER   "ligma-document-show-in-file-manager"
#define LIGMA_HELP_DOCUMENT_DIALOG                 "ligma-document-dialog"
#define LIGMA_HELP_DOCUMENT_OPEN                   "ligma-document-open"
#define LIGMA_HELP_DOCUMENT_REMOVE                 "ligma-document-remove"
#define LIGMA_HELP_DOCUMENT_REFRESH                "ligma-document-refresh"

#define LIGMA_HELP_TEMPLATE_DIALOG                 "ligma-template-dialog"
#define LIGMA_HELP_TEMPLATE_NEW                    "ligma-template-new"
#define LIGMA_HELP_TEMPLATE_DUPLICATE              "ligma-template-duplicate"
#define LIGMA_HELP_TEMPLATE_EDIT                   "ligma-template-edit"
#define LIGMA_HELP_TEMPLATE_IMAGE_NEW              "ligma-template-image-new"
#define LIGMA_HELP_TEMPLATE_DELETE                 "ligma-template-delete"

#define LIGMA_HELP_TOOL_OPTIONS_DIALOG             "ligma-tool-options-dialog"
#define LIGMA_HELP_TOOL_OPTIONS_SAVE               "ligma-tool-options-save"
#define LIGMA_HELP_TOOL_OPTIONS_RESTORE            "ligma-tool-options-restore"
#define LIGMA_HELP_TOOL_OPTIONS_EDIT               "ligma-tool-options-edit"
#define LIGMA_HELP_TOOL_OPTIONS_DELETE             "ligma-tool-options-delete"
#define LIGMA_HELP_TOOL_OPTIONS_RESET              "ligma-tool-options-reset"

#define LIGMA_HELP_ERRORS_DIALOG                   "ligma-errors-dialog"
#define LIGMA_HELP_ERRORS_HIGHLIGHT                "ligma-errors-highlight"
#define LIGMA_HELP_ERRORS_CLEAR                    "ligma-errors-clear"
#define LIGMA_HELP_ERRORS_SAVE                     "ligma-errors-save"
#define LIGMA_HELP_ERRORS_SELECT_ALL               "ligma-errors-select-all"

#define LIGMA_HELP_PREFS_DIALOG                    "ligma-prefs-dialog"
#define LIGMA_HELP_PREFS_SYSTEM_RESOURCES          "ligma-prefs-system-resources"
#define LIGMA_HELP_PREFS_DEBUGGING                 "ligma-prefs-debugging"
#define LIGMA_HELP_PREFS_COLOR_MANAGEMENT          "ligma-prefs-color-management"
#define LIGMA_HELP_PREFS_IMPORT_EXPORT             "ligma-prefs-import-export"
#define LIGMA_HELP_PREFS_PLAYGROUND                "ligma-prefs-playground"
#define LIGMA_HELP_PREFS_TOOL_OPTIONS              "ligma-prefs-tool-options"
#define LIGMA_HELP_PREFS_NEW_IMAGE                 "ligma-prefs-new-image"
#define LIGMA_HELP_PREFS_DEFAULT_GRID              "ligma-prefs-default-grid"
#define LIGMA_HELP_PREFS_INTERFACE                 "ligma-prefs-interface"
#define LIGMA_HELP_PREFS_THEME                     "ligma-prefs-theme"
#define LIGMA_HELP_PREFS_ICON_THEME                "ligma-prefs-icon-theme"
#define LIGMA_HELP_PREFS_TOOLBOX                   "ligma-prefs-toolbox"
#define LIGMA_HELP_PREFS_DIALOG_DEFAULTS           "ligma-prefs-dialog-defaults"
#define LIGMA_HELP_PREFS_HELP                      "ligma-prefs-help"
#define LIGMA_HELP_PREFS_DISPLAY                   "ligma-prefs-display"
#define LIGMA_HELP_PREFS_WINDOW_MANAGEMENT         "ligma-prefs-window-management"
#define LIGMA_HELP_PREFS_CANVAS_INTERACTION        "ligma-prefs-canvas-interaction"
#define LIGMA_HELP_PREFS_CANVAS_MODIFIERS          "ligma-prefs-canvas-modifiers"
#define LIGMA_HELP_PREFS_IMAGE_WINDOW              "ligma-prefs-image-window"
#define LIGMA_HELP_PREFS_IMAGE_WINDOW_APPEARANCE   "ligma-prefs-image-window-appearance"
#define LIGMA_HELP_PREFS_IMAGE_WINDOW_TITLE        "ligma-prefs-image-window-title"
#define LIGMA_HELP_PREFS_IMAGE_WINDOW_SNAPPING     "ligma-prefs-image-window-snapping"
#define LIGMA_HELP_PREFS_INPUT_DEVICES             "ligma-prefs-input-devices"
#define LIGMA_HELP_PREFS_INPUT_CONTROLLERS         "ligma-prefs-input-controllers"
#define LIGMA_HELP_PREFS_FOLDERS                   "ligma-prefs-folders"
#define LIGMA_HELP_PREFS_FOLDERS_BRUSHES           "ligma-prefs-folders-brushes"
#define LIGMA_HELP_PREFS_FOLDERS_DYNAMICS          "ligma-prefs-folders-dynamics"
#define LIGMA_HELP_PREFS_FOLDERS_PATTERNS          "ligma-prefs-folders-patterns"
#define LIGMA_HELP_PREFS_FOLDERS_PALETTES          "ligma-prefs-folders-palettes"
#define LIGMA_HELP_PREFS_FOLDERS_GRADIENTS         "ligma-prefs-folders-gradients"
#define LIGMA_HELP_PREFS_FOLDERS_FONTS             "ligma-prefs-folders-fonts"
#define LIGMA_HELP_PREFS_FOLDERS_TOOL_PRESETS      "ligma-prefs-folders-tool-presets"
#define LIGMA_HELP_PREFS_FOLDERS_MYPAINT_BRUSHES   "ligma-prefs-folders-mypaint-brushes"
#define LIGMA_HELP_PREFS_FOLDERS_PLUG_INS          "ligma-prefs-folders-plug-ins"
#define LIGMA_HELP_PREFS_FOLDERS_SCRIPTS           "ligma-prefs-folders-scripts"
#define LIGMA_HELP_PREFS_FOLDERS_MODULES           "ligma-prefs-folders-modules"
#define LIGMA_HELP_PREFS_FOLDERS_INTERPRETERS      "ligma-prefs-folders-interpreters"
#define LIGMA_HELP_PREFS_FOLDERS_ENVIRONMENT       "ligma-prefs-folders-environment"
#define LIGMA_HELP_PREFS_FOLDERS_THEMES            "ligma-prefs-folders-themes"
#define LIGMA_HELP_PREFS_FOLDERS_ICON_THEMES       "ligma-prefs-folders-icon-themes"

#define LIGMA_HELP_INPUT_DEVICES                   "ligma-help-input-devices"
#define LIGMA_HELP_KEYBOARD_SHORTCUTS              "ligma-help-keyboard-shortcuts"

#define LIGMA_HELP_INDEXED_PALETTE_DIALOG          "ligma-indexed-palette-dialog"
#define LIGMA_HELP_INDEXED_PALETTE_EDIT            "ligma-indexed-palette-edit"
#define LIGMA_HELP_INDEXED_PALETTE_ADD             "ligma-indexed-palette-add"
#define LIGMA_HELP_INDEXED_PALETTE_SELECTION_REPLACE "ligma-indexed-palette-selection-replace"
#define LIGMA_HELP_INDEXED_PALETTE_SELECTION_ADD   "ligma-indexed-palette-selection-add"
#define LIGMA_HELP_INDEXED_PALETTE_SELECTION_SUBTRACT "ligma-indexed-palette-selection-subtract"
#define LIGMA_HELP_INDEXED_PALETTE_SELECTION_INTERSECT "ligma-indexed-palette-selection-intersect"

#define LIGMA_HELP_POINTER_INFO_DIALOG             "ligma-pointer-info-dialog"
#define LIGMA_HELP_POINTER_INFO_SAMPLE_MERGED      "ligma-pointer-info-sample-merged"

#define LIGMA_HELP_SAMPLE_POINT_DIALOG             "ligma-sample-point-dialog"
#define LIGMA_HELP_SAMPLE_POINT_SAMPLE_MERGED      "ligma-sample-point-sample-merged"

#define LIGMA_HELP_DASHBOARD_DIALOG                "ligma-dashboard-dialog"
#define LIGMA_HELP_DASHBOARD_GROUPS                "ligma-dashboard-groups"
#define LIGMA_HELP_DASHBOARD_UPDATE_INTERVAL       "ligma-dashboard-update-interval"
#define LIGMA_HELP_DASHBOARD_HISTORY_DURATION      "ligma-dashboard-history-duration"
#define LIGMA_HELP_DASHBOARD_LOG_RECORD            "ligma-dashboard-log-record"
#define LIGMA_HELP_DASHBOARD_LOG_ADD_MARKER        "ligma-dashboard-log-add-marker"
#define LIGMA_HELP_DASHBOARD_LOG_ADD_EMPTY_MARKER  "ligma-dashboard-log-add-empty-marker"
#define LIGMA_HELP_DASHBOARD_RESET                 "ligma-dashboard-reset"
#define LIGMA_HELP_DASHBOARD_LOW_SWAP_SPACE_WARNING "ligma-dashboard-low-swap-space-warning"

#define LIGMA_HELP_DOCK                            "ligma-dock"
#define LIGMA_HELP_DOCK_CLOSE                      "ligma-dock-close"
#define LIGMA_HELP_DOCK_IMAGE_MENU                 "ligma-dock-image-menu"
#define LIGMA_HELP_DOCK_AUTO_BUTTON                "ligma-dock-auto-button"
#define LIGMA_HELP_DOCK_CHANGE_SCREEN              "ligma-dock-change-screen"
#define LIGMA_HELP_DOCK_SEPARATOR                  "ligma-dock-separator"

#define LIGMA_HELP_DOCK_TAB_ADD                    "ligma-dock-tab-add"
#define LIGMA_HELP_DOCK_TAB_CLOSE                  "ligma-dock-tab-close"
#define LIGMA_HELP_DOCK_TAB_LOCK                   "ligma-dock-tab-lock"
#define LIGMA_HELP_DOCK_TAB_MENU                   "ligma-dock-tab-menu"
#define LIGMA_HELP_DOCK_TAB_DETACH                 "ligma-dock-tab-detach"
#define LIGMA_HELP_DOCK_PREVIEW_SIZE               "ligma-dock-preview-size"
#define LIGMA_HELP_DOCK_TAB_STYLE                  "ligma-dock-tab-style"
#define LIGMA_HELP_DOCK_VIEW_AS_LIST               "ligma-dock-view-as-list"
#define LIGMA_HELP_DOCK_VIEW_AS_GRID               "ligma-dock-view-as-grid"
#define LIGMA_HELP_DOCK_SHOW_BUTTON_BAR            "ligma-dock-show-button-bar"

#define LIGMA_HELP_ABOUT_DIALOG                    "ligma-about-dialog"
#define LIGMA_HELP_ACTION_SEARCH_DIALOG            "ligma-action-search-dialog"
#define LIGMA_HELP_COLOR_DIALOG                    "ligma-color-dialog"
#define LIGMA_HELP_DEVICE_STATUS_DIALOG            "ligma-device-status-dialog"
#define LIGMA_HELP_DISPLAY_FILTER_DIALOG           "ligma-display-filter-dialog"
#define LIGMA_HELP_HISTOGRAM_DIALOG                "ligma-histogram-dialog"
#define LIGMA_HELP_INFO_DIALOG                     "ligma-info-dialog"
#define LIGMA_HELP_MODULE_DIALOG                   "ligma-module-dialog"
#define LIGMA_HELP_NAVIGATION_DIALOG               "ligma-navigation-dialog"
#define LIGMA_HELP_SYMMETRY_DIALOG                 "ligma-symmetry-dialog"
#define LIGMA_HELP_TEXT_EDITOR_DIALOG              "ligma-text-editor-dialog"
#define LIGMA_HELP_TIPS_DIALOG                     "ligma-tips-dialog"
#define LIGMA_HELP_UNDO_DIALOG                     "ligma-undo-dialog"
#define LIGMA_HELP_WELCOME_DIALOG                  "ligma-welcome-dialog"

#define LIGMA_HELP_EXPORT_DIALOG                   "ligma-export-dialog"
#define LIGMA_HELP_EXPORT_CONFIRM_DIALOG           "ligma-export-confirm-dialog"
#define LIGMA_HELP_UNIT_DIALOG                     "ligma-unit-dialog"

#define LIGMA_HELP_WINDOWS_SHOW_DOCK               "ligma-windows-show-dock"
#define LIGMA_HELP_WINDOWS_HIDE_DOCKS              "ligma-windows-hide-docks"
#define LIGMA_HELP_WINDOWS_SHOW_TABS               "ligma-windows-show-tabs"
#define LIGMA_HELP_WINDOWS_TABS_POSITION           "ligma-windows-tabs-position"
#define LIGMA_HELP_WINDOWS_USE_SINGLE_WINDOW_MODE  "ligma-windows-use-single-window-mode"
#define LIGMA_HELP_WINDOWS_OPEN_RECENT_DOCK        "ligma-windows-open-recent-dock"

#define LIGMA_HELP_HELP                            "ligma-help"
#define LIGMA_HELP_HELP_CONTEXT                    "ligma-help-context"

#define LIGMA_HELP_COLORDISPLAY_COLORBLIND         "ligma-colordisplay-colorblind"
#define LIGMA_HELP_COLORDISPLAY_CONTRAST           "ligma-colordisplay-contrast"
#define LIGMA_HELP_COLORDISPLAY_GAMMA              "ligma-colordisplay-gamma"
#define LIGMA_HELP_COLORDISPLAY_LIGMA               "ligma-colordisplay-ligma"
#define LIGMA_HELP_COLORDISPLAY_PROOF              "ligma-colordisplay-proof"

#define LIGMA_HELP_COLORSELECTOR_CMYK              "ligma-colorselector-cmyk"
#define LIGMA_HELP_COLORSELECTOR_TRIANGLE          "ligma-colorselector-triangle"
#define LIGMA_HELP_COLORSELECTOR_WATER             "ligma-colorselector-water"

#define LIGMA_HELP_CONTROLLER_KEYBOARD             "ligma-controller-keyboard"
#define LIGMA_HELP_CONTROLLER_LINUX_INPUT          "ligma-controller-linux-input"
#define LIGMA_HELP_CONTROLLER_MIDI                 "ligma-controller-midi"
#define LIGMA_HELP_CONTROLLER_MOUSE                "ligma-controller-mouse"
#define LIGMA_HELP_CONTROLLER_WHEEL                "ligma-controller-wheel"

#define LIGMA_HELP_EXTENSIONS_DIALOG               "ligma-extensions-dialog"
#define LIGMA_HELP_EXTENSIONS_INSTALLED            "ligma-extensions-installed"
#define LIGMA_HELP_EXTENSIONS_SYSTEM               "ligma-extensions-system"
#define LIGMA_HELP_EXTENSIONS_INSTALL              "ligma-extensions-install"

#endif /* __LIGMA_HELP_IDS_H__ */
