# LIGMA - The GNU Image Manipulation Program
# Copyright (C) 1998-2003 Manish Singh <yosh@ligma.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

package Ligma::CodeGen::pdb;

%arg_types = (
    int32       => { name            => 'INT32',
		     gtype           => 'G_TYPE_INT',
		     type            => 'gint ',
		     const_type      => 'gint ',
		     init_value      => '0',
		     get_value_func  => '$var = g_value_get_int ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_INT ($value)',
		     set_value_func  => 'g_value_set_int ($value, $var)',
		     take_value_func => 'g_value_set_int ($value, $var)' },

    uchar       => { name            => 'UCHAR',
		     gtype           => 'G_TYPE_UCHAR',
		     type            => 'guchar ',
		     const_type      => 'guchar ',
		     init_value      => '0',
		     get_value_func  => '$var = g_value_get_uchar ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_UVHAR ($value)',
		     set_value_func  => 'g_value_set_uchar ($value, $var)',
		     take_value_func => 'g_value_set_uchar ($value, $var)' },

    float       => { name            => 'FLOAT',
		     gtype           => 'G_TYPE_DOUBLE',
		     type            => 'gdouble ',
		     const_type      => 'gdouble ',
		     init_value      => '0.0',
		     get_value_func  => '$var = g_value_get_double ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_DOUBLE ($value)',
		     set_value_func  => 'g_value_set_double ($value, $var)',
		     take_value_func => 'g_value_set_double ($value, $var)' },

    string      => { name            => 'STRING',
		     gtype           => 'G_TYPE_STRING',
		     type            => 'gchar *',
		     const_type      => 'const gchar *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer full)',
		     get_value_func  => '$var = g_value_get_string ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_STRING ($value)',
		     set_value_func  => 'g_value_set_string ($value, $var)',
		     take_value_func => 'g_value_take_string ($value, $var)' },

    strv        => { name            => 'STRV',
		     gtype           => 'G_TYPE_STRV',
		     type            => 'gchar **',
		     const_type      => 'const gchar **',
		     init_value      => 'NULL',
		     in_annotate     => '(array zero-terminated=1)',
		     out_annotate    => '(array zero-terminated=1) (transfer full)',
		     get_value_func  => '$var = g_value_get_boxed ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_STRV ($value)',
		     set_value_func  => 'g_value_set_boxed ($value, $var)',
		     take_value_func => 'g_value_take_boxed ($value, $var)' },

    int32array  => { name            => 'INT32ARRAY',
		     gtype           => 'LIGMA_TYPE_INT32_ARRAY',
		     type            => 'gint32 *',
		     const_type      => 'const gint32 *',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type gint32)',
		     out_annotate    => '(element-type gint32) (transfer full)',
		     get_value_func  => '$var = ligma_value_get_int32_array ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_INT32_ARRAY ($value)',
		     set_value_func  => 'ligma_value_set_int32_array ($value, $var, $var_len)',
		     take_value_func => 'ligma_value_take_int32_array ($value, $var, $var_len)' },

    int8array   => { name            => 'INT8ARRAY',
		     gtype           => 'LIGMA_TYPE_UINT8_ARRAY',
		     type            => 'guint8 *',
		     const_type      => 'const guint8 *',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type guint8)',
		     out_annotate    => '(element-type guint8) (transfer full)',
		     get_value_func  => '$var = ligma_value_get_uint8_array ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_UINT8_ARRAY ($value)',
		     set_value_func  => 'ligma_value_set_uint8_array ($value, $var, $var_len)',
		     take_value_func => 'ligma_value_take_uint8_array ($value, $var, $var_len)' },

    floatarray  => { name            => 'FLOATARRAY',
		     gtype           => 'LIGMA_TYPE_FLOAT_ARRAY',
		     type            => 'gdouble *',
		     const_type      => 'const gdouble *',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type gdouble)',
		     out_annotate    => '(element-type gdouble) (transfer full)',
		     get_value_func  => '$var = ligma_value_get_float_array ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_FLOAT_ARRAY ($value)',
		     set_value_func  => 'ligma_value_set_float_array ($value, $var, $var_len)',
		     take_value_func => 'ligma_value_take_float_array ($value, $var, $var_len)' },

    colorarray  => { name            => 'COLORARRAY',
		     gtype           => 'LIGMA_TYPE_RGB_ARRAY',
		     type            => 'LigmaRGB *',
		     const_type      => 'const LigmaRGB *',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type LigmaRGB)',
		     out_annotate    => '(element-type LigmaRGB) (transfer full)',
		     get_value_func  => '$var = ligma_value_get_rgb_array ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_RGB_ARRAY ($value)',
		     set_value_func  => 'ligma_value_set_rgb_array ($value, $var, $var_len)',
		     take_value_func => 'ligma_value_take_rgb_array ($value, $var, $var_len)' },

    imagearray  => { name            => 'IMAGEARRAY',
		     gtype           => 'LIGMA_TYPE_OBJECT_ARRAY',
		     type            => 'LigmaImage **',
		     const_type      => 'const LigmaImage **',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type LigmaImage)',
		     out_annotate    => '(element-type LigmaImage) (transfer container)',
		     get_value_func  => '$var = (const LigmaImage **) ligma_value_get_object_array ($value)',
		     dup_value_func  => '{ LigmaObjectArray *a = g_value_get_boxed (ligma_value_array_index ($value)); if (a) $var = g_memdup2 (a->data, a->length * sizeof (gpointer)); }',
		     set_value_func  => 'ligma_value_set_object_array ($value, LIGMA_TYPE_IMAGE, (GObject **) $var, $var_len)',
		     take_value_func => 'ligma_value_take_object_array ($value, LIGMA_TYPE_IMAGE, (GObject **) $var, $var_len)' },

    itemarray   => { name            => 'ITEMARRAY',
		     gtype           => 'LIGMA_TYPE_OBJECT_ARRAY',
		     type            => 'LigmaItem **',
		     const_type      => 'const LigmaItem **',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type LigmaItem)',
		     out_annotate    => '(element-type LigmaItem) (transfer container)',
		     get_value_func  => '$var = (const LigmaItem **) ligma_value_get_object_array ($value)',
		     dup_value_func  => '{ LigmaObjectArray *a = g_value_get_boxed (ligma_value_array_index ($value)); if (a) $var = g_memdup2 (a->data, a->length * sizeof (gpointer)); }',
		     set_value_func  => 'ligma_value_set_object_array ($value, LIGMA_TYPE_ITEM, (GObject **) $var, $var_len)',
		     take_value_func => 'ligma_value_take_object_array ($value, LIGMA_TYPE_ITEM, (GObject **) $var, $var_len)' },

    layerarray  => { name            => 'LAYERARRAY',
		     gtype           => 'LIGMA_TYPE_OBJECT_ARRAY',
		     type            => 'LigmaLayer **',
		     const_type      => 'const LigmaLayer **',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type LigmaLayer)',
		     out_annotate    => '(element-type LigmaLayer) (transfer container)',
		     get_value_func  => '$var = (const LigmaLayer **) ligma_value_get_object_array ($value)',
		     dup_value_func  => '{ LigmaObjectArray *a = g_value_get_boxed (ligma_value_array_index ($value)); if (a) $var = g_memdup2 (a->data, a->length * sizeof (gpointer)); }',
		     set_value_func  => 'ligma_value_set_object_array ($value, LIGMA_TYPE_LAYER, (GObject **) $var, $var_len)',
		     take_value_func => 'ligma_value_take_object_array ($value, LIGMA_TYPE_LAYER, (GObject **) $var, $var_len)' },

    channelarray => { name            => 'CHANNELARRAY',
		     gtype           => 'LIGMA_TYPE_OBJECT_ARRAY',
		     type            => 'LigmaChannel **',
		     const_type      => 'const LigmaChannel **',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type LigmaChannel)',
		     out_annotate    => '(element-type LigmaChannel) (transfer container)',
		     get_value_func  => '$var = (const LigmaChannel **) ligma_value_get_object_array ($value)',
		     dup_value_func  => '{ LigmaObjectArray *a = g_value_get_boxed (ligma_value_array_index ($value)); if (a) $var = g_memdup2 (a->data, a->length * sizeof (gpointer)); }',
		     set_value_func  => 'ligma_value_set_object_array ($value, LIGMA_TYPE_CHANNEL, (GObject **) $var, $var_len)',
		     take_value_func => 'ligma_value_take_object_array ($value, LIGMA_TYPE_CHANNEL, (GObject **) $var, $var_len)' },

    vectorarray => { name            => 'VECTORSARRAY',
		     gtype           => 'LIGMA_TYPE_OBJECT_ARRAY',
		     type            => 'LigmaVectors **',
		     const_type      => 'const LigmaVectors **',
		     array           => 1,
		     init_value      => 'NULL',
		     in_annotate     => '(element-type LigmaVectors)',
		     out_annotate    => '(element-type LigmaVectors) (transfer container)',
		     get_value_func  => '$var = (const LigmaVectors **) ligma_value_get_object_array ($value)',
		     dup_value_func  => '{ LigmaObjectArray *a = g_value_get_boxed (ligma_value_array_index ($value)); if (a) $var = g_memdup2 (a->data, a->length * sizeof (gpointer)); }',
		     set_value_func  => 'ligma_value_set_object_array ($value, LIGMA_TYPE_VECTORS, (GObject **) $var, $var_len)',
		     take_value_func => 'ligma_value_take_object_array ($value, LIGMA_TYPE_VECTORS, (GObject **) $var, $var_len)' },

    color       => { name            => 'COLOR',
		     gtype           => 'LIGMA_TYPE_RGB',
		     type            => 'LigmaRGB ',
		     const_type      => 'LigmaRGB ',
		     struct          => 1,
		     init_value      => '{ 0.0, 0.0, 0.0, 1.0 }',
		     get_value_func  => 'ligma_value_get_rgb ($value, &$var)',
		     dup_value_func  => 'LIGMA_VALUES_GET_RGB ($value, &$var)',
		     set_value_func  => 'ligma_value_set_rgb ($value, $var)',
		     take_value_func => 'ligma_value_set_rgb ($value, &$var)',
		     headers         => [ qw(<cairo.h> "libligmacolor/ligmacolor.h") ] },

    display     => { name            => 'DISPLAY',
		     gtype           => 'LIGMA_TYPE_DISPLAY',
		     type            => 'LigmaDisplay *',
		     const_type      => 'LigmaDisplay *',
		     app_type        => 'LigmaDisplay *',
		     app_const_type  => 'LigmaDisplay *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_DISPLAY ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)' },

    image       => { name            => 'IMAGE',
		     gtype           => 'LIGMA_TYPE_IMAGE',
		     type            => 'LigmaImage *',
		     const_type      => 'LigmaImage *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_IMAGE ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmaimage.h") ] },

    item        => { name            => 'ITEM',
		     gtype           => 'LIGMA_TYPE_ITEM',
		     type            => 'LigmaItem *',
		     const_type      => 'LigmaItem *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_ITEM ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmaitem.h") ] },

    layer       => { name            => 'LAYER',
		     gtype           => 'LIGMA_TYPE_LAYER',
		     type            => 'LigmaLayer *',
		     const_type      => 'LigmaLayer *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_LAYER ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmalayer.h") ] },

    text_layer  => { name            => 'TEXT_LAYER',
		     gtype           => 'LIGMA_TYPE_TEXT_LAYER',
		     type            => 'LigmaTextLayer *',
		     const_type      => 'LigmaTextLayer *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_TEXT_LAYER ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("text/ligmatextlayer.h") ] },

    channel     => { name            => 'CHANNEL',
		     gtype           => 'LIGMA_TYPE_CHANNEL',
		     type            => 'LigmaChannel *',
		     const_type      => 'LigmaChannel *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_CHANNEL ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmachannel.h") ] },

    drawable    => { name            => 'DRAWABLE',
		     gtype           => 'LIGMA_TYPE_DRAWABLE',
		     type            => 'LigmaDrawable *',
		     const_type      => 'LigmaDrawable *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_DRAWABLE ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmadrawable.h") ] },

    selection   => { name            => 'SELECTION',
		     gtype           => 'LIGMA_TYPE_SELECTION',
		     type            => 'LigmaSelection *',
		     const_type      => 'LigmaSelection *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_SELECTION ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmaselection.h") ] },

    layer_mask  => { name            => 'CHANNEL',
		     gtype           => 'LIGMA_TYPE_LAYER_MASK',
		     type            => 'LigmaLayerMask *',
		     const_type      => 'LigmaLayerMask *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_LAYER_MASK ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("core/ligmalayermask.h") ] },

    vectors     => { name            => 'VECTORS',
		     gtype           => 'LIGMA_TYPE_VECTORS',
		     type            => 'LigmaVectors *',
		     const_type      => 'LigmaVectors *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_VECTORS ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)',
		     headers         => [ qw("vectors/ligmavectors.h") ] },

    file        => { name            => 'FILE',
		     gtype           => 'G_TYPE_FILE',
		     type            => 'GFile *',
		     const_type      => 'GFile *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer full)',
		     get_value_func  => '$var = g_value_get_object ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_FILE ($value)',
		     set_value_func  => 'g_value_set_object ($value, $var)',
		     take_value_func => 'g_value_set_object ($value, $var)' },

    parasite    => { name            => 'PARASITE',
		     gtype           => 'LIGMA_TYPE_PARASITE',
		     type            => 'LigmaParasite *',
		     const_type      => 'const LigmaParasite *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer full)',
		     get_value_func  => '$var = g_value_get_boxed ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_PARASITE ($value)',
		     set_value_func  => 'g_value_set_boxed ($value, $var)',
		     take_value_func => 'g_value_take_boxed ($value, $var)',
		     headers         => [ qw("libligmabase/ligmabase.h") ] },

    param       => { name            => 'PARAM',
		     gtype           => 'G_TYPE_PARAM_SPEC',
		     type            => 'GParamSpec *',
		     const_type      => 'GParamSpec *',
		     init_value      => 'NULL',
		     out_annotate    => '(transfer full)',
		     get_value_func  => '$var = g_value_get_param ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_DUP_PARAM ($value)',
		     set_value_func  => 'g_value_set_param ($value, $var)',
		     take_value_func => 'g_value_take_param ($value, $var)' },

    # Special cases
    enum        => { name            => 'ENUM',
		     gtype           => 'G_TYPE_ENUM',
		     type            => 'gint ',
		     const_type      => 'gint ',
		     init_value      => '0',
		     get_value_func  => '$var = g_value_get_enum ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_ENUM ($value)',
		     set_value_func  => 'g_value_set_enum ($value, $var)',
		     take_value_func => 'g_value_set_enum ($value, $var)' },

    boolean     => { name            => 'BOOLEAN',
		     gtype           => 'G_TYPE_BOOLEAN',
		     type            => 'gboolean ',
		     const_type      => 'gboolean ',
		     init_value      => 'FALSE',
		     get_value_func  => '$var = g_value_get_boolean ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_BOOLEAN ($value)',
		     set_value_func  => 'g_value_set_boolean ($value, $var)',
		     take_value_func => 'g_value_set_boolean ($value, $var)' },

    tattoo      => { name            => 'TATTOO',
		     gtype           => 'G_TYPE_UINT',
		     type            => 'guint ',
		     const_type      => 'guint ',
		     init_value      => '0',
		     get_value_func  => '$var = g_value_get_uint ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_UINT ($value)',
		     set_value_func  => 'g_value_set_uint ($value, $var)',
		     take_value_func => 'g_value_set_uint ($value, $var)' },

    guide       => { name            => 'GUIDE',
		     gtype           => 'G_TYPE_UINT',
		     type            => 'guint ',
		     const_type      => 'guint ',
		     init_value      => '0',
		     get_value_func  => '$var = g_value_get_uint ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_UINT ($value)',
		     set_value_func  => 'g_value_set_uint ($value, $var)',
		     take_value_func => 'g_value_set_uint ($value, $var)' },

   sample_point => { name            => 'SAMPLE_POINT',
		     gtype           => 'G_TYPE_UINT',
		     type            => 'guint ',
		     const_type      => 'guint ',
		     init_value      => '0',
		     get_value_func  => '$var = g_value_get_uint ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_UINT ($value)',
		     set_value_func  => 'g_value_set_uint ($value, $var)',
		     take_value_func => 'g_value_set_uint ($value, $var)' },

    unit        => { name            => 'UNIT',
		     gtype           => 'LIGMA_TYPE_UNIT',
		     type            => 'LigmaUnit ',
		     const_type      => 'LigmaUnit ',
		     init_value      => 'LIGMA_UNIT_PIXEL',
		     out_annotate    => '(transfer none)',
		     get_value_func  => '$var = g_value_get_int ($value)',
		     dup_value_func  => '$var = LIGMA_VALUES_GET_INT ($value)',
		     set_value_func  => 'g_value_set_int ($value, $var)',
		     take_value_func => 'g_value_set_int ($value, $var)' }
);

# Split out the parts of an arg constraint
sub arg_parse {
    my $arg = shift;

    if ($arg =~ /^enum (\w+)(.*)/) {
	my ($name, $remove) = ($1, $2);
	my @retvals = ('enum', $name);

	if ($remove && $remove =~ m@ \(no @) {
	    chop $remove; ($remove = substr($remove, 5)) =~ s/ $//;
	    push @retvals, split(/,\s*/, $remove);
	}

	return @retvals;
    }
    elsif ($arg =~ /^unit(?: \(min (.*?)\))?/) {
	my @retvals = ('unit');
	push @retvals, $1 if $1;
	return @retvals;
    }
    elsif ($arg =~ /^(?:([+-.\dA-Z_][^\s]*) \s* (<=|<))?
		     \s* (\w+) \s*
		     (?:(<=|<) \s* ([+-.\dA-Z_][^\s]*))?
		   /x) {
	return ($3, $1, $2, $5, $4);
    }
}

1;
