/* The GIMP -- an image manipulation program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/* NOTE: This file is autogenerated by pdbgen.pl. */

#include "config.h"


#include <glib-object.h>

#include "libgimpcolor/gimpcolor.h"

#include "pdb-types.h"
#include "procedural_db.h"
#include "core/gimpparamspecs.h"

#include "core/gimpchannel-combine.h"
#include "core/gimpchannel.h"
#include "core/gimpimage.h"

static ProcRecord channel_new_proc;
static ProcRecord channel_new_from_component_proc;
static ProcRecord channel_copy_proc;
static ProcRecord channel_combine_masks_proc;
static ProcRecord channel_get_show_masked_proc;
static ProcRecord channel_set_show_masked_proc;
static ProcRecord channel_get_opacity_proc;
static ProcRecord channel_set_opacity_proc;
static ProcRecord channel_get_color_proc;
static ProcRecord channel_set_color_proc;

void
register_channel_procs (Gimp *gimp)
{
  ProcRecord *procedure;

  /*
   * channel_new
   */
  procedure = procedural_db_init_proc (&channel_new_proc, 6, 1);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_IMAGE,
                              gimp_param_spec_image_id ("image",
                                                        "image",
                                                        "The image to which to add the channel",
                                                        gimp,
                                                        GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_int ("width",
                                                "width",
                                                "The channel width (1 <= width)",
                                                1, G_MAXINT32, 1,
                                                GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_int ("height",
                                                "height",
                                                "The channel height (1 <= height)",
                                                1, G_MAXINT32, 1,
                                                GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_STRING,
                              gimp_param_spec_string ("name",
                                                      "name",
                                                      "The channel name",
                                                      FALSE, FALSE,
                                                      NULL,
                                                      GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_FLOAT,
                              g_param_spec_double ("opacity",
                                                   "opacity",
                                                   "The channel opacity (0 <= opacity <= 100)",
                                                   0, 100, 0,
                                                   GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_COLOR,
                              gimp_param_spec_rgb ("color",
                                                   "color",
                                                   "The channel compositing color",
                                                   NULL,
                                                   GIMP_PARAM_READWRITE));
  procedural_db_add_return_value (procedure,
                                  GIMP_PDB_CHANNEL,
                                  gimp_param_spec_item_id ("channel",
                                                           "channel",
                                                           "The newly created channel",
                                                           gimp,
                                                           GIMP_TYPE_CHANNEL,
                                                           GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_new_from_component
   */
  procedure = procedural_db_init_proc (&channel_new_from_component_proc, 3, 1);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_IMAGE,
                              gimp_param_spec_image_id ("image",
                                                        "image",
                                                        "The image to which to add the channel",
                                                        gimp,
                                                        GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_enum ("component",
                                                 "component",
                                                 "The image component: { GIMP_RED_CHANNEL (0), GIMP_GREEN_CHANNEL (1), GIMP_BLUE_CHANNEL (2), GIMP_GRAY_CHANNEL (3), GIMP_INDEXED_CHANNEL (4), GIMP_ALPHA_CHANNEL (5) }",
                                                 GIMP_TYPE_CHANNEL_TYPE,
                                                 GIMP_RED_CHANNEL,
                                                 GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_STRING,
                              gimp_param_spec_string ("name",
                                                      "name",
                                                      "The channel name",
                                                      FALSE, FALSE,
                                                      NULL,
                                                      GIMP_PARAM_READWRITE));
  procedural_db_add_return_value (procedure,
                                  GIMP_PDB_CHANNEL,
                                  gimp_param_spec_item_id ("channel",
                                                           "channel",
                                                           "The newly created channel",
                                                           gimp,
                                                           GIMP_TYPE_CHANNEL,
                                                           GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_copy
   */
  procedure = procedural_db_init_proc (&channel_copy_proc, 1, 1);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel to copy",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_return_value (procedure,
                                  GIMP_PDB_CHANNEL,
                                  gimp_param_spec_item_id ("channel-copy",
                                                           "channel copy",
                                                           "The newly copied channel",
                                                           gimp,
                                                           GIMP_TYPE_CHANNEL,
                                                           GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_combine_masks
   */
  procedure = procedural_db_init_proc (&channel_combine_masks_proc, 5, 0);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel1",
                                                       "channel1",
                                                       "The channel1",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel2",
                                                       "channel2",
                                                       "The channel2",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_enum ("operation",
                                                 "operation",
                                                 "The selection operation: { GIMP_CHANNEL_OP_ADD (0), GIMP_CHANNEL_OP_SUBTRACT (1), GIMP_CHANNEL_OP_REPLACE (2), GIMP_CHANNEL_OP_INTERSECT (3) }",
                                                 GIMP_TYPE_CHANNEL_OPS,
                                                 GIMP_CHANNEL_OP_ADD,
                                                 GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_int ("offx",
                                                "offx",
                                                "x offset between upper left corner of channels: (second - first)",
                                                G_MININT32, G_MAXINT32, 0,
                                                GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_int ("offy",
                                                "offy",
                                                "y offset between upper left corner of channels: (second - first)",
                                                G_MININT32, G_MAXINT32, 0,
                                                GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_get_show_masked
   */
  procedure = procedural_db_init_proc (&channel_get_show_masked_proc, 1, 1);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_return_value (procedure,
                                  GIMP_PDB_INT32,
                                  g_param_spec_boolean ("show-masked",
                                                        "show masked",
                                                        "The channel composite method",
                                                        FALSE,
                                                        GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_set_show_masked
   */
  procedure = procedural_db_init_proc (&channel_set_show_masked_proc, 2, 0);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_INT32,
                              g_param_spec_boolean ("show-masked",
                                                    "show masked",
                                                    "The new channel composite method",
                                                    FALSE,
                                                    GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_get_opacity
   */
  procedure = procedural_db_init_proc (&channel_get_opacity_proc, 1, 1);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_return_value (procedure,
                                  GIMP_PDB_FLOAT,
                                  g_param_spec_double ("opacity",
                                                       "opacity",
                                                       "The channel opacity",
                                                       0, 100, 0,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_set_opacity
   */
  procedure = procedural_db_init_proc (&channel_set_opacity_proc, 2, 0);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_FLOAT,
                              g_param_spec_double ("opacity",
                                                   "opacity",
                                                   "The new channel opacity (0 <= opacity <= 100)",
                                                   0, 100, 0,
                                                   GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_get_color
   */
  procedure = procedural_db_init_proc (&channel_get_color_proc, 1, 1);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_return_value (procedure,
                                  GIMP_PDB_COLOR,
                                  gimp_param_spec_rgb ("color",
                                                       "color",
                                                       "The channel compositing color",
                                                       NULL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

  /*
   * channel_set_color
   */
  procedure = procedural_db_init_proc (&channel_set_color_proc, 2, 0);
  procedural_db_add_argument (procedure,
                              GIMP_PDB_CHANNEL,
                              gimp_param_spec_item_id ("channel",
                                                       "channel",
                                                       "The channel",
                                                       gimp,
                                                       GIMP_TYPE_CHANNEL,
                                                       GIMP_PARAM_READWRITE));
  procedural_db_add_argument (procedure,
                              GIMP_PDB_COLOR,
                              gimp_param_spec_rgb ("color",
                                                   "color",
                                                   "The new channel compositing color",
                                                   NULL,
                                                   GIMP_PARAM_READWRITE));
  procedural_db_register (gimp, procedure);

}

static Argument *
channel_new_invoker (ProcRecord   *proc_record,
                     Gimp         *gimp,
                     GimpContext  *context,
                     GimpProgress *progress,
                     Argument     *args)
{
  gboolean success = TRUE;
  Argument *return_vals;
  GimpImage *image;
  gint32 width;
  gint32 height;
  gchar *name;
  gdouble opacity;
  GimpRGB color;
  GimpChannel *channel = NULL;

  image = gimp_image_get_by_ID (gimp, args[0].value.pdb_int);
  if (! GIMP_IS_IMAGE (image))
    success = FALSE;

  width = args[1].value.pdb_int;
  if (width < 1)
    success = FALSE;

  height = args[2].value.pdb_int;
  if (height < 1)
    success = FALSE;

  name = (gchar *) args[3].value.pdb_pointer;
  if (name == NULL || !g_utf8_validate (name, -1, NULL))
    success = FALSE;

  opacity = args[4].value.pdb_float;
  if (opacity < 0.0 || opacity > 100.0)
    success = FALSE;

  color = args[5].value.pdb_color;

  if (success)
    {
      GimpRGB rgb_color = color;

      rgb_color.a = opacity / 100.0;
      channel = gimp_channel_new (image, width, height, name, &rgb_color);

      if (! channel)
        success = FALSE;
    }

  return_vals = procedural_db_return_values (proc_record, success);

  if (success)
    return_vals[1].value.pdb_int = channel ? gimp_item_get_ID (GIMP_ITEM (channel)) : -1;

  return return_vals;
}

static ProcRecord channel_new_proc =
{
  "gimp-channel-new",
  "gimp-channel-new",
  "Create a new channel.",
  "This procedure creates a new channel with the specified width and height. Name, opacity, and color are also supplied parameters. The new channel still needs to be added to the image, as this is not automatic. Add the new channel with the 'gimp_image_add_channel' command. Other attributes such as channel show masked, should be set with explicit procedure calls. The channel's contents are undefined initially.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_new_invoker } }
};

static Argument *
channel_new_from_component_invoker (ProcRecord   *proc_record,
                                    Gimp         *gimp,
                                    GimpContext  *context,
                                    GimpProgress *progress,
                                    Argument     *args)
{
  gboolean success = TRUE;
  Argument *return_vals;
  GimpImage *image;
  gint32 component;
  gchar *name;
  GimpChannel *channel = NULL;

  image = gimp_image_get_by_ID (gimp, args[0].value.pdb_int);
  if (! GIMP_IS_IMAGE (image))
    success = FALSE;

  component = args[1].value.pdb_int;
  if (component < GIMP_RED_CHANNEL || component > GIMP_ALPHA_CHANNEL)
    success = FALSE;

  name = (gchar *) args[2].value.pdb_pointer;
  if (name == NULL || !g_utf8_validate (name, -1, NULL))
    success = FALSE;

  if (success)
    {
      if (gimp_image_get_component_index (image, component) != -1)
        channel = gimp_channel_new_from_component (image,
                                                   component, name, NULL);

      if (channel)
        gimp_item_set_visible (GIMP_ITEM (channel), FALSE, FALSE);
      else
        success = FALSE;
    }

  return_vals = procedural_db_return_values (proc_record, success);

  if (success)
    return_vals[1].value.pdb_int = channel ? gimp_item_get_ID (GIMP_ITEM (channel)) : -1;

  return return_vals;
}

static ProcRecord channel_new_from_component_proc =
{
  "gimp-channel-new-from-component",
  "gimp-channel-new-from-component",
  "Create a new channel from a color component",
  "This procedure creates a new channel from a color component.",
  "Shlomi Fish <shlomif@iglu.org.il>",
  "Shlomi Fish",
  "2005",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_new_from_component_invoker } }
};

static Argument *
channel_copy_invoker (ProcRecord   *proc_record,
                      Gimp         *gimp,
                      GimpContext  *context,
                      GimpProgress *progress,
                      Argument     *args)
{
  gboolean success = TRUE;
  Argument *return_vals;
  GimpChannel *channel;
  GimpChannel *channel_copy = NULL;

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  if (success)
    {
      channel_copy = GIMP_CHANNEL (gimp_item_duplicate (GIMP_ITEM (channel),
                                   G_TYPE_FROM_INSTANCE (channel), FALSE));

      if (! channel_copy)
        success = FALSE;
    }

  return_vals = procedural_db_return_values (proc_record, success);

  if (success)
    return_vals[1].value.pdb_int = channel_copy ? gimp_item_get_ID (GIMP_ITEM (channel_copy)) : -1;

  return return_vals;
}

static ProcRecord channel_copy_proc =
{
  "gimp-channel-copy",
  "gimp-channel-copy",
  "Copy a channel.",
  "This procedure copies the specified channel and returns the copy.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_copy_invoker } }
};

static Argument *
channel_combine_masks_invoker (ProcRecord   *proc_record,
                               Gimp         *gimp,
                               GimpContext  *context,
                               GimpProgress *progress,
                               Argument     *args)
{
  gboolean success = TRUE;
  GimpChannel *channel1;
  GimpChannel *channel2;
  gint32 operation;
  gint32 offx;
  gint32 offy;

  channel1 = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel1) && ! gimp_item_is_removed (GIMP_ITEM (channel1))))
    success = FALSE;

  channel2 = (GimpChannel *) gimp_item_get_by_ID (gimp, args[1].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel2) && ! gimp_item_is_removed (GIMP_ITEM (channel2))))
    success = FALSE;

  operation = args[2].value.pdb_int;
  if (operation < GIMP_CHANNEL_OP_ADD || operation > GIMP_CHANNEL_OP_INTERSECT)
    success = FALSE;

  offx = args[3].value.pdb_int;

  offy = args[4].value.pdb_int;

  if (success)
    {
      gimp_channel_combine_mask (channel1, channel2, operation, offx, offy);
    }

  return procedural_db_return_values (proc_record, success);
}

static ProcRecord channel_combine_masks_proc =
{
  "gimp-channel-combine-masks",
  "gimp-channel-combine-masks",
  "Combine two channel masks.",
  "This procedure combines two channel masks. The result is stored in the first channel.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_combine_masks_invoker } }
};

static Argument *
channel_get_show_masked_invoker (ProcRecord   *proc_record,
                                 Gimp         *gimp,
                                 GimpContext  *context,
                                 GimpProgress *progress,
                                 Argument     *args)
{
  gboolean success = TRUE;
  Argument *return_vals;
  GimpChannel *channel;
  gboolean show_masked = FALSE;

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  if (success)
    {
      show_masked = gimp_channel_get_show_masked (channel);
    }

  return_vals = procedural_db_return_values (proc_record, success);

  if (success)
    return_vals[1].value.pdb_int = show_masked;

  return return_vals;
}

static ProcRecord channel_get_show_masked_proc =
{
  "gimp-channel-get-show-masked",
  "gimp-channel-get-show-masked",
  "Get the composite method of the specified channel.",
  "This procedure returns the specified channel's composite method. If it is TRUE, then the channel is composited with the image so that masked regions are shown. Otherwise, selected regions are shown.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_get_show_masked_invoker } }
};

static Argument *
channel_set_show_masked_invoker (ProcRecord   *proc_record,
                                 Gimp         *gimp,
                                 GimpContext  *context,
                                 GimpProgress *progress,
                                 Argument     *args)
{
  gboolean success = TRUE;
  GimpChannel *channel;
  gboolean show_masked;

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  show_masked = args[1].value.pdb_int ? TRUE : FALSE;

  if (success)
    {
      gimp_channel_set_show_masked (channel, show_masked);
    }

  return procedural_db_return_values (proc_record, success);
}

static ProcRecord channel_set_show_masked_proc =
{
  "gimp-channel-set-show-masked",
  "gimp-channel-set-show-masked",
  "Set the composite method of the specified channel.",
  "This procedure sets the specified channel's composite method. If it is TRUE, then the channel is composited with the image so that masked regions are shown. Otherwise, selected regions are shown.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_set_show_masked_invoker } }
};

static Argument *
channel_get_opacity_invoker (ProcRecord   *proc_record,
                             Gimp         *gimp,
                             GimpContext  *context,
                             GimpProgress *progress,
                             Argument     *args)
{
  gboolean success = TRUE;
  Argument *return_vals;
  GimpChannel *channel;
  gdouble opacity = 0.0;

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  if (success)
    {
      opacity = gimp_channel_get_opacity (channel) * 100;
    }

  return_vals = procedural_db_return_values (proc_record, success);

  if (success)
    return_vals[1].value.pdb_float = opacity;

  return return_vals;
}

static ProcRecord channel_get_opacity_proc =
{
  "gimp-channel-get-opacity",
  "gimp-channel-get-opacity",
  "Get the opacity of the specified channel.",
  "This procedure returns the specified channel's opacity.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_get_opacity_invoker } }
};

static Argument *
channel_set_opacity_invoker (ProcRecord   *proc_record,
                             Gimp         *gimp,
                             GimpContext  *context,
                             GimpProgress *progress,
                             Argument     *args)
{
  gboolean success = TRUE;
  GimpChannel *channel;
  gdouble opacity;

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  opacity = args[1].value.pdb_float;
  if (opacity < 0.0 || opacity > 100.0)
    success = FALSE;

  if (success)
    {
      gimp_channel_set_opacity (channel, opacity / 100.0, TRUE);
    }

  return procedural_db_return_values (proc_record, success);
}

static ProcRecord channel_set_opacity_proc =
{
  "gimp-channel-set-opacity",
  "gimp-channel-set-opacity",
  "Set the opacity of the specified channel.",
  "This procedure sets the specified channel's opacity.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_set_opacity_invoker } }
};

static Argument *
channel_get_color_invoker (ProcRecord   *proc_record,
                           Gimp         *gimp,
                           GimpContext  *context,
                           GimpProgress *progress,
                           Argument     *args)
{
  gboolean success = TRUE;
  Argument *return_vals;
  GimpChannel *channel;
  GimpRGB color = { 0.0, 0.0, 0.0, 1.0 };

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  if (success)
    {
      gimp_channel_get_color (channel, &color);
    }

  return_vals = procedural_db_return_values (proc_record, success);

  if (success)
    return_vals[1].value.pdb_color = color;

  return return_vals;
}

static ProcRecord channel_get_color_proc =
{
  "gimp-channel-get-color",
  "gimp-channel-get-color",
  "Get the compositing color of the specified channel.",
  "This procedure returns the specified channel's compositing color.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_get_color_invoker } }
};

static Argument *
channel_set_color_invoker (ProcRecord   *proc_record,
                           Gimp         *gimp,
                           GimpContext  *context,
                           GimpProgress *progress,
                           Argument     *args)
{
  gboolean success = TRUE;
  GimpChannel *channel;
  GimpRGB color;

  channel = (GimpChannel *) gimp_item_get_by_ID (gimp, args[0].value.pdb_int);
  if (! (GIMP_IS_CHANNEL (channel) && ! gimp_item_is_removed (GIMP_ITEM (channel))))
    success = FALSE;

  color = args[1].value.pdb_color;

  if (success)
    {
      GimpRGB rgb_color = color;

      rgb_color.a = channel->color.a;
      gimp_channel_set_color (channel, &rgb_color, TRUE);
    }

  return procedural_db_return_values (proc_record, success);
}

static ProcRecord channel_set_color_proc =
{
  "gimp-channel-set-color",
  "gimp-channel-set-color",
  "Set the compositing color of the specified channel.",
  "This procedure sets the specified channel's compositing color.",
  "Spencer Kimball & Peter Mattis",
  "Spencer Kimball & Peter Mattis",
  "1995-1996",
  NULL,
  GIMP_INTERNAL,
  0, NULL, 0, NULL,
  { { channel_set_color_invoker } }
};
