/* LIGMA - The GNU Image Manipulation Program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl. */

#include "config.h"

#include "stamp-pdbgen.h"

#include <string.h>

#include <gegl.h>

#include <gdk-pixbuf/gdk-pixbuf.h>

#include "libligmabase/ligmabase.h"

#include "pdb-types.h"

#include "core/ligma.h"
#include "core/ligmacontainer-filter.h"
#include "core/ligmacontext.h"
#include "core/ligmadatafactory.h"
#include "core/ligmagradient.h"
#include "core/ligmaparamspecs.h"

#include "ligmapdb.h"
#include "ligmapdb-utils.h"
#include "ligmaprocedure.h"
#include "internal-procs.h"


static LigmaValueArray *
gradients_refresh_invoker (LigmaProcedure         *procedure,
                           Ligma                  *ligma,
                           LigmaContext           *context,
                           LigmaProgress          *progress,
                           const LigmaValueArray  *args,
                           GError               **error)
{
  ligma_data_factory_data_refresh (ligma->gradient_factory, context);

  return ligma_procedure_get_return_values (procedure, TRUE, NULL);
}

static LigmaValueArray *
gradients_get_list_invoker (LigmaProcedure         *procedure,
                            Ligma                  *ligma,
                            LigmaContext           *context,
                            LigmaProgress          *progress,
                            const LigmaValueArray  *args,
                            GError               **error)
{
  gboolean success = TRUE;
  LigmaValueArray *return_vals;
  const gchar *filter;
  gchar **gradient_list = NULL;

  filter = g_value_get_string (ligma_value_array_index (args, 0));

  if (success)
    {
      gradient_list = ligma_container_get_filtered_name_array (ligma_data_factory_get_container (ligma->gradient_factory),
                                                              filter);
    }

  return_vals = ligma_procedure_get_return_values (procedure, success,
                                                  error ? *error : NULL);

  if (success)
    g_value_take_boxed (ligma_value_array_index (return_vals, 1), gradient_list);

  return return_vals;
}

void
register_gradients_procs (LigmaPDB *pdb)
{
  LigmaProcedure *procedure;

  /*
   * ligma-gradients-refresh
   */
  procedure = ligma_procedure_new (gradients_refresh_invoker);
  ligma_object_set_static_name (LIGMA_OBJECT (procedure),
                               "ligma-gradients-refresh");
  ligma_procedure_set_static_help (procedure,
                                  "Refresh current gradients. This function always succeeds.",
                                  "This procedure retrieves all gradients currently in the user's gradient path and updates the gradient dialogs accordingly.",
                                  NULL);
  ligma_procedure_set_static_attribution (procedure,
                                         "Michael Natterer <mitch@ligma.org>",
                                         "Michael Natterer",
                                         "2002");
  ligma_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);

  /*
   * ligma-gradients-get-list
   */
  procedure = ligma_procedure_new (gradients_get_list_invoker);
  ligma_object_set_static_name (LIGMA_OBJECT (procedure),
                               "ligma-gradients-get-list");
  ligma_procedure_set_static_help (procedure,
                                  "Retrieve the list of loaded gradients.",
                                  "This procedure returns a list of the gradients that are currently loaded. You can later use the 'ligma-context-set-gradient' function to set the active gradient.",
                                  NULL);
  ligma_procedure_set_static_attribution (procedure,
                                         "Federico Mena Quintero",
                                         "Federico Mena Quintero",
                                         "1997");
  ligma_procedure_add_argument (procedure,
                               ligma_param_spec_string ("filter",
                                                       "filter",
                                                       "An optional regular expression used to filter the list",
                                                       FALSE, TRUE, FALSE,
                                                       NULL,
                                                       LIGMA_PARAM_READWRITE));
  ligma_procedure_add_return_value (procedure,
                                   g_param_spec_boxed ("gradient-list",
                                                       "gradient list",
                                                       "The list of gradient names",
                                                       G_TYPE_STRV,
                                                       LIGMA_PARAM_READWRITE));
  ligma_pdb_register_procedure (pdb, procedure);
  g_object_unref (procedure);
}
