scalable_images = \
	scalable/dialog-error-symbolic.svg				\
	scalable/dialog-information-symbolic.svg			\
	scalable/dialog-question-symbolic.svg				\
	scalable/dialog-warning-symbolic.svg				\
	scalable/document-new-symbolic.svg				\
	scalable/document-open-symbolic.svg				\
	scalable/document-open-recent-symbolic.svg			\
	scalable/document-print-symbolic.svg				\
	scalable/document-revert-symbolic.svg				\
	scalable/document-save-symbolic.svg				\
	scalable/document-save-as-symbolic.svg				\
	scalable/edit-clear-symbolic.svg					\
	scalable/edit-copy-symbolic.svg					\
	scalable/edit-cut-symbolic.svg					\
	scalable/edit-delete-symbolic.svg				\
	scalable/edit-paste-symbolic.svg					\
	scalable/edit-redo-symbolic.svg					\
	scalable/edit-undo-symbolic.svg					\
	scalable/folder-symbolic.svg					\
	scalable/folder-new-symbolic.svg					\
	scalable/format-indent-more-symbolic.svg				\
	scalable/format-justify-fill-symbolic.svg			\
	scalable/format-justify-center-symbolic.svg			\
	scalable/format-justify-left-symbolic.svg			\
	scalable/format-justify-right-symbolic.svg			\
	scalable/format-text-direction-ltr-symbolic.svg			\
	scalable/format-text-direction-rtl-symbolic.svg			\
	scalable/go-bottom-symbolic.svg					\
	scalable/go-down-symbolic.svg					\
	scalable/go-first-symbolic.svg					\
	scalable/go-home-symbolic.svg					\
	scalable/go-last-symbolic.svg					\
	scalable/go-next-symbolic.svg					\
	scalable/go-previous-symbolic.svg				\
	scalable/go-top-symbolic.svg					\
	scalable/go-up-symbolic.svg					\
	scalable/help-about-symbolic.svg					\
	scalable/list-add-symbolic.svg					\
	scalable/list-remove-symbolic.svg				\
	scalable/media-floppy-symbolic.svg				\
	scalable/media-optical-symbolic.svg				\
	scalable/media-playback-pause-symbolic.svg			\
	scalable/media-playback-start-symbolic.svg			\
	scalable/media-record-symbolic.svg				\
	scalable/media-seek-backward-symbolic.svg			\
	scalable/media-skip-backward-symbolic.svg			\
	scalable/media-skip-forward-symbolic.svg				\
	scalable/object-flip-horizontal-symbolic.svg			\
	scalable/object-flip-vertical-symbolic.svg			\
	scalable/object-rotate-left-symbolic.svg			\
	scalable/object-rotate-right-symbolic.svg			\
	scalable/preferences-system-symbolic.svg				\
	scalable/process-stop-symbolic.svg				\
	scalable/system-run-symbolic.svg					\
	scalable/view-fullscreen-symbolic.svg				\
	scalable/view-refresh-symbolic.svg				\
	scalable/window-close-symbolic.svg				\
	scalable/window-new-symbolic.svg					\
	scalable/zoom-fit-best-symbolic.svg				\
	scalable/zoom-in-symbolic.svg					\
	scalable/zoom-original-symbolic.svg				\
	scalable/zoom-out-symbolic.svg					\
	\
	scalable/gtk-cancel-symbolic.svg					\
	scalable/gtk-edit-symbolic.svg					\
	scalable/gtk-no-symbolic.svg					\
	scalable/gtk-ok-symbolic.svg					\
	scalable/gtk-select-color-symbolic.svg				\
	scalable/gtk-select-font-symbolic.svg				\
	scalable/gtk-yes-symbolic.svg					\
	\
	scalable/gimp-anchor-symbolic.svg				\
	scalable/gimp-attach-symbolic.svg				\
	scalable/gimp-business-card-symbolic.svg				\
	scalable/gimp-cap-butt-symbolic.svg				\
	scalable/gimp-cap-round-symbolic.svg				\
	scalable/gimp-cap-square-symbolic.svg				\
	scalable/gimp-center-symbolic.svg				\
	scalable/gimp-channel-alpha-symbolic.svg				\
	scalable/gimp-channel-blue-symbolic.svg				\
	scalable/gimp-channel-gray-symbolic.svg				\
	scalable/gimp-channel-green-symbolic.svg				\
	scalable/gimp-channel-indexed-symbolic.svg			\
	scalable/gimp-channel-red-symbolic.svg				\
	scalable/gimp-channels-symbolic.svg				\
	scalable/gimp-channel-symbolic.svg				\
	scalable/gimp-char-picker-symbolic.svg				\
	scalable/gimp-clipboard-symbolic.svg				\
	scalable/gimp-close-symbolic.svg					\
	scalable/gimp-close-all-symbolic.svg				\
	scalable/gimp-colormap-symbolic.svg				\
	scalable/gimp-color-picker-black-symbolic.svg			\
	scalable/gimp-color-picker-gray-symbolic.svg			\
	scalable/gimp-color-picker-white-symbolic.svg			\
	scalable/gimp-color-pick-from-screen-symbolic.svg		\
	scalable/gimp-color-cmyk-symbolic.svg				\
	scalable/gimp-color-space-linear-symbolic.svg			\
	scalable/gimp-color-space-non-linear-symbolic.svg		\
	scalable/gimp-color-space-perceptual-symbolic.svg		\
	scalable/gimp-color-triangle-symbolic.svg			\
	scalable/gimp-color-water-symbolic.svg				\
	scalable/gimp-controller-keyboard-symbolic.svg			\
	scalable/gimp-controller-linux-input-symbolic.svg		\
	scalable/gimp-controller-midi-symbolic.svg			\
	scalable/gimp-controller-symbolic.svg				\
	scalable/gimp-controller-wheel-symbolic.svg			\
	scalable/gimp-convert-grayscale-symbolic.svg			\
	scalable/gimp-convert-indexed-symbolic.svg			\
	scalable/gimp-convert-rgb-symbolic.svg				\
	scalable/gimp-cursor-symbolic.svg				\
	scalable/gimp-curve-free-symbolic.svg				\
	scalable/gimp-curve-point-corner-symbolic.svg			\
	scalable/gimp-curve-point-smooth-symbolic.svg			\
	scalable/gimp-curve-smooth-symbolic.svg				\
	scalable/gimp-dashboard-symbolic.svg				\
	scalable/gimp-default-colors-symbolic.svg			\
	scalable/gimp-detach-symbolic.svg				\
	scalable/gimp-device-status-symbolic.svg				\
	scalable/gimp-display-symbolic.svg				\
	scalable/gimp-display-filter-clip-warning-symbolic.svg		\
	scalable/gimp-display-filter-colorblind-symbolic.svg		\
	scalable/gimp-display-filter-contrast-symbolic.svg		\
	scalable/gimp-display-filter-gamma-symbolic.svg			\
	scalable/gimp-display-filter-lcms-symbolic.svg			\
	scalable/gimp-display-filter-proof-symbolic.svg			\
	scalable/gimp-display-filter-symbolic.svg			\
	scalable/gimp-duplicate-symbolic.svg				\
	scalable/gimp-dynamics-symbolic.svg				\
	scalable/gimp-file-manager-symbolic.svg				\
	scalable/gimp-floating-selection-symbolic.svg			\
	scalable/gimp-gegl-symbolic.svg					\
	scalable/gimp-gradient-bilinear-symbolic.svg			\
	scalable/gimp-gradient-conical-asymmetric-symbolic.svg		\
	scalable/gimp-gradient-conical-symmetric-symbolic.svg		\
	scalable/gimp-gradient-linear-symbolic.svg			\
	scalable/gimp-gradient-radial-symbolic.svg			\
	scalable/gimp-gradient-shapeburst-angular-symbolic.svg		\
	scalable/gimp-gradient-shapeburst-dimpled-symbolic.svg		\
	scalable/gimp-gradient-shapeburst-spherical-symbolic.svg		\
	scalable/gimp-gradient-spiral-anticlockwise-symbolic.svg		\
	scalable/gimp-gradient-spiral-clockwise-symbolic.svg		\
	scalable/gimp-gradient-square-symbolic.svg			\
	scalable/gimp-gravity-east-symbolic.svg				\
	scalable/gimp-gravity-north-east-symbolic.svg			\
	scalable/gimp-gravity-north-symbolic.svg				\
	scalable/gimp-gravity-north-west-symbolic.svg			\
	scalable/gimp-gravity-south-east-symbolic.svg			\
	scalable/gimp-gravity-south-symbolic.svg				\
	scalable/gimp-gravity-south-west-symbolic.svg			\
	scalable/gimp-gravity-west-symbolic.svg				\
	scalable/gimp-grid-symbolic.svg					\
	scalable/gimp-group-layer-symbolic.svg				\
	scalable/gimp-hcenter-symbolic.svg				\
	scalable/gimp-hchain-broken-symbolic.svg				\
	scalable/gimp-hchain-symbolic.svg				\
	scalable/gimp-hfill-symbolic.svg					\
	scalable/gimp-histogram-linear-symbolic.svg			\
	scalable/gimp-histogram-logarithmic-symbolic.svg			\
	scalable/gimp-histogram-symbolic.svg				\
	scalable/gimp-images-symbolic.svg				\
	scalable/gimp-image-symbolic.svg					\
	scalable/gimp-image-open-symbolic.svg				\
	scalable/gimp-image-reload-symbolic.svg				\
	scalable/gimp-input-device-symbolic.svg				\
	scalable/gimp-invert-symbolic.svg				\
	scalable/gimp-join-bevel-symbolic.svg				\
	scalable/gimp-join-miter-symbolic.svg				\
	scalable/gimp-join-round-symbolic.svg				\
	scalable/gimp-landscape-symbolic.svg				\
	scalable/gimp-layer-mask-symbolic.svg				\
	scalable/gimp-layers-symbolic.svg				\
	scalable/gimp-layer-symbolic.svg					\
	scalable/gimp-layer-to-imagesize-symbolic.svg			\
	scalable/gimp-letter-spacing-symbolic.svg			\
	scalable/gimp-line-spacing-symbolic.svg				\
	scalable/gimp-linked-symbolic.svg				\
	scalable/gimp-list-symbolic.svg					\
	scalable/gimp-marker-symbolic.svg				\
	scalable/gimp-menu-left-symbolic.svg				\
	scalable/gimp-menu-right-symbolic.svg				\
	scalable/gimp-merge-down-symbolic.svg				\
	scalable/gimp-move-to-screen-symbolic.svg			\
	scalable/gimp-navigation-symbolic.svg				\
	scalable/gimp-paste-as-new-symbolic.svg				\
	scalable/gimp-paste-into-symbolic.svg				\
	scalable/gimp-path-symbolic.svg					\
	scalable/gimp-paths-symbolic.svg					\
	scalable/gimp-path-stroke-symbolic.svg				\
	scalable/gimp-pattern-symbolic.svg				\
	scalable/gimp-pivot-center-symbolic.svg				\
	scalable/gimp-pivot-east-symbolic.svg				\
	scalable/gimp-pivot-north-symbolic.svg				\
	scalable/gimp-pivot-north-east-symbolic.svg			\
	scalable/gimp-pivot-north-west-symbolic.svg			\
	scalable/gimp-pivot-south-symbolic.svg				\
	scalable/gimp-pivot-south-east-symbolic.svg			\
	scalable/gimp-pivot-south-west-symbolic.svg			\
	scalable/gimp-pivot-west-symbolic.svg				\
	scalable/gimp-plugin-symbolic.svg				\
	scalable/gimp-portrait-symbolic.svg				\
	scalable/gimp-prefs-color-management-symbolic.svg		\
	scalable/gimp-prefs-controllers-symbolic.svg			\
	scalable/gimp-prefs-default-comment-symbolic.svg			\
	scalable/gimp-prefs-default-grid-symbolic.svg			\
	scalable/gimp-prefs-display-symbolic.svg				\
	scalable/gimp-prefs-folders-symbolic.svg				\
	scalable/gimp-prefs-folders-brushes-symbolic.svg			\
	scalable/gimp-prefs-folders-dynamics-symbolic.svg		\
	scalable/gimp-prefs-folders-environ-symbolic.svg			\
	scalable/gimp-prefs-folders-fonts-symbolic.svg			\
	scalable/gimp-prefs-folders-gradients-symbolic.svg		\
	scalable/gimp-prefs-folders-icon-themes-symbolic.svg		\
	scalable/gimp-prefs-folders-interp-symbolic.svg			\
	scalable/gimp-prefs-folders-modules-symbolic.svg			\
	scalable/gimp-prefs-folders-mypaint-brushes-symbolic.svg		\
	scalable/gimp-prefs-folders-palettes-symbolic.svg		\
	scalable/gimp-prefs-folders-patterns-symbolic.svg		\
	scalable/gimp-prefs-folders-plug-ins-symbolic.svg		\
	scalable/gimp-prefs-folders-scripts-symbolic.svg			\
	scalable/gimp-prefs-folders-themes-symbolic.svg			\
	scalable/gimp-prefs-folders-tool-plug-ins-symbolic.svg		\
	scalable/gimp-prefs-folders-tool-presets-symbolic.svg		\
	scalable/gimp-prefs-folders-tools-symbolic.svg			\
	scalable/gimp-prefs-help-system-symbolic.svg			\
	scalable/gimp-prefs-icon-theme-symbolic.svg			\
	scalable/gimp-prefs-image-title-symbolic.svg			\
	scalable/gimp-prefs-image-windows-symbolic.svg			\
	scalable/gimp-prefs-image-windows-appearance-symbolic.svg	\
	scalable/gimp-prefs-image-windows-snapping-symbolic.svg		\
	scalable/gimp-prefs-import-export-symbolic.svg			\
	scalable/gimp-prefs-input-devices-symbolic.svg			\
	scalable/gimp-prefs-interface-symbolic.svg			\
	scalable/gimp-prefs-new-image-symbolic.svg			\
	scalable/gimp-prefs-playground-symbolic.svg			\
	scalable/gimp-prefs-session-symbolic.svg				\
	scalable/gimp-prefs-system-resources-symbolic.svg		\
	scalable/gimp-prefs-theme-symbolic.svg				\
	scalable/gimp-prefs-toolbox-symbolic.svg				\
	scalable/gimp-prefs-tool-options-symbolic.svg			\
	scalable/gimp-prefs-window-management-symbolic.svg		\
	scalable/gimp-quick-mask-off-symbolic.svg			\
	scalable/gimp-quick-mask-on-symbolic.svg				\
	scalable/gimp-reset-symbolic.svg					\
	scalable/gimp-reshow-filter-symbolic.svg				\
	scalable/gimp-resize-symbolic.svg				\
	scalable/gimp-rotate-180-symbolic.svg				\
	scalable/gimp-sample-point-symbolic.svg				\
	scalable/gimp-scale-symbolic.svg					\
	scalable/gimp-selection-symbolic.svg				\
	scalable/gimp-selection-add-symbolic.svg				\
	scalable/gimp-selection-all-symbolic.svg				\
	scalable/gimp-selection-border-symbolic.svg			\
	scalable/gimp-selection-grow-symbolic.svg			\
	scalable/gimp-selection-intersect-symbolic.svg			\
	scalable/gimp-selection-none-symbolic.svg			\
	scalable/gimp-selection-replace-symbolic.svg			\
	scalable/gimp-selection-shrink-symbolic.svg			\
	scalable/gimp-selection-stroke-symbolic.svg			\
	scalable/gimp-selection-subtract-symbolic.svg			\
	scalable/gimp-selection-to-channel-symbolic.svg			\
	scalable/gimp-selection-to-path-symbolic.svg			\
	scalable/gimp-shape-circle-symbolic.svg				\
	scalable/gimp-shape-diamond-symbolic.svg				\
	scalable/gimp-shape-square-symbolic.svg				\
	scalable/gimp-shred-symbolic.svg					\
	scalable/gimp-smartphone-symbolic.svg				\
	scalable/gimp-swap-colors-symbolic.svg				\
	scalable/gimp-symmetry-symbolic.svg				\
	scalable/gimp-template-symbolic.svg				\
	scalable/gimp-text-dir-ttb-rtl-symbolic.svg			\
	scalable/gimp-text-dir-ttb-rtl-upright-symbolic.svg		\
	scalable/gimp-text-dir-ttb-ltr-symbolic.svg			\
	scalable/gimp-text-dir-ttb-ltr-upright-symbolic.svg		\
	scalable/gimp-text-layer-symbolic.svg				\
	scalable/gimp-toilet-paper-symbolic.svg				\
	scalable/gimp-tool-airbrush-symbolic.svg				\
	scalable/gimp-tool-align-symbolic.svg				\
	scalable/gimp-tool-blur-symbolic.svg				\
	scalable/gimp-tool-brightness-contrast-symbolic.svg		\
	scalable/gimp-tool-bucket-fill-symbolic.svg			\
	scalable/gimp-tool-by-color-select-symbolic.svg			\
	scalable/gimp-tool-cage-symbolic.svg				\
	scalable/gimp-tool-clone-symbolic.svg				\
	scalable/gimp-tool-color-balance-symbolic.svg			\
	scalable/gimp-tool-colorize-symbolic.svg				\
	scalable/gimp-tool-color-picker-symbolic.svg			\
	scalable/gimp-tool-color-temperature-symbolic.svg		\
	scalable/gimp-tool-crop-symbolic.svg				\
	scalable/gimp-tool-curves-symbolic.svg				\
	scalable/gimp-tool-desaturate-symbolic.svg			\
	scalable/gimp-tool-dodge-symbolic.svg				\
	scalable/gimp-tool-ellipse-select-symbolic.svg			\
	scalable/gimp-tool-eraser-symbolic.svg				\
	scalable/gimp-tool-exposure-symbolic.svg				\
	scalable/gimp-tool-flip-symbolic.svg				\
	scalable/gimp-tool-foreground-select-symbolic.svg		\
	scalable/gimp-tool-free-select-symbolic.svg			\
	scalable/gimp-tool-fuzzy-select-symbolic.svg			\
	scalable/gimp-tool-gradient-symbolic.svg				\
	scalable/gimp-tool-handle-transform-symbolic.svg			\
	scalable/gimp-tool-heal-symbolic.svg				\
	scalable/gimp-tool-hue-saturation-symbolic.svg			\
	scalable/gimp-tool-ink-symbolic.svg				\
	scalable/gimp-tool-iscissors-symbolic.svg			\
	scalable/gimp-tool-levels-symbolic.svg				\
	scalable/gimp-tool-measure-symbolic.svg				\
	scalable/gimp-tool-move-symbolic.svg				\
	scalable/gimp-tool-mypaint-brush-symbolic.svg			\
	scalable/gimp-tool-n-point-deformation-symbolic.svg		\
	scalable/gimp-tool-offset-symbolic.svg				\
	scalable/gimp-tool-options-symbolic.svg				\
	scalable/gimp-tool-paintbrush-symbolic.svg			\
	scalable/gimp-tool-path-symbolic.svg				\
	scalable/gimp-tool-pencil-symbolic.svg				\
	scalable/gimp-tool-perspective-clone-symbolic.svg		\
	scalable/gimp-tool-perspective-symbolic.svg			\
	scalable/gimp-tool-posterize-symbolic.svg			\
	scalable/gimp-tool-preset-symbolic.svg				\
	scalable/gimp-tool-rect-select-symbolic.svg			\
	scalable/gimp-tool-rotate-symbolic.svg				\
	scalable/gimp-tool-scale-symbolic.svg				\
	scalable/gimp-tool-seamless-clone-symbolic.svg			\
	scalable/gimp-tool-shadows-highlights-symbolic.svg		\
	scalable/gimp-tool-shear-symbolic.svg				\
	scalable/gimp-tool-smudge-symbolic.svg				\
	scalable/gimp-tools-symbolic.svg					\
	scalable/gimp-tool-text-symbolic.svg				\
	scalable/gimp-tool-threshold-symbolic.svg			\
	scalable/gimp-tool-transform-3d-symbolic.svg			\
	scalable/gimp-tool-unified-transform-symbolic.svg		\
	scalable/gimp-tool-warp-symbolic.svg				\
	scalable/gimp-tool-zoom-symbolic.svg				\
	scalable/gimp-transform-3d-camera-symbolic.svg			\
	scalable/gimp-transform-3d-move-symbolic.svg			\
	scalable/gimp-transform-3d-rotate-symbolic.svg			\
	scalable/gimp-transparency-symbolic.svg				\
	scalable/gimp-undo-history-symbolic.svg				\
	scalable/gimp-user-manual-symbolic.svg				\
	scalable/gimp-vcenter-symbolic.svg				\
	scalable/gimp-vchain-symbolic.svg				\
	scalable/gimp-vchain-broken-symbolic.svg				\
	scalable/gimp-vfill-symbolic.svg					\
	scalable/gimp-video-symbolic.svg					\
	scalable/gimp-visible-symbolic.svg				\
	scalable/gimp-web-symbolic.svg					\
	scalable/gimp-wilber-symbolic.svg				\
	scalable/gimp-wilber-eek-symbolic.svg				\
	scalable/gimp-wilber-outline-symbolic.svg			\
	scalable/gimp-zoom-follow-window-symbolic.svg

vector24_images = \
	24/dialog-error-symbolic.svg					\
	24/dialog-information-symbolic.svg				\
	24/dialog-question-symbolic.svg					\
	24/dialog-warning-symbolic.svg					\
	24/document-print-symbolic.svg					\
	24/media-floppy-symbolic.svg 					\
	24/media-optical-symbolic.svg					\
	\
	24/gtk-select-color-symbolic.svg					\
	\
	24/gimp-business-card-symbolic.svg				\
	24/gimp-center-symbolic.svg					\
	24/gimp-channel-symbolic.svg					\
	24/gimp-channel-alpha-symbolic.svg				\
	24/gimp-channel-blue-symbolic.svg				\
	24/gimp-channel-gray-symbolic.svg				\
	24/gimp-channel-green-symbolic.svg				\
	24/gimp-channel-indexed-symbolic.svg				\
	24/gimp-channel-red-symbolic.svg					\
	24/gimp-channels-symbolic.svg					\
	24/gimp-char-picker-symbolic.svg					\
	24/gimp-colormap-symbolic.svg					\
	24/gimp-color-space-linear-symbolic.svg				\
	24/gimp-color-space-non-linear-symbolic.svg			\
	24/gimp-color-space-perceptual-symbolic.svg			\
	24/gimp-controller-symbolic.svg					\
	24/gimp-controller-keyboard-symbolic.svg				\
	24/gimp-controller-linux-input-symbolic.svg			\
	24/gimp-controller-midi-symbolic.svg				\
	24/gimp-controller-wheel-symbolic.svg				\
	24/gimp-cursor-symbolic.svg					\
	24/gimp-device-status-symbolic.svg				\
	24/gimp-display-symbolic.svg					\
	24/gimp-display-filter-symbolic.svg				\
	24/gimp-display-filter-clip-warning-symbolic.svg			\
	24/gimp-display-filter-colorblind-symbolic.svg			\
	24/gimp-display-filter-contrast-symbolic.svg			\
	24/gimp-display-filter-gamma-symbolic.svg			\
	24/gimp-display-filter-lcms-symbolic.svg				\
	24/gimp-display-filter-proof-symbolic.svg			\
	24/gimp-dynamics-symbolic.svg					\
	24/gimp-floating-selection-symbolic.svg				\
	24/gimp-gegl-symbolic.svg					\
	24/gimp-grid-symbolic.svg					\
	24/gimp-histogram-symbolic.svg					\
	24/gimp-image-symbolic.svg					\
	24/gimp-images-symbolic.svg					\
	24/gimp-landscape-symbolic.svg					\
	24/gimp-layer-symbolic.svg					\
	24/gimp-layer-mask-symbolic.svg					\
	24/gimp-layers-symbolic.svg					\
	24/gimp-letter-spacing-symbolic.svg				\
	24/gimp-line-spacing-symbolic.svg				\
	24/gimp-move-to-screen-symbolic.svg				\
	24/gimp-navigation-symbolic.svg					\
	24/gimp-path-symbolic.svg					\
	24/gimp-paths-symbolic.svg					\
	24/gimp-portrait-symbolic.svg					\
	24/gimp-prefs-color-management-symbolic.svg			\
	24/gimp-prefs-controllers-symbolic.svg				\
	24/gimp-prefs-default-comment-symbolic.svg			\
	24/gimp-prefs-default-grid-symbolic.svg				\
	24/gimp-prefs-display-symbolic.svg				\
	24/gimp-prefs-folders-symbolic.svg				\
	24/gimp-prefs-folders-brushes-symbolic.svg			\
	24/gimp-prefs-folders-dynamics-symbolic.svg			\
	24/gimp-prefs-folders-environ-symbolic.svg			\
	24/gimp-prefs-folders-fonts-symbolic.svg				\
	24/gimp-prefs-folders-gradients-symbolic.svg			\
	24/gimp-prefs-folders-icon-themes-symbolic.svg			\
	24/gimp-prefs-folders-interp-symbolic.svg			\
	24/gimp-prefs-folders-modules-symbolic.svg			\
	24/gimp-prefs-folders-mypaint-brushes-symbolic.svg		\
	24/gimp-prefs-folders-palettes-symbolic.svg			\
	24/gimp-prefs-folders-patterns-symbolic.svg			\
	24/gimp-prefs-folders-plug-ins-symbolic.svg			\
	24/gimp-prefs-folders-scripts-symbolic.svg			\
	24/gimp-prefs-folders-themes-symbolic.svg			\
	24/gimp-prefs-folders-tool-plug-ins-symbolic.svg			\
	24/gimp-prefs-folders-tool-presets-symbolic.svg			\
	24/gimp-prefs-folders-tools-symbolic.svg				\
	24/gimp-prefs-help-system-symbolic.svg				\
	24/gimp-prefs-icon-theme-symbolic.svg				\
	24/gimp-prefs-image-title-symbolic.svg				\
	24/gimp-prefs-image-windows-symbolic.svg				\
	24/gimp-prefs-image-windows-appearance-symbolic.svg		\
	24/gimp-prefs-image-windows-snapping-symbolic.svg		\
	24/gimp-prefs-import-export-symbolic.svg				\
	24/gimp-prefs-input-devices-symbolic.svg				\
	24/gimp-prefs-interface-symbolic.svg				\
	24/gimp-prefs-new-image-symbolic.svg				\
	24/gimp-prefs-playground-symbolic.svg				\
	24/gimp-prefs-session-symbolic.svg				\
	24/gimp-prefs-system-resources-symbolic.svg			\
	24/gimp-prefs-theme-symbolic.svg					\
	24/gimp-prefs-toolbox-symbolic.svg				\
	24/gimp-prefs-tool-options-symbolic.svg				\
	24/gimp-prefs-window-management-symbolic.svg			\
	24/gimp-resize-symbolic.svg					\
	24/gimp-sample-point-symbolic.svg				\
	24/gimp-scale-symbolic.svg					\
	24/gimp-selection-symbolic.svg					\
	24/gimp-smartphone-symbolic.svg					\
	24/gimp-symmetry-symbolic.svg					\
	24/gimp-template-symbolic.svg					\
	24/gimp-text-layer-symbolic.svg					\
	24/gimp-tool-airbrush-symbolic.svg				\
	24/gimp-tool-align-symbolic.svg					\
	24/gimp-tool-blur-symbolic.svg					\
	24/gimp-tool-brightness-contrast-symbolic.svg			\
	24/gimp-tool-bucket-fill-symbolic.svg				\
	24/gimp-tool-by-color-select-symbolic.svg			\
	24/gimp-tool-cage-symbolic.svg					\
	24/gimp-tool-clone-symbolic.svg					\
	24/gimp-tool-color-balance-symbolic.svg				\
	24/gimp-tool-color-picker-symbolic.svg				\
	24/gimp-tool-colorize-symbolic.svg				\
	24/gimp-tool-crop-symbolic.svg					\
	24/gimp-tool-curves-symbolic.svg					\
	24/gimp-tool-desaturate-symbolic.svg				\
	24/gimp-tool-dodge-symbolic.svg					\
	24/gimp-tool-eraser-symbolic.svg					\
	24/gimp-tool-ellipse-select-symbolic.svg				\
	24/gimp-tool-exposure-symbolic.svg				\
	24/gimp-tool-flip-symbolic.svg					\
	24/gimp-tool-foreground-select-symbolic.svg			\
	24/gimp-tool-free-select-symbolic.svg				\
	24/gimp-tool-fuzzy-select-symbolic.svg				\
	24/gimp-tool-gradient-symbolic.svg				\
	24/gimp-tool-handle-transform-symbolic.svg			\
	24/gimp-tool-heal-symbolic.svg					\
	24/gimp-tool-hue-saturation-symbolic.svg				\
	24/gimp-tool-ink-symbolic.svg					\
	24/gimp-tool-iscissors-symbolic.svg				\
	24/gimp-tool-levels-symbolic.svg					\
	24/gimp-tool-mypaint-brush-symbolic.svg				\
	24/gimp-tool-measure-symbolic.svg				\
	24/gimp-tool-n-point-deformation-symbolic.svg			\
	24/gimp-tool-offset-symbolic.svg				\
	24/gimp-tool-options-symbolic.svg				\
	24/gimp-tool-paintbrush-symbolic.svg				\
	24/gimp-tool-path-symbolic.svg					\
	24/gimp-tool-pencil-symbolic.svg					\
	24/gimp-tool-perspective-symbolic.svg				\
	24/gimp-tool-perspective-clone-symbolic.svg			\
	24/gimp-tool-posterize-symbolic.svg				\
	24/gimp-tool-preset-symbolic.svg					\
	24/gimp-tool-rect-select-symbolic.svg				\
	24/gimp-tool-rotate-symbolic.svg					\
	24/gimp-tools-symbolic.svg					\
	24/gimp-tool-scale-symbolic.svg					\
	24/gimp-tool-seamless-clone-symbolic.svg				\
	24/gimp-tool-shadows-highlights-symbolic.svg			\
	24/gimp-tool-shear-symbolic.svg					\
	24/gimp-tool-smudge-symbolic.svg					\
	24/gimp-tool-threshold-symbolic.svg				\
	24/gimp-tool-transform-3d-symbolic.svg				\
	24/gimp-tool-unified-transform-symbolic.svg			\
	24/gimp-tool-text-symbolic.svg					\
	24/gimp-tool-warp-symbolic.svg					\
	24/gimp-tool-zoom-symbolic.svg					\
	24/gimp-transparency-symbolic.svg				\
	24/gimp-undo-history-symbolic.svg				\
	24/gimp-user-manual-symbolic.svg					\
	24/gimp-video-symbolic.svg					\
	24/gimp-web-symbolic.svg						\
	24/gimp-wilber-symbolic.svg

icons12_images = \
	12/gimp-attach-symbolic.symbolic.png					\
	12/gimp-close-symbolic.symbolic.png					\
	12/gimp-default-colors-symbolic.symbolic.png				\
	12/gimp-detach-symbolic.symbolic.png					\
	12/gimp-linked-symbolic.symbolic.png					\
	12/gimp-menu-left-symbolic.symbolic.png					\
	12/gimp-menu-right-symbolic.symbolic.png				\
	12/gimp-pivot-center-symbolic.symbolic.png				\
	12/gimp-pivot-east-symbolic.symbolic.png				\
	12/gimp-pivot-north-symbolic.symbolic.png				\
	12/gimp-pivot-north-east-symbolic.symbolic.png				\
	12/gimp-pivot-north-west-symbolic.symbolic.png				\
	12/gimp-pivot-south-symbolic.symbolic.png				\
	12/gimp-pivot-south-east-symbolic.symbolic.png				\
	12/gimp-pivot-south-west-symbolic.symbolic.png				\
	12/gimp-pivot-west-symbolic.symbolic.png				\
	12/gimp-quick-mask-off-symbolic.symbolic.png				\
	12/gimp-quick-mask-on-symbolic.symbolic.png				\
	12/gimp-swap-colors-symbolic.symbolic.png				\
	12/gimp-visible-symbolic.symbolic.png					\
	12/gimp-zoom-follow-window-symbolic.symbolic.png

icons16_images = \
	16/dialog-error-symbolic.symbolic.png					\
	16/dialog-information-symbolic.symbolic.png				\
	16/dialog-question-symbolic.symbolic.png				\
	16/dialog-warning-symbolic.symbolic.png					\
	16/document-new-symbolic.symbolic.png					\
	16/document-open-symbolic.symbolic.png					\
	16/document-open-recent-symbolic.symbolic.png				\
	16/document-print-symbolic.symbolic.png					\
	16/document-revert-symbolic.symbolic.png				\
	16/document-save-symbolic.symbolic.png					\
	16/document-save-as-symbolic.symbolic.png				\
	16/edit-clear-symbolic.symbolic.png					\
	16/edit-copy-symbolic.symbolic.png					\
	16/edit-cut-symbolic.symbolic.png					\
	16/edit-delete-symbolic.symbolic.png					\
	16/edit-paste-symbolic.symbolic.png					\
	16/edit-redo-symbolic.symbolic.png					\
	16/edit-undo-symbolic.symbolic.png					\
	16/folder-symbolic.symbolic.png						\
	16/folder-new-symbolic.symbolic.png					\
	16/go-bottom-symbolic.symbolic.png					\
	16/go-down-symbolic.symbolic.png					\
	16/go-first-symbolic.symbolic.png					\
	16/go-home-symbolic.symbolic.png					\
	16/go-last-symbolic.symbolic.png					\
	16/go-next-symbolic.symbolic.png					\
	16/go-previous-symbolic.symbolic.png					\
	16/go-top-symbolic.symbolic.png						\
	16/go-up-symbolic.symbolic.png						\
	16/help-about-symbolic.symbolic.png					\
	16/list-add-symbolic.symbolic.png					\
	16/list-remove-symbolic.symbolic.png					\
	16/media-floppy-symbolic.symbolic.png					\
	16/media-optical-symbolic.symbolic.png					\
	16/media-playback-pause-symbolic.symbolic.png				\
	16/media-playback-start-symbolic.symbolic.png				\
	16/media-record.symbolic.png						\
	16/media-seek-backward-symbolic.symbolic.png				\
	16/media-skip-backward-symbolic.symbolic.png				\
	16/media-skip-forward-symbolic.symbolic.png				\
	16/object-flip-horizontal-symbolic.symbolic.png				\
	16/object-flip-vertical-symbolic.symbolic.png				\
	16/object-rotate-left-symbolic.symbolic.png				\
	16/object-rotate-right-symbolic.symbolic.png				\
	16/preferences-system-symbolic.symbolic.png				\
	16/process-stop-symbolic.symbolic.png					\
	16/system-run-symbolic.symbolic.png					\
	16/view-fullscreen-symbolic.symbolic.png				\
	16/view-refresh-symbolic.symbolic.png					\
	16/window-close-symbolic.symbolic.png					\
	16/window-new-symbolic.symbolic.png					\
	16/zoom-fit-best-symbolic.symbolic.png					\
	16/zoom-in-symbolic.symbolic.png					\
	16/zoom-original-symbolic.symbolic.png					\
	16/zoom-out-symbolic.symbolic.png					\
	\
	16/gtk-cancel-symbolic.symbolic.png					\
	16/gtk-edit-symbolic.symbolic.png					\
	16/gtk-no-symbolic.symbolic.png						\
	16/gtk-ok-symbolic.symbolic.png						\
	16/gtk-select-color-symbolic.symbolic.png				\
	16/gtk-select-font-symbolic.symbolic.png				\
	16/gtk-yes-symbolic.symbolic.png					\
	\
	16/gimp-anchor-symbolic.symbolic.png					\
	16/gimp-business-card-symbolic.symbolic.png				\
	16/gimp-cap-butt-symbolic.symbolic.png					\
	16/gimp-cap-round-symbolic.symbolic.png					\
	16/gimp-cap-square-symbolic.symbolic.png				\
	16/gimp-center-symbolic.symbolic.png					\
	16/gimp-channel-alpha-symbolic.symbolic.png				\
	16/gimp-channel-blue-symbolic.symbolic.png				\
	16/gimp-channel-gray-symbolic.symbolic.png				\
	16/gimp-channel-green-symbolic.symbolic.png				\
	16/gimp-channel-indexed-symbolic.symbolic.png				\
	16/gimp-channel-red-symbolic.symbolic.png				\
	16/gimp-channel-symbolic.symbolic.png					\
	16/gimp-channels-symbolic.symbolic.png					\
	16/gimp-char-picker-symbolic.symbolic.png				\
	16/gimp-clipboard-symbolic.symbolic.png					\
	16/gimp-close-all-symbolic.symbolic.png					\
	16/gimp-color-pick-from-screen-symbolic.symbolic.png			\
	16/gimp-color-cmyk-symbolic.symbolic.png				\
	16/gimp-tool-color-temperature-symbolic.symbolic.png			\
	16/gimp-color-triangle-symbolic.symbolic.png				\
	16/gimp-color-water-symbolic.symbolic.png				\
	16/gimp-colormap-symbolic.symbolic.png					\
	16/gimp-color-space-linear-symbolic.symbolic.png			\
	16/gimp-color-space-non-linear-symbolic.symbolic.png			\
	16/gimp-color-space-perceptual-symbolic.symbolic.png			\
	16/gimp-controller-keyboard-symbolic.symbolic.png			\
	16/gimp-controller-linux-input-symbolic.symbolic.png			\
	16/gimp-controller-midi-symbolic.symbolic.png				\
	16/gimp-controller-wheel-symbolic.symbolic.png				\
	16/gimp-controller-symbolic.symbolic.png				\
	16/gimp-convert-grayscale-symbolic.symbolic.png				\
	16/gimp-convert-indexed-symbolic.symbolic.png				\
	16/gimp-convert-rgb-symbolic.symbolic.png				\
	16/gimp-cursor-symbolic.symbolic.png					\
	16/gimp-curve-free-symbolic.symbolic.png				\
	16/gimp-curve-point-corner-symbolic.symbolic.png			\
	16/gimp-curve-point-smooth-symbolic.symbolic.png			\
	16/gimp-curve-smooth-symbolic.symbolic.png				\
	16/gimp-dashboard-symbolic.symbolic.png					\
	16/gimp-device-status-symbolic.symbolic.png				\
	16/gimp-display-symbolic.symbolic.png					\
	16/gimp-display-filter-clip-warning-symbolic.symbolic.png		\
	16/gimp-display-filter-colorblind-symbolic.symbolic.png			\
	16/gimp-display-filter-contrast-symbolic.symbolic.png			\
	16/gimp-display-filter-gamma-symbolic.symbolic.png			\
	16/gimp-display-filter-lcms-symbolic.symbolic.png			\
	16/gimp-display-filter-proof-symbolic.symbolic.png			\
	16/gimp-display-filter-symbolic.symbolic.png				\
	16/gimp-duplicate-symbolic.symbolic.png					\
	16/gimp-dynamics-symbolic.symbolic.png					\
	16/gimp-file-manager-symbolic.symbolic.png				\
	16/gimp-floating-selection-symbolic.symbolic.png			\
	16/gimp-gegl-symbolic.symbolic.png					\
	16/gimp-gradient-bilinear-symbolic.symbolic.png				\
	16/gimp-gradient-conical-asymmetric-symbolic.symbolic.png		\
	16/gimp-gradient-conical-symmetric-symbolic.symbolic.png		\
	16/gimp-gradient-linear-symbolic.symbolic.png				\
	16/gimp-gradient-radial-symbolic.symbolic.png				\
	16/gimp-gradient-shapeburst-angular-symbolic.symbolic.png		\
	16/gimp-gradient-shapeburst-dimpled-symbolic.symbolic.png		\
	16/gimp-gradient-shapeburst-spherical-symbolic.symbolic.png		\
	16/gimp-gradient-spiral-anticlockwise-symbolic.symbolic.png		\
	16/gimp-gradient-spiral-clockwise-symbolic.symbolic.png			\
	16/gimp-gradient-square-symbolic.symbolic.png				\
	16/gimp-grid-symbolic.symbolic.png					\
	16/gimp-group-layer-symbolic.symbolic.png				\
	16/gimp-histogram-linear-symbolic.symbolic.png				\
	16/gimp-histogram-logarithmic-symbolic.symbolic.png			\
	16/gimp-histogram-symbolic.symbolic.png					\
	16/gimp-image-symbolic.symbolic.png					\
	16/gimp-images-symbolic.symbolic.png					\
	16/gimp-image-open-symbolic.symbolic.png				\
	16/gimp-image-reload-symbolic.symbolic.png				\
	16/gimp-input-device-symbolic.symbolic.png				\
	16/gimp-invert-symbolic.symbolic.png					\
	16/gimp-join-bevel-symbolic.symbolic.png				\
	16/gimp-join-miter-symbolic.symbolic.png				\
	16/gimp-join-round-symbolic.symbolic.png				\
	16/gimp-landscape-symbolic.symbolic.png					\
	16/gimp-layer-mask-symbolic.symbolic.png				\
	16/gimp-layer-to-imagesize-symbolic.symbolic.png			\
	16/gimp-layer-symbolic.symbolic.png					\
	16/gimp-layers-symbolic.symbolic.png					\
	16/gimp-list-symbolic.symbolic.png					\
	16/gimp-marker-symbolic.symbolic.png					\
	16/gimp-merge-down-symbolic.symbolic.png				\
	16/gimp-move-to-screen-symbolic.symbolic.png				\
	16/gimp-navigation-symbolic.symbolic.png				\
	16/gimp-paste-as-new-symbolic.symbolic.png				\
	16/gimp-paste-into-symbolic.symbolic.png				\
	16/gimp-path-stroke-symbolic.symbolic.png				\
	16/gimp-path-symbolic.symbolic.png					\
	16/gimp-paths-symbolic.symbolic.png					\
	16/gimp-pattern-symbolic.symbolic.png					\
	16/gimp-plugin-symbolic.symbolic.png					\
	16/gimp-portrait-symbolic.symbolic.png					\
	16/gimp-prefs-folders-brushes-symbolic.symbolic.png			\
	16/gimp-prefs-folders-dynamics-symbolic.symbolic.png			\
	16/gimp-prefs-folders-environ-symbolic.symbolic.png			\
	16/gimp-prefs-folders-fonts-symbolic.symbolic.png			\
	16/gimp-prefs-folders-gradients-symbolic.symbolic.png			\
	16/gimp-prefs-folders-icon-themes-symbolic.symbolic.png			\
	16/gimp-prefs-folders-interp-symbolic.symbolic.png			\
	16/gimp-prefs-folders-modules-symbolic.symbolic.png			\
	16/gimp-prefs-folders-mypaint-brushes-symbolic.symbolic.png		\
	16/gimp-prefs-folders-palettes-symbolic.symbolic.png			\
	16/gimp-prefs-folders-patterns-symbolic.symbolic.png			\
	16/gimp-prefs-folders-plug-ins-symbolic.symbolic.png			\
	16/gimp-prefs-folders-scripts-symbolic.symbolic.png			\
	16/gimp-prefs-folders-themes-symbolic.symbolic.png			\
	16/gimp-prefs-folders-tool-plug-ins-symbolic.symbolic.png		\
	16/gimp-prefs-folders-tool-presets-symbolic.symbolic.png		\
	16/gimp-prefs-folders-tools-symbolic.symbolic.png			\
	16/gimp-prefs-icon-theme-symbolic.symbolic.png				\
	16/gimp-prefs-image-windows-symbolic.symbolic.png			\
	16/gimp-prefs-import-export-symbolic.symbolic.png			\
	16/gimp-prefs-interface-symbolic.symbolic.png				\
	16/gimp-prefs-theme-symbolic.symbolic.png				\
	16/gimp-prefs-toolbox-symbolic.symbolic.png				\
	16/gimp-prefs-window-management-symbolic.symbolic.png			\
	16/gimp-reset-symbolic.symbolic.png					\
	16/gimp-reshow-filter-symbolic.symbolic.png				\
	16/gimp-resize-symbolic.symbolic.png					\
	16/gimp-rotate-180-symbolic.symbolic.png				\
	16/gimp-sample-point-symbolic.symbolic.png				\
	16/gimp-scale-symbolic.symbolic.png					\
	16/gimp-selection-add-symbolic.symbolic.png				\
	16/gimp-selection-all-symbolic.symbolic.png				\
	16/gimp-selection-border-symbolic.symbolic.png				\
	16/gimp-selection-grow-symbolic.symbolic.png				\
	16/gimp-selection-intersect-symbolic.symbolic.png			\
	16/gimp-selection-none-symbolic.symbolic.png				\
	16/gimp-selection-replace-symbolic.symbolic.png				\
	16/gimp-selection-shrink-symbolic.symbolic.png				\
	16/gimp-selection-stroke-symbolic.symbolic.png				\
	16/gimp-selection-subtract-symbolic.symbolic.png			\
	16/gimp-selection-to-channel-symbolic.symbolic.png			\
	16/gimp-selection-to-path-symbolic.symbolic.png				\
	16/gimp-selection-symbolic.symbolic.png					\
	16/gimp-shape-circle-symbolic.symbolic.png				\
	16/gimp-shape-diamond-symbolic.symbolic.png				\
	16/gimp-shape-square-symbolic.symbolic.png				\
	16/gimp-shred-symbolic.symbolic.png					\
	16/gimp-smartphone-symbolic.symbolic.png				\
	16/gimp-symmetry-symbolic.symbolic.png					\
	16/gimp-template-symbolic.symbolic.png					\
	16/gimp-text-layer-symbolic.symbolic.png				\
	16/gimp-toilet-paper-symbolic.symbolic.png				\
	16/gimp-tool-airbrush-symbolic.symbolic.png				\
	16/gimp-tool-align-symbolic.symbolic.png				\
	16/gimp-tool-blur-symbolic.symbolic.png					\
	16/gimp-tool-brightness-contrast-symbolic.symbolic.png			\
	16/gimp-tool-bucket-fill-symbolic.symbolic.png				\
	16/gimp-tool-by-color-select-symbolic.symbolic.png			\
	16/gimp-tool-cage-symbolic.symbolic.png					\
	16/gimp-tool-clone-symbolic.symbolic.png				\
	16/gimp-tool-color-balance-symbolic.symbolic.png			\
	16/gimp-tool-color-picker-symbolic.symbolic.png				\
	16/gimp-tool-colorize-symbolic.symbolic.png				\
	16/gimp-tool-crop-symbolic.symbolic.png					\
	16/gimp-tool-curves-symbolic.symbolic.png				\
	16/gimp-tool-desaturate-symbolic.symbolic.png				\
	16/gimp-tool-dodge-symbolic.symbolic.png				\
	16/gimp-tool-ellipse-select-symbolic.symbolic.png			\
	16/gimp-tool-eraser-symbolic.symbolic.png				\
	16/gimp-tool-exposure-symbolic.symbolic.png				\
	16/gimp-tool-flip-symbolic.symbolic.png					\
	16/gimp-tool-foreground-select-symbolic.symbolic.png			\
	16/gimp-tool-free-select-symbolic.symbolic.png				\
	16/gimp-tool-fuzzy-select-symbolic.symbolic.png				\
	16/gimp-tool-gradient-symbolic.symbolic.png				\
	16/gimp-tool-handle-transform-symbolic.symbolic.png			\
	16/gimp-tool-heal-symbolic.symbolic.png					\
	16/gimp-tool-hue-saturation-symbolic.symbolic.png			\
	16/gimp-tool-ink-symbolic.symbolic.png					\
	16/gimp-tool-iscissors-symbolic.symbolic.png				\
	16/gimp-tool-levels-symbolic.symbolic.png				\
	16/gimp-tool-measure-symbolic.symbolic.png				\
	16/gimp-tool-move-symbolic.symbolic.png					\
	16/gimp-tool-mypaint-brush-symbolic.symbolic.png			\
	16/gimp-tool-n-point-deformation-symbolic.symbolic.png			\
	16/gimp-tool-offset-symbolic.symbolic.png				\
	16/gimp-tool-options-symbolic.symbolic.png				\
	16/gimp-tool-paintbrush-symbolic.symbolic.png				\
	16/gimp-tool-path-symbolic.symbolic.png					\
	16/gimp-tool-pencil-symbolic.symbolic.png				\
	16/gimp-tool-perspective-clone-symbolic.symbolic.png			\
	16/gimp-tool-perspective-symbolic.symbolic.png				\
	16/gimp-tool-posterize-symbolic.symbolic.png				\
	16/gimp-tool-preset-symbolic.symbolic.png				\
	16/gimp-tool-rect-select-symbolic.symbolic.png				\
	16/gimp-tool-rotate-symbolic.symbolic.png				\
	16/gimp-tool-scale-symbolic.symbolic.png				\
	16/gimp-tool-seamless-clone-symbolic.symbolic.png			\
	16/gimp-tool-shadows-highlights-symbolic.symbolic.png			\
	16/gimp-tool-shear-symbolic.symbolic.png				\
	16/gimp-tool-smudge-symbolic.symbolic.png				\
	16/gimp-tool-text-symbolic.symbolic.png					\
	16/gimp-tool-threshold-symbolic.symbolic.png				\
	16/gimp-tool-transform-3d-symbolic.symbolic.png				\
	16/gimp-tool-unified-transform-symbolic.symbolic.png			\
	16/gimp-tool-warp-symbolic.symbolic.png					\
	16/gimp-tool-zoom-symbolic.symbolic.png					\
	16/gimp-tools-symbolic.symbolic.png					\
	16/gimp-transform-3d-camera-symbolic.symbolic.png			\
	16/gimp-transform-3d-move-symbolic.symbolic.png				\
	16/gimp-transform-3d-rotate-symbolic.symbolic.png			\
	16/gimp-transparency-symbolic.symbolic.png				\
	16/gimp-undo-history-symbolic.symbolic.png				\
	16/gimp-user-manual-symbolic.symbolic.png				\
	16/gimp-video-symbolic.symbolic.png					\
	16/gimp-web-symbolic.symbolic.png					\
	16/gimp-wilber-symbolic.symbolic.png

icons18_images = \
	18/gimp-color-picker-black-symbolic.symbolic.png			\
	18/gimp-color-picker-gray-symbolic.symbolic.png				\
	18/gimp-color-picker-white-symbolic.symbolic.png

icons20_images = \
	20/gimp-linked-symbolic.symbolic.png					\
	20/gimp-visible-symbolic.symbolic.png

icons22_images = \
	22/folder-symbolic.symbolic.png						\
	22/format-indent-more-symbolic.symbolic.png				\
	22/format-justify-center-symbolic.symbolic.png				\
	22/format-justify-fill-symbolic.symbolic.png				\
	22/format-justify-left-symbolic.symbolic.png				\
	22/format-justify-right-symbolic.symbolic.png				\
	\
	22/gimp-char-picker-symbolic.symbolic.png				\
	22/gimp-dynamics-symbolic.symbolic.png					\
	22/gimp-histogram-symbolic.symbolic.png					\
	22/gimp-input-device-symbolic.symbolic.png				\
	22/gimp-landscape-symbolic.symbolic.png					\
	22/gimp-letter-spacing-symbolic.symbolic.png				\
	22/gimp-line-spacing-symbolic.symbolic.png				\
	22/gimp-path-symbolic.symbolic.png					\
	22/gimp-paths-symbolic.symbolic.png					\
	22/gimp-portrait-symbolic.symbolic.png					\
	22/gimp-prefs-color-management-symbolic.symbolic.png			\
	22/gimp-prefs-controllers-symbolic.symbolic.png				\
	22/gimp-prefs-default-grid-symbolic.symbolic.png			\
	22/gimp-prefs-display-symbolic.symbolic.png				\
	22/gimp-prefs-folders-symbolic.symbolic.png				\
	22/gimp-prefs-folders-brushes-symbolic.symbolic.png			\
	22/gimp-prefs-folders-dynamics-symbolic.symbolic.png			\
	22/gimp-prefs-folders-environ-symbolic.symbolic.png			\
	22/gimp-prefs-folders-fonts-symbolic.symbolic.png			\
	22/gimp-prefs-folders-gradients-symbolic.symbolic.png			\
	22/gimp-prefs-folders-icon-themes-symbolic.symbolic.png			\
	22/gimp-prefs-folders-interp-symbolic.symbolic.png			\
	22/gimp-prefs-folders-modules-symbolic.symbolic.png			\
	22/gimp-prefs-folders-mypaint-brushes-symbolic.symbolic.png		\
	22/gimp-prefs-folders-palettes-symbolic.symbolic.png			\
	22/gimp-prefs-folders-patterns-symbolic.symbolic.png			\
	22/gimp-prefs-folders-plug-ins-symbolic.symbolic.png			\
	22/gimp-prefs-folders-scripts-symbolic.symbolic.png			\
	22/gimp-prefs-folders-themes-symbolic.symbolic.png			\
	22/gimp-prefs-folders-tool-plug-ins-symbolic.symbolic.png		\
	22/gimp-prefs-folders-tool-presets-symbolic.symbolic.png		\
	22/gimp-prefs-folders-tools-symbolic.symbolic.png			\
	22/gimp-prefs-help-system-symbolic.symbolic.png				\
	22/gimp-prefs-icon-theme-symbolic.symbolic.png				\
	22/gimp-prefs-image-title-symbolic.symbolic.png				\
	22/gimp-prefs-image-windows-symbolic.symbolic.png			\
	22/gimp-prefs-image-windows-appearance-symbolic.symbolic.png		\
	22/gimp-prefs-image-windows-snapping-symbolic.symbolic.png		\
	22/gimp-prefs-import-export-symbolic.symbolic.png			\
	22/gimp-prefs-input-devices-symbolic.symbolic.png			\
	22/gimp-prefs-interface-symbolic.symbolic.png				\
	22/gimp-prefs-new-image-symbolic.symbolic.png				\
	22/gimp-prefs-playground-symbolic.symbolic.png				\
	22/gimp-prefs-session-symbolic.symbolic.png				\
	22/gimp-prefs-system-resources-symbolic.symbolic.png			\
	22/gimp-prefs-theme-symbolic.symbolic.png				\
	22/gimp-prefs-tool-options-symbolic.symbolic.png			\
	22/gimp-prefs-toolbox-symbolic.symbolic.png				\
	22/gimp-prefs-window-management-symbolic.symbolic.png			\
	22/gimp-tool-preset-symbolic.symbolic.png				\
	22/gimp-wilber-symbolic.symbolic.png

icons24_images = \
	24/dialog-error-symbolic.symbolic.png					\
	24/dialog-information-symbolic.symbolic.png				\
	24/dialog-question-symbolic.symbolic.png				\
	24/dialog-warning-symbolic.symbolic.png					\
	24/document-print-symbolic.symbolic.png					\
	24/format-text-direction-ltr-symbolic.symbolic.png			\
	24/format-text-direction-rtl-symbolic.symbolic.png			\
	24/media-floppy-symbolic.symbolic.png					\
	24/media-optical-symbolic.symbolic.png 					\
	\
	24/gtk-select-color-symbolic.symbolic.png				\
	\
	24/gimp-attach-symbolic.symbolic.png					\
	24/gimp-business-card-symbolic.symbolic.png				\
	24/gimp-center-symbolic.symbolic.png					\
	24/gimp-channel-alpha-symbolic.symbolic.png				\
	24/gimp-channel-blue-symbolic.symbolic.png				\
	24/gimp-channel-gray-symbolic.symbolic.png				\
	24/gimp-channel-green-symbolic.symbolic.png				\
	24/gimp-channel-indexed-symbolic.symbolic.png				\
	24/gimp-channel-red-symbolic.symbolic.png				\
	24/gimp-channel-symbolic.symbolic.png					\
	24/gimp-channels-symbolic.symbolic.png					\
	24/gimp-colormap-symbolic.symbolic.png					\
	24/gimp-color-space-linear-symbolic.symbolic.png			\
	24/gimp-color-space-non-linear-symbolic.symbolic.png			\
	24/gimp-color-space-perceptual-symbolic.symbolic.png			\
	24/gimp-tool-color-temperature-symbolic.symbolic.png			\
	24/gimp-controller-keyboard-symbolic.symbolic.png			\
	24/gimp-controller-linux-input-symbolic.symbolic.png			\
	24/gimp-controller-midi-symbolic.symbolic.png				\
	24/gimp-controller-wheel-symbolic.symbolic.png				\
	24/gimp-controller-symbolic.symbolic.png				\
	24/gimp-cursor-symbolic.symbolic.png					\
	24/gimp-dashboard-symbolic.symbolic.png					\
	24/gimp-detach-symbolic.symbolic.png					\
	24/gimp-device-status-symbolic.symbolic.png				\
	24/gimp-display-symbolic.symbolic.png					\
	24/gimp-display-filter-clip-warning-symbolic.symbolic.png		\
	24/gimp-display-filter-colorblind-symbolic.symbolic.png			\
	24/gimp-display-filter-contrast-symbolic.symbolic.png			\
	24/gimp-display-filter-gamma-symbolic.symbolic.png			\
	24/gimp-display-filter-lcms-symbolic.symbolic.png			\
	24/gimp-display-filter-proof-symbolic.symbolic.png			\
	24/gimp-display-filter-symbolic.symbolic.png				\
	24/gimp-floating-selection-symbolic.symbolic.png			\
	24/gimp-gegl-symbolic.symbolic.png					\
	24/gimp-grid-symbolic.symbolic.png					\
	24/gimp-gravity-east-symbolic.symbolic.png				\
	24/gimp-gravity-north-east-symbolic.symbolic.png			\
	24/gimp-gravity-north-west-symbolic.symbolic.png			\
	24/gimp-gravity-north-symbolic.symbolic.png				\
	24/gimp-gravity-south-east-symbolic.symbolic.png			\
	24/gimp-gravity-south-west-symbolic.symbolic.png			\
	24/gimp-gravity-south-symbolic.symbolic.png				\
	24/gimp-gravity-west-symbolic.symbolic.png				\
	24/gimp-hcenter-symbolic.symbolic.png					\
	24/gimp-hchain-broken-symbolic.symbolic.png				\
	24/gimp-hchain-symbolic.symbolic.png					\
	24/gimp-hfill-symbolic.symbolic.png					\
	24/gimp-image-symbolic.symbolic.png					\
	24/gimp-images-symbolic.symbolic.png					\
	24/gimp-layer-mask-symbolic.symbolic.png				\
	24/gimp-layer-symbolic.symbolic.png					\
	24/gimp-layers-symbolic.symbolic.png					\
	24/gimp-move-to-screen-symbolic.symbolic.png				\
	24/gimp-navigation-symbolic.symbolic.png				\
	24/gimp-resize-symbolic.symbolic.png					\
	24/gimp-sample-point-symbolic.symbolic.png				\
	24/gimp-scale-symbolic.symbolic.png					\
	24/gimp-selection-symbolic.symbolic.png					\
	24/gimp-smartphone-symbolic.symbolic.png				\
	24/gimp-symmetry-symbolic.symbolic.png					\
	24/gimp-template-symbolic.symbolic.png					\
	24/gimp-text-dir-ttb-rtl-symbolic.symbolic.png				\
	24/gimp-text-dir-ttb-rtl-upright-symbolic.symbolic.png			\
	24/gimp-text-dir-ttb-ltr-symbolic.symbolic.png				\
	24/gimp-text-dir-ttb-ltr-upright-symbolic.symbolic.png			\
	24/gimp-text-layer-symbolic.symbolic.png				\
	24/gimp-toilet-paper-symbolic.symbolic.png				\
	24/gimp-tool-airbrush-symbolic.symbolic.png				\
	24/gimp-tool-align-symbolic.symbolic.png				\
	24/gimp-tool-blur-symbolic.symbolic.png					\
	24/gimp-tool-brightness-contrast-symbolic.symbolic.png			\
	24/gimp-tool-bucket-fill-symbolic.symbolic.png				\
	24/gimp-tool-by-color-select-symbolic.symbolic.png			\
	24/gimp-tool-cage-symbolic.symbolic.png					\
	24/gimp-tool-clone-symbolic.symbolic.png				\
	24/gimp-tool-color-balance-symbolic.symbolic.png			\
	24/gimp-tool-color-picker-symbolic.symbolic.png				\
	24/gimp-tool-colorize-symbolic.symbolic.png				\
	24/gimp-tool-crop-symbolic.symbolic.png					\
	24/gimp-tool-curves-symbolic.symbolic.png				\
	24/gimp-tool-desaturate-symbolic.symbolic.png				\
	24/gimp-tool-dodge-symbolic.symbolic.png				\
	24/gimp-tool-ellipse-select-symbolic.symbolic.png			\
	24/gimp-tool-eraser-symbolic.symbolic.png				\
	24/gimp-tool-exposure-symbolic.symbolic.png				\
	24/gimp-tool-flip-symbolic.symbolic.png					\
	24/gimp-tool-foreground-select-symbolic.symbolic.png			\
	24/gimp-tool-free-select-symbolic.symbolic.png				\
	24/gimp-tool-fuzzy-select-symbolic.symbolic.png				\
	24/gimp-tool-gradient-symbolic.symbolic.png				\
	24/gimp-tool-handle-transform-symbolic.symbolic.png			\
	24/gimp-tool-heal-symbolic.symbolic.png					\
	24/gimp-tool-hue-saturation-symbolic.symbolic.png			\
	24/gimp-tool-ink-symbolic.symbolic.png					\
	24/gimp-tool-iscissors-symbolic.symbolic.png				\
	24/gimp-tool-levels-symbolic.symbolic.png				\
	24/gimp-tool-measure-symbolic.symbolic.png				\
	24/gimp-tool-move-symbolic.symbolic.png					\
	24/gimp-tool-mypaint-brush-symbolic.symbolic.png			\
	24/gimp-tool-n-point-deformation-symbolic.symbolic.png			\
	24/gimp-tool-offset-symbolic.symbolic.png				\
	24/gimp-tool-paintbrush-symbolic.symbolic.png				\
	24/gimp-tool-path-symbolic.symbolic.png					\
	24/gimp-tool-pencil-symbolic.symbolic.png				\
	24/gimp-tool-perspective-clone-symbolic.symbolic.png			\
	24/gimp-tool-perspective-symbolic.symbolic.png				\
	24/gimp-tool-preset-symbolic.symbolic.png				\
	24/gimp-tool-posterize-symbolic.symbolic.png				\
	24/gimp-tool-rect-select-symbolic.symbolic.png				\
	24/gimp-tool-rotate-symbolic.symbolic.png				\
	24/gimp-tool-scale-symbolic.symbolic.png				\
	24/gimp-tool-seamless-clone-symbolic.symbolic.png			\
	24/gimp-tool-shadows-highlights-symbolic.symbolic.png			\
	24/gimp-tool-shear-symbolic.symbolic.png				\
	24/gimp-tool-smudge-symbolic.symbolic.png				\
	24/gimp-tool-text-symbolic.symbolic.png					\
	24/gimp-tool-threshold-symbolic.symbolic.png				\
	24/gimp-tool-transform-3d-symbolic.symbolic.png				\
	24/gimp-tool-unified-transform-symbolic.symbolic.png			\
	24/gimp-tool-warp-symbolic.symbolic.png					\
	24/gimp-tool-zoom-symbolic.symbolic.png					\
	24/gimp-tool-options-symbolic.symbolic.png				\
	24/gimp-tools-symbolic.symbolic.png					\
	24/gimp-transparency-symbolic.symbolic.png				\
	24/gimp-undo-history-symbolic.symbolic.png				\
	24/gimp-user-manual-symbolic.symbolic.png				\
	24/gimp-vcenter-symbolic.symbolic.png					\
	24/gimp-vchain-broken-symbolic.symbolic.png				\
	24/gimp-vchain-symbolic.symbolic.png					\
	24/gimp-vfill-symbolic.symbolic.png					\
	24/gimp-video-symbolic.symbolic.png					\
	24/gimp-web-symbolic.symbolic.png

icons32_images = \
	32/gimp-channel-alpha-symbolic.symbolic.png				\
	32/gimp-channel-blue-symbolic.symbolic.png				\
	32/gimp-channel-gray-symbolic.symbolic.png				\
	32/gimp-channel-green-symbolic.symbolic.png				\
	32/gimp-channel-indexed-symbolic.symbolic.png				\
	32/gimp-channel-red-symbolic.symbolic.png				\
	32/gimp-channel-symbolic.symbolic.png					\
	32/gimp-floating-selection-symbolic.symbolic.png			\
	32/gimp-image-symbolic.symbolic.png					\
	32/gimp-layer-mask-symbolic.symbolic.png				\
	32/gimp-layer-symbolic.symbolic.png					\
	32/gimp-text-layer-symbolic.symbolic.png				\
	32/gimp-user-manual-symbolic.symbolic.png				\
	32/gimp-wilber-symbolic.symbolic.png

icons48_images = \
	48/folder-symbolic.symbolic.png						\
	\
	48/gimp-channel-alpha-symbolic.symbolic.png				\
	48/gimp-channel-blue-symbolic.symbolic.png				\
	48/gimp-channel-gray-symbolic.symbolic.png				\
	48/gimp-channel-green-symbolic.symbolic.png				\
	48/gimp-channel-indexed-symbolic.symbolic.png				\
	48/gimp-channel-red-symbolic.symbolic.png				\
	48/gimp-channel-symbolic.symbolic.png					\
	48/gimp-floating-selection-symbolic.symbolic.png			\
	48/gimp-image-symbolic.symbolic.png					\
	48/gimp-layer-mask-symbolic.symbolic.png				\
	48/gimp-layer-symbolic.symbolic.png					\
	48/gimp-prefs-color-management-symbolic.symbolic.png			\
	48/gimp-prefs-controllers-symbolic.symbolic.png				\
	48/gimp-prefs-default-comment-symbolic.symbolic.png			\
	48/gimp-prefs-default-grid-symbolic.symbolic.png			\
	48/gimp-prefs-display-symbolic.symbolic.png				\
	48/gimp-prefs-folders-symbolic.symbolic.png				\
	48/gimp-prefs-folders-brushes-symbolic.symbolic.png			\
	48/gimp-prefs-folders-dynamics-symbolic.symbolic.png			\
	48/gimp-prefs-folders-environ-symbolic.symbolic.png			\
	48/gimp-prefs-folders-fonts-symbolic.symbolic.png			\
	48/gimp-prefs-folders-gradients-symbolic.symbolic.png			\
	48/gimp-prefs-folders-icon-themes-symbolic.symbolic.png			\
	48/gimp-prefs-folders-interp-symbolic.symbolic.png			\
	48/gimp-prefs-folders-modules-symbolic.symbolic.png			\
	48/gimp-prefs-folders-mypaint-brushes-symbolic.symbolic.png		\
	48/gimp-prefs-folders-palettes-symbolic.symbolic.png			\
	48/gimp-prefs-folders-patterns-symbolic.symbolic.png			\
	48/gimp-prefs-folders-plug-ins-symbolic.symbolic.png			\
	48/gimp-prefs-folders-scripts-symbolic.symbolic.png			\
	48/gimp-prefs-folders-themes-symbolic.symbolic.png			\
	48/gimp-prefs-folders-tool-plug-ins-symbolic.symbolic.png		\
	48/gimp-prefs-folders-tool-presets-symbolic.symbolic.png		\
	48/gimp-prefs-folders-tools-symbolic.symbolic.png			\
	48/gimp-prefs-help-system-symbolic.symbolic.png				\
	48/gimp-prefs-icon-theme-symbolic.symbolic.png				\
	48/gimp-prefs-image-title-symbolic.symbolic.png				\
	48/gimp-prefs-image-windows-symbolic.symbolic.png			\
	48/gimp-prefs-image-windows-appearance-symbolic.symbolic.png		\
	48/gimp-prefs-image-windows-snapping-symbolic.symbolic.png		\
	48/gimp-prefs-import-export-symbolic.symbolic.png			\
	48/gimp-prefs-input-devices-symbolic.symbolic.png			\
	48/gimp-prefs-interface-symbolic.symbolic.png				\
	48/gimp-prefs-new-image-symbolic.symbolic.png				\
	48/gimp-prefs-playground-symbolic.symbolic.png				\
	48/gimp-prefs-session-symbolic.symbolic.png				\
	48/gimp-prefs-system-resources-symbolic.symbolic.png			\
	48/gimp-prefs-theme-symbolic.symbolic.png				\
	48/gimp-prefs-tool-options-symbolic.symbolic.png			\
	48/gimp-prefs-toolbox-symbolic.symbolic.png				\
	48/gimp-prefs-window-management-symbolic.symbolic.png			\
	48/gimp-text-layer-symbolic.symbolic.png				\
	48/gimp-wilber-symbolic.symbolic.png

icons64_images = \
	64/gimp-frame.png							\
	64/gimp-texture.png							\
	64/gimp-user-manual-symbolic.symbolic.png				\
	64/gimp-wilber-eek-symbolic.symbolic.png				\
	64/gimp-wilber-symbolic.symbolic.png					\
	64/gimp-wilber-outline-symbolic.symbolic.png

icons64_system_images = \
	64/dialog-error-symbolic.symbolic.png					\
	64/dialog-information-symbolic.symbolic.png				\
	64/dialog-question-symbolic.symbolic.png				\
	64/dialog-warning-symbolic.symbolic.png

icons96_images = \
	96/gimp-wilber-symbolic.symbolic.png					\
	96/gimp-wilber-outline-symbolic.symbolic.png

icons128_images = 								\
	128/folder-symbolic.symbolic.png					\
	128/gimp-wilber-symbolic.symbolic.png					\
	128/gimp-wilber-outline-symbolic.symbolic.png

icons192_images = \
	192/gimp-wilber-symbolic.symbolic.png					\
	192/gimp-wilber-outline-symbolic.symbolic.png

icons256_images = \
	256/folder-symbolic.symbolic.png					\
	256/gimp-wilber-symbolic.symbolic.png					\
	256/gimp-wilber-outline-symbolic.symbolic.png

if ENABLE_VECTOR_ICONS
icons24dir  = $(iconsdir)/24x24/apps
icons64dir  = $(iconsdir)/64x64/apps
scalabledir = $(iconsdir)/scalable/apps

icons64_DATA = \
	$(icons64_system_images)						\
	64/gimp-frame.png							\
	64/gimp-texture.png

else
icons12dir  = $(iconsdir)/12x12/apps
icons16dir  = $(iconsdir)/16x16/apps
icons18dir  = $(iconsdir)/18x18/apps
icons20dir  = $(iconsdir)/20x20/apps
icons22dir  = $(iconsdir)/22x22/apps
icons24dir  = $(iconsdir)/24x24/apps
icons32dir  = $(iconsdir)/32x32/apps
icons48dir  = $(iconsdir)/48x48/apps
icons64dir  = $(iconsdir)/64x64/apps
icons96dir  = $(iconsdir)/96x96/apps
icons128dir = $(iconsdir)/128x128/apps
icons192dir = $(iconsdir)/192x192/apps
icons256dir = $(iconsdir)/256x256/apps

icons12_DATA = \
	$(icons12_images)

icons16_DATA = \
	$(icons16_images)

icons18_DATA = \
	$(icons18_images)

icons20_DATA = \
	$(icons20_images)

icons22_DATA = \
	$(icons22_images)

icons24_DATA = \
	$(icons24_images)

icons32_DATA = \
	$(icons32_images)

icons48_DATA = \
	$(icons48_images)

icons64_DATA = \
	$(icons64_images) \
	$(icons64_system_images)

icons96_DATA = \
	$(icons96_images)

icons128_DATA = \
	$(icons128_images)

icons192_DATA = \
	$(icons192_images)

icons256_DATA = \
	$(icons256_images)
endif
