/* THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT */

typedef void (*GimpCompositeFunction)(GimpCompositeContext *);
typedef GimpCompositeFunction (*GimpCompositeFunctionTable[GIMP_COMPOSITE_N][GIMP_PIXELFORMAT_N][GIMP_PIXELFORMAT_N][GIMP_PIXELFORMAT_N]);
