/* Test for constants in our Gobject Introspection API to make sure they are
 * available.
 */

static GimpValueArray *
gimp_c_test_run (GimpProcedure        *procedure,
                 GimpRunMode           run_mode,
                 GimpImage            *image,
                 GimpDrawable        **drawables,
                 GimpProcedureConfig  *config,
                 gpointer              run_data)
{
/* The compiler could detect that comparison would always be true and always
 * return a TRUE value. But then: it would already fail compiling if the
 * constant is missing.
 */
#define GIMP_CONST_TEST(testname, test) \
  GIMP_TEST_START(testname); GIMP_TEST_END(test == test);

/* The actual test here isn't that important, we just need to know it exists. */
#define GIMP_CONST_STRING_TEST(testname, test) \
  GIMP_TEST_START(testname); GIMP_TEST_END(test != NULL);

  GIMP_CONST_TEST("GIMP_CHECK_SIZE", GIMP_CHECK_SIZE);
  GIMP_CONST_TEST("GIMP_CHECK_SIZE_SM", GIMP_CHECK_SIZE_SM);
  GIMP_CONST_TEST("GIMP_CHECK_DARK", GIMP_CHECK_DARK);
  GIMP_CONST_TEST("GIMP_CHECK_LIGHT", GIMP_CHECK_LIGHT);

  GIMP_CONST_TEST("GIMP_MIN_IMAGE_SIZE", GIMP_MIN_IMAGE_SIZE);
  GIMP_CONST_TEST("GIMP_MAX_IMAGE_SIZE", GIMP_MAX_IMAGE_SIZE);
  GIMP_CONST_TEST("GIMP_MIN_RESOLUTION", GIMP_MIN_RESOLUTION);
  GIMP_CONST_TEST("GIMP_MAX_RESOLUTION", GIMP_MAX_RESOLUTION);
  GIMP_CONST_TEST("GIMP_MAX_MESIZE", GIMP_MAX_MEMSIZE);

  GIMP_CONST_TEST("GIMP_PARAM_NO_VALIDATE", GIMP_PARAM_NO_VALIDATE);
  GIMP_CONST_TEST("GIMP_PARAM_DONT_SERIALIZE", GIMP_PARAM_DONT_SERIALIZE);
  GIMP_CONST_TEST("GIMP_PARAM_FLAG_SHIFT", GIMP_PARAM_FLAG_SHIFT);
  GIMP_CONST_TEST("GIMP_PARAM_STATIC_STRINGS", GIMP_PARAM_STATIC_STRINGS);
  GIMP_CONST_TEST("GIMP_PARAM_READABLE", GIMP_PARAM_READABLE);
  GIMP_CONST_TEST("GIMP_PARAM_WRITABLE", GIMP_PARAM_WRITABLE);
  GIMP_CONST_TEST("GIMP_PARAM_READWRITE", GIMP_PARAM_READWRITE);

  GIMP_CONST_TEST("GIMP_PARASITE_PERSISTENT", GIMP_PARASITE_PERSISTENT);
  GIMP_CONST_TEST("GIMP_PARASITE_UNDOABLE", GIMP_PARASITE_UNDOABLE);
  GIMP_CONST_TEST("GIMP_PARASITE_ATTACH_PARENT", GIMP_PARASITE_ATTACH_PARENT);
  GIMP_CONST_TEST("GIMP_PARASITE_PARENT_PERSISTENT", GIMP_PARASITE_PARENT_PERSISTENT);
  GIMP_CONST_TEST("GIMP_PARASITE_PARENT_UNDOABLE", GIMP_PARASITE_PARENT_UNDOABLE);
  GIMP_CONST_TEST("GIMP_PARASITE_ATTACH_GRANDPARENT", GIMP_PARASITE_ATTACH_GRANDPARENT);
  GIMP_CONST_TEST("GIMP_PARASITE_GRANDPARENT_PERSISTENT", GIMP_PARASITE_GRANDPARENT_PERSISTENT);
  GIMP_CONST_TEST("GIMP_PARASITE_GRANDPARENT_UNDOABLE", GIMP_PARASITE_GRANDPARENT_UNDOABLE);

  /* FIXME: libgimpbase/gimpparasiteio.h is not listed in gimpbase.h, is that
   * an oversight, or does it need to be included in gimpbase-private.h.
   * It seems that pixpipe is only handled in app, but this const, a struct and
   * several functions are available through Gobject Introspection so we
   * can't just remove it from the API.
   *
  GIMP_CONST_TEST("GIMP_PIXPIPE_MAXDIM", GIMP_PIXPIPE_MAXDIM);
   */

  GIMP_CONST_TEST("GIMP_MAJOR_VERSION", GIMP_MAJOR_VERSION);
  GIMP_CONST_TEST("GIMP_MINOR_VERSION", GIMP_MINOR_VERSION);
  GIMP_CONST_TEST("GIMP_MICRO_VERSION", GIMP_MICRO_VERSION);
  GIMP_CONST_STRING_TEST("GIMP_VERSION", GIMP_VERSION);
  GIMP_CONST_STRING_TEST("GIMP_API_VERSION", GIMP_API_VERSION);

  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_SERIALIZE", GIMP_CONFIG_PARAM_SERIALIZE);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_AGGREGATE", GIMP_CONFIG_PARAM_AGGREGATE);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_RESTART", GIMP_CONFIG_PARAM_RESTART);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_CONFIRM", GIMP_CONFIG_PARAM_CONFIRM);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_DEFAULTS", GIMP_CONFIG_PARAM_DEFAULTS);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_IGNORE", GIMP_CONFIG_PARAM_IGNORE);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_DONT_COMPARE", GIMP_CONFIG_PARAM_DONT_COMPARE);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_FLAG_SHIFT", GIMP_CONFIG_PARAM_FLAG_SHIFT);
  GIMP_CONST_TEST("GIMP_CONFIG_PARAM_FLAGS", GIMP_CONFIG_PARAM_FLAGS);

  /* FIXME This resides in libgimpmodule/gimpmodule.h which isn't referenced
   * from libgimp.h. We can add an include in c-test-header.c, but should we?
   *
  GIMP_CONST_TEST("GIMP_MODULE_ABI_VERSION", GIMP_MODULE_ABI_VERSION);
   */

  /* FIXME We can't test the constants defined in libgimpwidgets here.
   * However, they are defined in GimpUi and probably should be tested
   * separately and only when a display is available. */

  GIMP_TEST_RETURN
}
