# TOP = ..\..\..
# !INCLUDE $(TOP)\glib\build\win32\make.msc

STOCK_VARIABLES = \
	stock_button_anchor	images/stock-button-anchor.png	\
	stock_button_delete	images/stock-button-delete.png	\
	stock_button_duplicate	images/stock-button-duplicate.png	\
	stock_button_edit	images/stock-button-edit.png		\
	stock_button_eye	images/stock-button-eye.png		\
	stock_button_linked	images/stock-button-linked.png	\
	stock_button_lower	images/stock-button-lower.png		\
	stock_button_new	images/stock-button-new.png		\
	stock_button_paste	images/stock-button-paste.png		\
	stock_button_paste_as_new	images/stock-button-paste-as-new.png	\
	stock_button_paste_into	images/stock-button-paste-into.png	\
	stock_button_raise	images/stock-button-raise.png		\
	stock_button_refresh	images/stock-button-refresh.png	\
	stock_button_stroke	images/stock-button-stroke.png	\
	stock_button_to_path	images/stock-button-to-path.png	\
	stock_button_to_selection	images/stock-button-to-selection.png	\
	stock_button_selection_replace	images/stock-button-selection-replace.png	\
	stock_button_selection_add	images/stock-button-selection-add.png		\
	stock_button_selection_subtract	images/stock-button-selection-subtract.png	\
	stock_button_selection_intersect	images/stock-button-selection-intersect.png	\
	stock_button_hchain	images/stock-button-hchain.png		\
	stock_button_hchain_broken	images/stock-button-hchain-broken.png		\
	stock_button_vchain	images/stock-button-vchain.png		\
	stock_button_vchain_broken	images/stock-button-vchain-broken.png		\
	stock_menu_navigation	images/stock-menu-navigation.png		\
	stock_menu_qmask_off	images/stock-menu-qmask-off.png		\
	stock_menu_qmask_on	images/stock-menu-qmask-on.png		\
	stock_wilber_eek	images/stock-wilber-eek.png			\

STOCK_TOOL_VARIABLES = \
	stock_tool_button_airbrush	images/tools/stock-tool-button-airbrush.png			\
	stock_tool_button_bezier_select	images/tools/stock-tool-button-bezier-select.png		\
	stock_tool_button_blend		images/tools/stock-tool-button-blend.png			\
	stock_tool_button_blur	images/tools/stock-tool-button-blur.png			\
	stock_tool_button_brightness_contrast	images/tools/stock-tool-button-brightness-contrast.png	\
	stock_tool_button_bucket_fill	images/tools/stock-tool-button-bucket-fill.png		\
	stock_tool_button_by_color_select	images/tools/stock-tool-button-by-color-select.png		\
	stock_tool_button_clone	images/tools/stock-tool-button-clone.png			\
	stock_tool_button_color_balance	images/tools/stock-tool-button-color-balance.png		\
	stock_tool_button_color_picker	images/tools/stock-tool-button-color-picker.png		\
	stock_tool_button_crop	images/tools/stock-tool-button-crop.png			\
	stock_tool_button_curves	images/tools/stock-tool-button-curves.png			\
	stock_tool_button_dodge	images/tools/stock-tool-button-dodge.png			\
	stock_tool_button_ellipse_select	images/tools/stock-tool-button-ellipse-select.png		\
	stock_tool_button_eraser	images/tools/stock-tool-button-eraser.png			\
	stock_tool_button_flip	images/tools/stock-tool-button-flip.png			\
	stock_tool_button_free_select	images/tools/stock-tool-button-free-select.png		\
	stock_tool_button_fuzzy_select	images/tools/stock-tool-button-fuzzy-select.png		\
	stock_tool_button_histogram	images/tools/stock-tool-button-histogram.png			\
	stock_tool_button_hue_saturation	images/tools/stock-tool-button-hue-saturation.png		\
	stock_tool_button_ink	images/tools/stock-tool-button-ink.png			\
	stock_tool_button_iscissors	images/tools/stock-tool-button-iscissors.png			\
	stock_tool_button_levels	images/tools/stock-tool-button-levels.png			\
	stock_tool_button_measure	images/tools/stock-tool-button-measure.png			\
	stock_tool_button_move	images/tools/stock-tool-button-move.png			\
	stock_tool_button_paintbrush	images/tools/stock-tool-button-paintbrush.png			\
	stock_tool_button_path	images/tools/stock-tool-button-path.png			\
	stock_tool_button_pencil	images/tools/stock-tool-button-pencil.png			\
	stock_tool_button_perspective	images/tools/stock-tool-button-perspective.png		\
	stock_tool_button_posterize	images/tools/stock-tool-button-posterize.png			\
	stock_tool_button_rect_select	images/tools/stock-tool-button-rect-select.png		\
	stock_tool_button_rotate	images/tools/stock-tool-button-rotate.png			\
	stock_tool_button_scale	images/tools/stock-tool-button-scale.png			\
	stock_tool_button_shear	images/tools/stock-tool-button-shear.png			\
	stock_tool_button_smudge	images/tools/stock-tool-button-smudge.png			\
	stock_tool_button_text	images/tools/stock-tool-button-text.png			\
	stock_tool_button_threshold	images/tools/stock-tool-button-threshold.png			\
	stock_tool_button_zoom	images/tools/stock-tool-button-zoom.png			\

WILBER_VARIABLES = \
	stock_wilber_16_16	images/stock-wilber-16x16.png		\
	stock_wilber_32_32	images/stock-wilber-32x32.png		\
	stock_wilber_48_48	images/stock-wilber-48x48.png		\
	stock_wilber_64_64	images/stock-wilber-64x64.png		\

all: \
	gimp-stock-pixbufs.h \
	gimp-wilber-pixbufs.h


gimp-stock-pixbufs.h: $(STOCK_IMAGES) makefile.msc
	gdk-pixbuf-csource --raw --build-list $(STOCK_VARIABLES) $(STOCK_TOOL_VARIABLES) > gimp-stock-pixbufs.h

gimp-wilber-pixbufs.h: $(WILBER_IMAGES) makefile.msc
	gdk-pixbuf-csource --raw --build-list $(WILBER_VARIABLES) > gimp-wilber-pixbufs.h
